### ISSUE TITLE
Bug: Mobile number validation accepts 3xxxxxx, 4xxxxxx, etc. numbers

### ISSUE THREAD

**Issue by leonardloo** [opengovsg/formsg#100]
Mobile numbers in Singapore start with either 8 or 9. While numbers starting with 6 are rejected, oddly enough numbers starting with 1,2,3,4,5,7 are accepted. Don't remember this being there previously. Better to patch this quickly as this means validation isn't really working.

**Comment by karrui** [comment]
Remember the bug where mobile field validation was too strong and legit numbers are being rejected? Mobile field validation was then loosened again to only validate against the length....

I guess I can add validation to only accept numbers starting with 8/9s :(
