### ISSUE TITLE
Show response summary on thank you page

### ISSUE THREAD

**Issue by r00dgirl** [opengovsg/FormSG#1052]
why?
Requested by public users as well as form admin
for public users to have record of submission if email ack has not been set by form admin
way for Storage mode respondents to have record of submission which is not currently possible

todo:
show form response on Thank You page
its ok if its long

**Comment by liangyuanruo** [comment]
@syan-syan we should also use this page to double as checkout before proceeding to payment

**Comment by syan-syan** [comment]
@pearlyong @f1zaz btw updated requirement above "Show date and time of submission prominently as this is often used at visitor declarations etc for someone to sight"

**Comment by pearlyong** [comment]
Figma screens for Desktop and Mobile [here](https://www.figma.com/file/ta5tjjBqphML8LPRkmxD53/DesignMaster_v2?node-id=1166%3A246)

**Comment by syan-syan** [comment]
update: after more investigation, download pdf will give rise to more edge cases than initially anticipated, pivot to showing response in html on thank you page instead

**Comment by syan-syan** [comment]
update: deferring to after react to make use of react-based package
