### ISSUE TITLE
Technical design for Storage mode agency key 

### ISSUE THREAD

**Issue by r00dgirl** [opengovsg/FormSG#11]
**Problem**: Prevent loss of Storage mode response data due to form admins losing secret keys. Loss of keys is expected especially over time with the form changing hands. However loss of response data undermines public confidence in the government, and could have individually significant consequences for form respondents (e.g. financial aid application).

**Technical design**

[Design document here](https://docs.google.com/document/d/1k94IILZnkHGVzEyDUeOP_Wd7ZP9H1laeI9Hs3A8DgFQ/edit) 

Agency central key in the hands of CIO/CISO. Each new form key will be encrypted by agency’s public key and stored in agencyKey table for CIO retrieval with his private key. If agency private key is lost, have to manually contact each form owner to get private keys to re-encrypt with new agency key. 

To be implemented after React rewrite

**Comment by tshuli** [comment]
Moved to linear
