### ISSUE TITLE
Sort options alphabetically

### ISSUE THREAD

**Issue by r00dgirl** [opengovsg/FormSG#1102]
Sorting options alphabetically helps respondents find the desired option within a long list

Number of forms with >10 options caa 30 Oct 2020:
dropdown | 18932
radiobutton | 3151
checkbox | 2579
Overall UNIQUE | 10561

**Comment by siuting0511** [comment]
I can build a sorting function for this, can I be assigned?

**Comment by mantariksh** [comment]
pending design. should be an option for form admins to sort in-browser rather than sorting for respondents on retrieval

**Comment by Raphael2908** [comment]
May I contribute if the designs are out?
