### ISSUE TITLE
[API-post] Deprecate PUT /{formId}/adminform API endpoint

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#1210]
Updates to more than one nested property in the forms schema result in the entire nested object being overridden.

For example, if implementing webhook retries, updating the new `form.webhooks.retries` parameter would cause `form.webhooks.webhookUrl` to be overridden because the use of `assignIn` in the `updateForm` function only merges objects shallowly, such that the entire `form.webhooks` is replaced.

A previous attempt to fix this with recursive merge behavior had to be reverted in https://github.com/opengovsg/FormSG/pull/1115, because logic fields actually rely on shallow merge behavior to replace the entire logic fields array.

This bug has not affected production yet because we currently do not have more than one nested property in the form schema.

**Comment by syan-syan** [comment]
depends on API refactoring
