### ISSUE TITLE
Determine whether MyInfo returns error-description or error_description

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#1211]
When there is an error during the consent flow,
1. The MyInfo documentation states that a query parameter called `error_description` will be returned
2. Mockpass returns `error_description`
3. MyInfo Staging returns `error-description` (note hyphen, not underscore)

Currently, the code supports both. When we confirm what production returns,
1. if `error_description`, then keep current code
2. if `error-description` then open PR in Mockpass to change `error_description` to `error-description`

**Comment by liangyuanruo** [comment]
@mantariksh deviation from documentation is also a bug - we should file a report with MyInfo

**Comment by liangyuanruo** [comment]
Incorporate into #1234
