### ISSUE TITLE
Pre-fill competitive research and safeguards

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#1215]
Pre-fills are valuable because
- support collection of valuable data that might otherwise be unfeasible to collect (e.g. form is too long, few respondents willing to fill up)
- support collection of accurate data (e.g. serial numbers like covid test form)
- save respondents' time

We've already implemented url-based pre-fill but its currently only available to the Covid ops forms, as we did not then have the time to think through and design safeguards against potential scams in general use cases. To launch prefill mainstream and allow other use cases to benefit, we want to **refine this feature's design to minimise the likelihood that form respondents will fall prey to scams involving a malicious actor pre-filling a value and tricking them into submitting the form.**

**Competitive research**: on other designs that aim to fulfil a similar goal, i.e. alert users to pre-filled/untrusted values and allow them to correct the values, especially in a form filling context

**Design**: safeguards for Form's context, options include
- allow form admins to selectively enable pre-fill on a field: it will not be allowed by default
- prompt form admins that are enabling pre-fill to reconsider if this action would create an opening for a scam "especially for use cases with financial implications", "anyone can generate a pre-filled URL and send the link to another respondent" 
- communicate to respondents that this value (or these x values) has been pre-filled from the URL/link they clicked on and "Please check that these values are correct / accurate / what you intended"
- make it possible for respondents to edit or remove untrusted values

**Comment by syan-syan** [comment]
check out:
prepopulate.jotform.io

**Comment by pearlyong** [comment]
Figma [here](https://www.figma.com/file/ta5tjjBqphML8LPRkmxD53/DesignMaster_v2?node-id=1366%3A629)

We’re proposing using colour to denote the prefilled fields, along with a warning infobox at the top.
