### ISSUE TITLE
Convert Mongoose "set" hooks to validators

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#1222]
Some keys in Mongoose models have validators and some have "set" hooks. This makes behaviour inconsistent when documents are invalid. Examples: `authType` in form model and `includeFormSummary` in `emailField`model.

**Comment by seaerchin** [comment]
Another thing to note is that this affects the order of assignment. In `authType` for `form.server.model`, if you set status to be public before assigning authType, this defaults the authType to NIL instead of the expected behaviour where authType is set successfully
