### ISSUE TITLE
Post-MyInfo migration cleanup and hardening

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#1234]
Unit tests should be added for all new functions added during the V3 migration.

**Comment by liangyuanruo** [comment]
Expanding this to cover additional
- [ ] Convert and combine new AngularJS services into a single TypeScript client service
- [ ] Publish and integrate with latest MyInfoGovClient version

**Comment by liangyuanruo** [comment]
# Discrepancies  with MyInfo

## error-description query parameter
When there is an error during the consent flow,
1. The MyInfo documentation states that a query parameter called `error_description` will be returned
2. Mockpass returns `error_description`
3. MyInfo Staging returns `error-description` (note hyphen, not underscore)

Currently, the code supports both. When we confirm what production returns,
1. if `error_description`, then keep current code
2. if `error-description` then open PR in Mockpass to change `error_description` to `error-description`
