### ISSUE TITLE
Misalignment of COVID templates, secret key download buttons on IE11, UI/copy fixes

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#124]
- [ ] fix misalignment of covid templates

- [ ] fix misalignment of Save your Secret Key modal download buttons 

- [ ] change 'NRIC' field to say 'NRIC/FIN' on the UI and default field name. any side effects? 

- [ ] change 'Date range validation' to say 'Restrict dates' 

These layout issues should be fixed so that issues does not linger in production before embarking on a React migration.

COVID templates
![image](https://user-images.githubusercontent.com/5690550/89976822-290dca80-dc9c-11ea-84ec-f9bf649c5a35.png)

Secret Key Download/Copy buttons
![image](https://user-images.githubusercontent.com/5690550/89976851-39be4080-dc9c-11ea-8ca8-05bc15dbce16.png)

**Comment by syan-syan** [comment]
sneaked in ui/copy fixes

**Comment by syan-syan** [comment]
these should all be done except changing NRIC to NRIC/FIN
