### ISSUE TITLE
UEN field

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#1273]
- Helps to reduce typos in UENs and ensure data accuracy

https://gist.github.com/mervintankw/90d5660c6ab03a83ddf77fa8199a0e52

**Comment by aniruddha-adhikary** [comment]
@syan-syan Is the objective of this ticket to introduce a new Field Type for UENs? Could some more information be provided? I am interested to contribute. 🚀

**Comment by mantariksh** [comment]
@aniruddha-adhikary That's right! Broadly the implementation will involve:
1. Adding a new database schema for UEN fields
2. Adding the UEN field on the admin Build tab so admins can add it to their forms
3. Adding validation on the frontend to ensure that form-fillers are prevented from submitting invalid UENs via the UI
4. Adding backend validation to ensure that submitted UEN answers are valid

**Comment by aniruddha-adhikary** [comment]
@mantariksh thanks for getting back to me on this!

I was wondering if it would be a good idea to merge the NRIC/FIN and UEN fields in a single field. There could be a selector to select whether users could enter NRIC/FIN, UEN or Both. It would make the widgets panel less bloated.

**Comment by aniruddha-adhikary** [comment]
#2100 should close this :)
