### ISSUE TITLE
Constrain email field domain model to prevent inconsistencies

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#1312]
The `hasAllowedEmailDomains` boolean property on the email field schema is used to support the toggle in the UI. Explicitly saving this boolean into the database can be problematic because it can result in inconsistent database state, which occurs when `hasAllowedEmailDomains` is `true` and yet `allowedEmailDomains` is empty.

We can constrain the model by using an empty `allowedEmailDomains` array to replace the false value of `hasAllowedEmailDomains`. The toggle behavior can be recovered by simply having the frontend controller inspect the length of the array.

**Comment by karrui** [comment]
Blocked by https://github.com/opengovsg/FormSG/issues/1481
