### ISSUE TITLE
[Feature] List of my own forms behaves erratically

### ISSUE THREAD

**Issue by glycoaddict** [opengovsg/FormSG#1356]
As an end user of maybe 50-60 forms,
I want to be able to find the correct form from the whole list. 
But currently I (1) can only see the first few characters of each item, which is insufficient to distinguish between the 50 forms I have, 
(2) order of list is non alphabetical and changes every time I open a form. 

I expect the forms to be sorted alphabetically and to display the full names.

I can code this but need some help where to start.

**Comment by syan-syan** [comment]
hey @glycoaddict, we increased number of visible characters last year as a quick fix - the **final fix** is supposed to be a **list view of all forms** that will be introduced together with React migration in Q3. 

we can possibly increase visible text further to 3 or 4 lines in the meantime.

**Comment by liangyuanruo** [comment]
The forms also re-sort themselves based on the last modified timestamp.

**Comment by syan-syan** [comment]
this will be fixed in ux revamp with react migration - will be a list of forms
