### ISSUE TITLE
Move model and API params/body types to `shared` directory

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#1382]
These types will most likely be shared across both the frontend and backend now that the frontend services is about to be refactored to TypeScript, to prevent duplication and desync of frontend and backend types. We should move the shareable types to the `shared` directory. For example,

to update settings, the type
```ts
type SettingsUpdateBody = Partial<{
  authType: NonNullable<IForm['authType']>
  emails: NonNullable<IForm['emails']>
  esrvcId: NonNullable<IForm['esrvcId']>
  hasCaptcha: NonNullable<IForm['hasCaptcha']>
  inactiveMessage: NonNullable<IForm['inactiveMessage']>
  permissionList: NonNullable<IForm['permissionList']>
  status: NonNullable<IForm['status']>
  title: NonNullable<IForm['title']>
  webhook: NonNullable<IForm['webhook']>
}>
```
is written, but this type relies on the `IForm` type.  Thus, the IForm type will need to be located in the shared folder too. 

This will probably not be the only case and we should just move all model types currently in `src/types` to a `shared/` directory in root (in preparation for React migration?)

**Comment by liangyuanruo** [comment]
@karrui data that cross the API boundary are called [_data transfer objects_](https://en.wikipedia.org/wiki/Data_transfer_object) or DTOs, and the naming of their types should reflect as much. I think most of your suggestion makes sense, but the schema types clearly belong in the backend and should probably stay there.

**Comment by karrui** [comment]
Not really linked to typescriptify backend milestone since this is changing the directory of already typescripted files :P

**Comment by karrui** [comment]
On further thought, this may be more complicated than just moving the types, since model types depend on `mongoose` and we obviously do not want to import `mongoose` on the client side.

We may end up having to split up the types anyways using primitives on the client side and `mongoose` types on the server side, defeating the purpose of moving the types a level higher into the root.

Thoughts @liangyuanruo ?
