### ISSUE TITLE
Investigate Babel configuration to target IE11 / ES5

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#14]
Babel should be transpiling code to be ES5 / IE11-compatible. Currently IE11 is specified as a target browser in `.babelrc` file, yet `Object.values` was not transpiled.

Additionally - check if polyfills from `polyfills.js` are being added by babel e.g. `whatwg-fetch`

@mantariksh said: I investigated this for a while today but didn't get very far. Tried using the `useBuiltIns` option for Babel but it didn't help. I'm pretty sure the polyfills are being imported though, both from inspection of `bundle.js` and the fact that downloading storage mode attachments works in IE11 (hence `fetch` is definitely working). I'm setting this aside for now to work on other things.

**Comment by liangyuanruo** [comment]
Fixed in https://github.com/opengovsg/FormSG/pull/981
