### ISSUE TITLE
Browser history changed after visiting form

### ISSUE THREAD

**Issue by dlqs** [opengovsg/FormSG#1411]
After visiting the form at https://form.gov.sg/#!/5f87f246e7354600116fb63e, my browser's back button takes me back to https://form.gov.sg/#!/ instead of the page I was at previously. The browser's history was changed.

To replicate:
1. Visit https://safetravel.ica.gov.sg/sc-pr/opt-out/apply-now
2. Click on the go link
3. Wait for the form to load, then click your browser's back button
4. End up at https://form.gov.sg/#!/

Browser: Firefox 85

**Comment by syan-syan** [comment]
@dlqs thanks for opening this issue. we expect this to be fixed with our react migration and have opened another issue prior on the entire back button experience in formsg.
