### ISSUE TITLE
Response cap/limit

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#148]
Disable form when x number of responses reached 

**Why**

helpful for limiting slots to signup forms which are est. at least 4% of all forms. Registration is also third biggest use case.

**Details**

- new key on forms collection responseLimit
- formStatisticsTotal is currently updated via batch job every 24h. we need to change this to update when each response is submitted.
- deactivate form once response count >= response limit. any response submitted after is a response submitted to a deactivated form 
- need to add to form activation: check that response limit has not been exceeded. if it has, show red error toaster at page top "Error: Form cannot be activated as response limit has been reached"
- response limit can be revised after it is set
- should be able to disable response limit entirely after setting it, in which case responses are unlimited

- if response limit is revised to a number lower than current response count, error message saying "Response limit must be higher than already received responses (35)"
- if response limit set to 0, show red toaster on field "Please enter a number bigger than 0"
- if decimal entered, show red toaster on field "Please enter a number without decimals"
- if response limit is enabled but not specified (blank field), it does not save

**Screens**

https://www.figma.com/file/ta5tjjBqphML8LPRkmxD53/DesignMaster_v2?node-id=1020%3A1148

**Related features**

- response limit within x timeframe
- choice limit 
- form expiry
- Enable reCaptcha must be selected to enable response limit

**Comment by shuli-ogp** [comment]
As discussed during sync-up, to KIV for now

**Comment by pearlyong** [comment]
figma screens here
https://www.figma.com/file/ta5tjjBqphML8LPRkmxD53/DesignMaster_v2?node-id=1020%3A1148

**Comment by syan-syan** [comment]
### Design document

meaning submission will increment some formSubmission document instead of performing a batch job on submissions. Might speed it up

mongo increment is atomic since it is on the document level and I am fairly sure it will not bottleneck if we index properly.
Concurrency issues should not be there since wiredtiger engine has document level locking, but yes may introduce bottlenecks and we should test that.
If we update mongodb to 4.0, we can even have multidoc transactions.

i think this formSubmissions increment approach should be faster than retrieving the current number of submissions for the form, then deactivate it if the number exceeds the threshold?

the bottleneck won't come from the document lookup, but from the increment operation because only one thread can have write access to it at one time


Mongo document index on submission collection with formId, every submission query for number of current submissions
	This one slowish????

Submission has all the data
{ formId, encryptedContent, time }

submissionMetadata collection
	{ formId, _id }

{ formId, _id, count }
Everytime submit inc count
10000 ppl submit at same time -- concurrency problems?
Gut feeling is it will be fine, because mongodb has document level atomicity. And document level locking.
Problem is only how big the queue is before bottleneck
Every submission = new row in metadata. Same problem as submission collection, but at least metadata has less data
Submission => query submissionMetadata for all metadata with formId, return count.

All of these have chance to desync because 1 submission = 2 writes in separate collections
	Our mongodb version is 3.6. EOL.
	Will be mitigated by 4.0 multidoc transactions


???? More suggestions



If users need 2000, we just need to count 2000 https://stackoverflow.com/questions/9778420/mongo-count-really-slow-when-there-are-millions-of-records. This means we should not allow a response cap limit that’s too high (e.g. 50,000).

Questions

Response count limit is set to 200 and there are already 199 responses. Then, 10 people are filling up their forms at the same time. With this response count limit, what will happen to the 9 people who submitted later?

“We have already received 200 responses. Please be aware that your response may not be accepted.”

**Comment by leonardloo** [comment]
When someone arrives at form, Check `count(submissions) where id = form_id` to be > `forms - allowedSubmissions` variable, if so disable submission. This is the naive approach - is it not good enough?

I believe what Sonjia is suggesting is: Check `forms - submissionCount` to be > `forms - allowedSubmissions` to disable submission. Practically checking `count(submissions)` for one form id should be fast enough?

Another suggestion built on top of Sonjia's: Decrement `forms - remainingSubmissions` after each submission, and check if it is <= 0, so we need not add another key.

**Comment by syan-syan** [comment]
@leonardloo btw since the batch job has been failing, we also wanted to replace the way we updated formstatstotal as an additional goal
