### ISSUE TITLE
Combine submission middlewares into controllers

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#149]
Blocked by #144

Many of our middleware functions are being chained together and used as services, which is an [anti-pattern](https://insertafter.com/en/blog/no_more_middlewares.html). This causes problems such as having long-range object and type dependencies, which must be overridden by the developer with type assertions.

A better solution where possible, is to merge middlewares into a single controller function as far as possible so that dependencies are clearly defined.

**Comment by arshadali172** [comment]
- [ ] Webhook controller should be removed and webhook service referenced in the submission controller

**Comment by liangyuanruo** [comment]
@karrui @tshuli i had a discussion with @mantariksh today, and we thought that instead of chaining middlewares, we can group relevant parts of the `celebrate` middleware together.

For example, instead of doing this:

```typescript
app.route(...).post(
  celebrate({
    body: Joi.object({
        valueA: Joi.string(),
        valueB: Joi.boolean()
    })
  })
  middlewareUsingValueA, // naked middleware function with implicit
  middlewareUsingValueB, // dependency on upstream middleware for protection
)
```

We can do this instead:

```typescript
// Exported together so that it's not possible to
// use middleware without protection
export const middlewareUsingValueA = [
  celebrate({
    body: Joi.object({
        valueA: Joi.string(),
    })
  }),
  (req, res, next) => {...} // or implemented as a separate function
]

export const middlewareUsingValueB = [
  celebrate({
    body: Joi.object({
        valueB: Joi.string(),
    })
  }),
  (req, res, next) => {...}
]

app.route(...).post(
  middlewareUsingValueA,
  middlewareUsingValueB
)
```

**Comment by liangyuanruo** [comment]
Note: to also refactor associated routes for

- [ ] VerifiedContentMiddleware.encryptVerifiedSpcpFields
- [ ] EncryptSubmissionMiddleware.prepareEncryptSubmission
- [ ] encryptSubmissions.saveResponseToDb
- [ ] webhookVerifiedContentFactory.post
- [ ] SubmissionsMiddleware.sendEmailConfirmations
