### ISSUE TITLE
Migrate betas.client.factory.js to TypeScript

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#1506]
The _Betas_ service is used to manage user access to hidden features in the codebase based on the beta flag permissions within the _user_ object. Originally slated for removal, this has found new use with sgID and should be migrated to TS.

**Comment by karrui** [comment]
the beta flags are also cleared in the DB and not used anymore so all traces should be safe to remove. I will pick up this issue once it's been assigned a priority @liangyuanruo @syan-syan
