### ISSUE TITLE
Convert form-fields.client.service.js to TypeScript

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#1515]
The FormFields service holds a collection of disparate utility functions. Instead of straightforward conversion to TypeScript, consider also whether these functions are applicable to a future React codebase, and weigh future needs against the cost of refactoring existing AngularJS code.

**Comment by karrui** [comment]
This may not be needed for React, as each Field will be its own component and perform its own logic. This service is currently mainly used in Table fields, and should be handled by its corresponding React TableField component.
