### ISSUE TITLE
Convert rating.client.service.js into TypeScript enums

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#1516]
This service encodes the steps and shape of the rating field. It should be straightforward to convert to an enum, but do also perform a check to ensure that the DRY principle is followed and that any new data created is consistent with existing backend definitions.

**Comment by karrui** [comment]
Similar to #1503, this may not actually need to be migrated

**Comment by mantariksh** [comment]
Closed via #1955
