### ISSUE TITLE
[API] Migrate verifed field related endpoints to new /api counterparts

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#1522]
This issue tracks the migration of verified field related endpoints to their new `api/forms/:formId/fieldverifications` counterparts.

The old endpoint should not be deleted for backwards compatibility (at least for a few weeks after the new endpoint has been released).

The current to new mapping is shown below:

\# | Existing endpoints | New endpoints<br>(note that all routes are prefixed with /api/v3) | Description
-- | -- | --|--|
1 | POST /transaction  body: { formId } | POST /forms/:formId/fieldverifications | create verification transaction instance
2 | GET /transaction/:transactionId | GET /forms/:formId/fieldverifications/:id | retrieve transaction by id
3 | POST /transaction/:transactionId/reset<br>body: { fieldId } | POST /forms/:formId/fieldverifications/:id/fields/:fieldId/reset | reset field verification by id
4 | POST /transaction/:transactionId/otp<br>body: { fieldId, answer } | POST /forms/:formId/fieldverifications/:id/fields/:fieldId/otp/generate<br>body: { answer, fieldType } | generate OTP for field
5 | POST /transaction/:transactionId/otp/verify<br>body: { fieldId, otp} | POST /forms/:formId/fieldverifications/:id/fields/:fieldId/otp/verify<br>body: { otp } | verify OTP for field

**Comment by seaerchin** [comment]
@karrui not migrating #2 as per the PR because it's unused

**Comment by seaerchin** [comment]
@karrui what do you feel about changing the endpoint for 3-5 to the plural form

**Comment by karrui** [comment]
> @karrui what do you feel about changing the endpoint for 3-5 to the plural form

pls do idk why i missed those

**Comment by seaerchin** [comment]
@karrui are we fully trustring the frontend on the otp generation side? from what i can see, `answer` can be any string - should we instead discriminate on the `type` of answer? (otp/email) and then validate that too

**Comment by seaerchin** [comment]
per discussion, will do the above
