### ISSUE TITLE
Properly enable eslint-plugin-jest by inlining into root .eslintrc

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#1575]
Tests are code, just like the rest of the application. Our Jest test suite is expanding and may soon reach a state where its maintenance is non-negligible.

This issue suggests the addition of [eslint-plugin-jest](https://www.npmjs.com/package/eslint-plugin-jest) in order to help the team conform to better coding practices.

**Comment by karrui** [comment]
This is already in our codebase, just in a different eslint file :P. See `tests/unit/backend/.eslintrc`

**Comment by karrui** [comment]
Oh, but now that our tests are outside of the `tests` directory... we might need to inline that into our root .eslintrc

**Comment by liangyuanruo** [comment]
Thanks @karrui , will close.

**Comment by karrui** [comment]
Sorry for the confusion, it's also already in the root [.eslintrc](https://github.com/opengovsg/FormSG/blob/develop/.eslintrc#L66). Can feel free to close this issue again HAHA
