### ISSUE TITLE
Migrate public-forms.server.routes.js to TypeScript

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#1582]
The encrypt submissions endpoint should be moved to the encrypt submissions module, and the remaining endpoints should be moved to the public-form module.

**Comment by seaerchin** [comment]
i think #1513 is the same as this

**Comment by mantariksh** [comment]
@seaerchin nope that one is duplication + migrating the frontend to the new endpoint, this one is migrating the existing endpoints to a new router in typescript

**Comment by mantariksh** [comment]
Blocked by #1561, #1398
