### ISSUE TITLE
Bulk download attachments on Storage mode

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#16]
**Problem**
Currently users have to individually download attachments on the corresponding response view in FormSG. The exported csv shows filename. If users receive a high volume of responses and every one of them has an attachment, individually downloading attachments is going to be a pain in the ass.

How do we make attachment downloads more convenient for users, and best support whatever they need to do with attachments after?

**Why users have to download attachments rather than just viewing them**

For common use cases like applications, users often need to bring up attachments again or send them to other parties for downstream stages of the process.
e.g. need to bring up CV and personal statement again if applicant is shortlisted through later rounds

**Immediate implementation**

summary: https://docs.google.com/document/d/1nzUHQDzo4WBA67xdy0a3A3nJLCeKVSzjzPtJebtS9xQ/edit#heading=h.ypu06omk303h

1. Previous discussions were halted because downloading all attachments within x date range in 1 zip file was not technically feasible. 

2. Alternative was to have browser download 1 zip file (per response) at a time, but would not be a great UX, as user has to click twice (unzip, then open folder) just to access each response's attachments. 

Do we have a better option than option 2?

**Screens**
https://app.zeplin.io/project/5b29ffde48eaaf6318d01b05/dashboard?seid=5f87c5ed5cf4fc4b800abbde

**Longer term**
- Look at Zendesk extension
- Explore service worker and saving to disk

**Comment by leonardloo** [comment]
@frankchn @syan-syan @liangyuanruo 

Looked at Jotform. They have e2ee forms but not for files. Files are not encrypted.

I'm against bulk downloads for two reasons: a) load on our servers and b) load on agency browsers. This load is non-trivial as we have seen from e2ee text.

How about we:
1. Place https://form.gov.sg/formid/submissionid in downloaded csv
2. On click, open up this response in the UI
2a. If user is not logged in or authorised to this formid, show a 403/404
2b. If user is logged in, prompt him for secret key then unlock this submission
2c. If user has entered secret key before, save it in session storage. Alternatively, save public key in session storage, which is used to encrypt secret key to temporarily store it on our servers with a short expiry.

Having a link in the Excel is likely the most intuitive way users view files. Google Forms, JotForm, TypeForm all do it that way.

**Comment by liangyuanruo** [comment]
session storage is only persistent within the same browser window. we'll have to use local storage instead, and that will persist the key on the browser for much longer.

if we want to do this, we should build out the caching mechanism within the app first for existing UX first.

**Comment by frankchn** [comment]
@liangyuanruo @leonardloo 

What do you think of transferring sharing secret keys [by something like `BroadcastChannel` to request a secret key from another tab if it is already open](https://developers.google.com/web/updates/2016/09/broadcastchannel)? 

I am envisioning a new tab being opened with a direct link to the response page, and upon load, the new tab will call `postMessage({action: requestSecretKey, formId: whatever})` when it displays the prompt for the user to upload/enter the secret key.

Any other tab that already has the secret key loaded can respond by calling `postMessage({action: secretKey, formId: whatever, secretKey: secret})`. The secret key received from the other tab is treated the same way as if it is entered by the user, and loading proceeds as normal after that.

`BroadcastChannel` is for scripts from the same origin (unlike `window.postMessage`) so it should be as secure as secret key handling is now. We don't touch either sessionStorage or localStorage, so there shouldn't be any further security implications.

The only downside I can see is that IE11 doesn't support this API.

**Comment by frankchn** [comment]
Also, if the user opens a bunch of tabs at once, once the user uploads the key to one tab, that tab can `postMessage({action: secretKey, formId: whatever, secretKey: secret})` and all the other tabs will receive the same key and proceed with loading too.

**Comment by syan-syan** [comment]
to resolve
- web workers for optimisation
- bulk endpoint on server
- error handling

**Comment by syan-syan** [comment]
### Points we need to communicate to users for this implementation, not final copy

**Pre-download user messaging**
- (if threshold exceeded) You are attempting to download attachments for 10,943 responses. We recommend adjusting the date range to 1,000 responses. Downloading for >1000 responses might cause overheating or browser unresponsiveness on slower devices. GO BACK vs PROCEED ANYWAY
- (if threshold not exceeded) Downloading attachments for 838 responses
- Downloading might take 30 minutes or more (number here depends on our testing)
- Attachments will be downloaded as one zip file per response. Up to 838 zipped responses will be downloaded into your destination folder.
- To stop the download, close your browser

Eventually we can also detect attachment capacity of form and change the threshold number accordingly, but lets keep it out of 1st iteration as additional code required.

@liangyuanruo please add on if I missed out anything
@pearlyong @f1zaz

**Comment by pearlyong** [comment]
Styling changes

**Search icon and field** 
Position should be on the right, beside the date field. Can see [Zeplin](https://zpl.io/bovokqg) for reference.  For behaviour, can see the Search icon in the Examples page. On click it should display field and focus. There should also be an X to close, which will return it to an icon, and all results will be displayed again.

**Dropdown field** 
Can see [Zeplin](https://zpl.io/bPeN7xy) for reference. Can use the same component as in the Examples page (Agency dropdown sort)

**Download attachments modal** 
Can we use same modal styling as the one that is used while downloading? No border radius, Header styling, centre align all content, and centre in page

**Downloading button**
Can we change the Downloading button on the responses page to a loading one with a spinner when attachments are downloading?

For copy, i will update this thread again today/tomorrow.

**Comment by pearlyong** [comment]
**Updates in Figma:**
https://www.figma.com/file/ta5tjjBqphML8LPRkmxD53/DesignMaster_v2?node-id=928%3A45

- Copy to reflect above
- Included beta flag which should link to guide.form.gov.sg on what a Beta feature is, and possible consequences
- Warning to inform users to download below the threshold allowed to avoid overheating

**Comment by pearlyong** [comment]
**Updated copy in [Figma](https://www.figma.com/file/ta5tjjBqphML8LPRkmxD53/DesignMaster_v2?node-id=928%3A45) to reflect the following:**

- Warning messages (Do not use Internet Explorer, Your network connectivity is strong, Your device has sufficient disk space for the download)
- Estimated time to download
- Download stopped
- Download complete (with error)
