### ISSUE TITLE
investigate usage of individual response views

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#1673]
**aim**
this will help determine whether we keep individual response views in form v3 or simply have csv download

**todo**
- find out how many individual response views in a recent 1 month period
- find out how many csv downloads triggered in the same 1 month period

**Comment by karrui** [comment]
**find out how many individual response views in a recent 1 month period**
```
fields @timestamp, meta.userId, @message
| filter meta.req.url like '/adminform/submissions?submissionId'
| parse meta.req.url '/*/adminform/submissions?submissionId=*' as formId, submissionId
```
**Results**
**155,441** records matched from 20 March to 20 April 2021

**Comment by karrui** [comment]
**find out how many csv downloads triggered in the same 1 month period**
This includes both downloadAttachment calls and normal downloads, and date range ones. 
```
fields @timestamp, meta.userId, @message
| filter message = 'Stream encrypted responses closed'
| parse meta.urlWithQueryParams '/*/adminform/submissions/download*' as formId, params
# Blank because our URL endpoints changed to the /api/v3/ variant, this ensures accurate counts pre-v3
| filter not isblank(params)
```
**Results**
32,823 records matched from 20 March to 20 April 2021
