### ISSUE TITLE
Changes to Settings Authentication section

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#1675]
So that users more easily understand that they need one eservice ID for Singpass and another for Corppass:

Change placeholder text of e-service ID boxes to "Enter Singpass e-service ID" for Singpass / MyInfo (Individual) vs "Enter Corppass e-service ID" for Singpass (Corporate)

**Comment by mantariksh** [comment]
@syan-syan yo this is actually a _really_ hard issue - in order to squash Singpass and Singpass (MyInfo), the authType has to be changed behind the scenes, and every time MyInfo fields are added/removed the database state needs to be kept in sync.

**Comment by karrui** [comment]
Adding the discussion tag for ... discussion during kanban mondays (i'm coining that term)
