### ISSUE TITLE
Joining of Mongo error messages results in walls of text

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#1694]
When a user attempts to edit a form and encounters one or more validation errors, the server combines all the validation error messages into a single comma-separated string and returns it to the client. This normally works fine because a client would normally encounter only one validation error at the time. However, in rare edge cases, they might end up with something like this:

![Screenshot 2021-04-21 at 10 17 16 AM](https://user-images.githubusercontent.com/29480346/115487484-5e3ad580-a28b-11eb-9f5b-635fe0240347.png)

Error messages should be made more readable in case of multiple validation errors.

**Comment by syan-syan** [comment]
@mantariksh @frankchn can work on this next, will require some thinking on how best to clean up

**Comment by frankchn** [comment]
Deduplicate error message at https://github.com/opengovsg/FormSG/blob/aecc1dbd44b4258584819a2b3e822347c1446be9/src/app/utils/handle-mongo-error.ts#L21
