### ISSUE TITLE
eServiceId appears to not be validated for Singpass or Corppass

### ISSUE THREAD

**Issue by seaerchin** [opengovsg/FormSG#1705]
## Problem 
FormSG adopts a 2 step approach to validating eServiceId to ensure no fake forms are being created.

currently, the 2 steps are 
1. frontend checks for alphanumeric and length between 1 and 25 
2. backend check to validate that it is a valid eserviceId.

currently, the second check is buggy and always returns true to any eserviceId.

## Steps to reproduce
1. create a form requiring authentication 
2. set eServiceId as 0 (for Singpass or Corppass)
3. activate the form
4. go to the form and click login

this results in an error page greeting the user

**Comment by karrui** [comment]
Closed by #1706
