### ISSUE TITLE
Date field validations

### ISSUE THREAD

**Issue by r00dgirl** [opengovsg/FormSG#1736]
### Problem

the following additional date validations were requested by a pharmacy user with 6k responses per month, with potential to expand to many other booking/delivery use cases as in user research here https://docs.google.com/spreadsheets/d/1ctE5EfhHkoNM0naw1zuXgdCRZpJ6RBG_TfXDa3gS23s/edit#gid=664269691

- No weekends
- No public holidays
- Rolling x-day period, y days after today

### Observations

Requested validations can be abstracted as such, allowing feature to be more flexible and also serving more use cases

- Exclude choice of: Mon, Tue, Wed, Thu, Fri, Sat, Sun, Public Holidays
- Start date and End date where date can be fixed, none or an offset of +/- from today

**However more research needs to be done to understand** 
- **how best to present these choices to users**
- **what other common date validations exist?** we might also want to support these and may need to design implementation to be even more flexible if so

### Competitive research

Can include not just form managers but also related products like Google Cal. can look through use cases and requests mentioned in user research spreadsheet for inspiration and context as well.

- [prioritize first] Exclude choice of: Mon, Tue, Wed, Thu, Fri, Sat, Sun, Public Holidays
- Start Date and End Date
- Any other validations?

**Comment by tshuli** [comment]
Can I suggest that instead of excluding public holidays, we provide a textfield for them to state the dates that they want to exclude? Gives them more flexibility (e.g. they may close on eve of major public holidays like cny as well), and avoids the need to maintain / update a database of public holidays

**Comment by syan-syan** [comment]
> Can I suggest that instead of excluding public holidays, we provide a textfield for them to state the dates that they want to exclude? Gives them more flexibility (e.g. they may close on eve of major public holidays like cny as well), and avoids the need to maintain / update a database of public holidays

how do you envision the text field working - what do we do with the input?

**Comment by tshuli** [comment]
would be similar to dropdown options - each line is a date, and we then exclude these dates

**Comment by karrui** [comment]
@pearlyong @mantariksh @syan-syan thinking of assigning @siddarth2824 to this concurrently whilst he waits on reviews on his other internship project. i think i can assign sid to think of the feasibility of engineering each of the designs @prasanthkumaar envisioned.

**Comment by syan-syan** [comment]
@pearlyong can help to link the figma you and @prasanthkumaar worked on in here?
