### ISSUE TITLE
Mergify to integrate Snyk.io, and explicitly check success of each CI step

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#1749]
We are currently using _mergify_ to automatically merge dependency updates from _dependabot_.

According to [mergify docs](https://docs.mergify.io/conditions/#validating-all-status-checks), we should not be using _mergify_ with the condition `#check-failure=0`, because this evaluates to true as soon as the pull request is created and before any CI services report its status. Instead, we should be explicitly listing each CI step using the `check-success` condition.

We should also create a new rule to integrate Snyk.io to obtain security updates.

Implementer may wish to refer to [GoGovSG](https://github.com/opengovsg/GoGovSG/pull/1420) for reference.

**Comment by mantariksh** [comment]
`#check-failure=0` has already been removed, and we can rely on branch protections instead of listing each CI step, otherwise we'd have to keep updating the mergify config every time we add a CI step. see https://github.com/opengovsg/FormSG/pull/1737
