### ISSUE TITLE
Visiting archived form URL shows uninformative error message, wrong form ID

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#1759]
Visiting an archived form URL shows the following:

![Screenshot 2021-04-29 at 11 37 55 AM](https://user-images.githubusercontent.com/29480346/116499694-59a39c00-a8df-11eb-8b6b-18c5cf72fef5.png)

This has a couple of problems:
1. The "Gone" error message is uninformative. This is a regression because the error message used to be something like "This form has been deleted."
2. The target form ID is cut off, probably because of a bug in slicing the string.

**Comment by syan-syan** [comment]
todo: change copy to 'This form is no longer active' and 'Form ID: (correct form id)'

**Comment by aniruddha-adhikary** [comment]
<img width="889" alt="Screenshot 2021-07-07 at 1 31 57 AM" src="https://user-images.githubusercontent.com/932949/124643040-25da8900-dec3-11eb-9d48-455511e23d55.png">

This appears to be fixed.

**Comment by aniruddha-adhikary** [comment]
#2320 fixes it
