### ISSUE TITLE
Update data collation tool delimiter 

### ISSUE THREAD

**Issue by r00dgirl** [opengovsg/FormSG#18]
Table style fields on Email mode often need to be split to column after data collation into an Excel sheet. However we use a comma delimiter that makes this difficult. Excel 365 splits to column whether or not the comma delimiter is followed by a space.

![SnipImage](https://user-images.githubusercontent.com/55272802/88082540-78d50680-cbb4-11ea-93c0-cedc272aaa46.JPG)

Storage mode uses ; delimiter:

<img width="697" alt="Screenshot 2020-07-22 at 12 47 34 AM" src="https://user-images.githubusercontent.com/55272802/88082899-f3058b00-cbb4-11ea-939f-8f75eaf9c407.png">

To discuss: backwards compatibility

**Comment by tshuli** [comment]
Closing stale issue
