### ISSUE TITLE
LogicDto is typed incorrectly

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#1810]
In `src/types/form_logic.ts`, `LogicDto` is typed as

```
LogicDto = ConditionalPick<LeanDocument<ILogicSchema>, Primitive>
```

This was initially typed to be in line with `FormFieldDto`, but this is wrong because Logic contains nested objects which are not primitives, resulting in `LogicDto` only containing `_id` and `logicType`.

**Comment by seaerchin** [comment]
was actually looking at this and i have a fix - can just change to `ConditionalExcept<LeanDocument<ILogicSchema>, Function>`

**Comment by mantariksh** [comment]
as discussed, the fix mentioned above doesn't work because the logic schema contains a nested condition schema, which won't have its Mongoose properties removed
