### ISSUE TITLE
Pre-validate hooks not running

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#1814]
Due to the new usage of `findByIdAndUpdate`, certain pre-validate and pre-save hooks are not running as `findByIdAndUpdate` does not activate them. For example, the Form model has a check to ensure that the total form size does not exceed 10MB, but this check does not run when the Settings page is updated as the settings update uses `findByIdAndUpdate`. The Verification model also has a check for duplicate field IDs which is not run when Verification documents are updated.

The following fixes should be made to ensure that the functionality in the hooks is maintained:
1. For the Form model, the check for object size should be moved in to the Dropdown and Checkbox fields, which have a risk of becoming too large as the user is allowed to copy and paste multiple options into a textarea.
2. For the Form model, the checks for the admin and permissionList should be moved into the admin and permissionList keys.
3. For the Verification model, the check for duplicate field IDs should be moved into the `fields` key.
4. All other instances of `findByIdAndUpdate` and `findOneAndUpdate` should be checked to ensure that the models do not rely on Mongoose hooks to maintain the correct state.

**Comment by liangyuanruo** [comment]
Discussion
1. Use a heuristic e.g. max length to prevent users from uploading in the UI by disabling the "Save" button
2. Remove complicated bson size estimation
