### ISSUE TITLE
Comma in Sender name gets cut off in respondent inbox

### ISSUE THREAD

**Issue by jacksonOGP** [opengovsg/FormSG#1822]
When Sender name has a comma, for example
"Agency for Science, technology and Research"
The sender name seems to be be cut off and become
"technology and research" when it reach recipient's inbox.

**Steps to replicate issue**

1. go to any forms with email field and make sure confirmation is turned on
2. make sure sender name has a comma
3. Go to the form as respondent
4. Enter your work email
5. Look at the sender name at your inbox

**Comment by mantariksh** [comment]
Closed via #1782
