### ISSUE TITLE
Convert submissions.client.factory.js to TypeScript

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#1841]
This is a key client-side service that determines the performance and safety of many key features:
- Data format of submissions before encryption over HTTP
- Email submission over multipart FormData
- Retrieving the submission count
- Metadata retrieval for responses page
- Downloading individual submissions and decrypting them
- Downloading and decrypting attachments as zip files
- Performance sensitive bulk downloads and decryption

**Comment by karrui** [comment]
This file should be split up into a two different services too:

### SubmissionService
- Submit email mode form 
- Submit encrypt mode form

### FormResponsesService
- Retrieve submission count
- Retrieve encrypt mode responses list
- Retrieve individual response
- Download encrypt mode form responses
  - Without attachments
  - With attachments
  - Individual attachment

**Comment by karrui** [comment]
Closing in favour of #1873, #1874
