### ISSUE TITLE
Start page buttons have wonky html when preview cannot be seen 

### ISSUE THREAD

**Issue by seaerchin** [opengovsg/FormSG#1859]
## Problem
on prod, once the preview screen has been hidden due to (possibly) the developer console opening, the options for form logo are not selectable using the radio buttons. instead, only the top most (`default`) is selectable in a small area. Once this button is selected, then the rest of the buttons become selectable once again.

The recording below shows first the expected behaviour, the bug and then the workaround
![recording](https://user-images.githubusercontent.com/44049504/117758732-20f7b100-b255-11eb-9a01-390aa38e59f1.gif)

**Comment by syan-syan** [comment]
#wontfix since migrating frontend to react
