### ISSUE TITLE
The page seems outdated and your changes could not be saved

### ISSUE THREAD

**Issue by Reevefrombackgate** [opengovsg/FormSG#1890]
Hi guys,

I have encountered this error message when trying to amend the FormSG that I created.

The field that I was trying to edit is under "Thank you", which is at the bottom of the form.

Seeking your advice, please.

Reeve
![Capture](https://user-images.githubusercontent.com/84267320/118391656-057f1280-b668-11eb-86f8-5cad8d0959a2.PNG)

**Comment by mantariksh** [comment]
hi @Reevefrombackgate have you tried refreshing the page? Also could you fill in [this form](https://form.gov.sg/#!/5d6dd66ad6754c0012d7dc82) and provide us with your form link please?

**Comment by Reevefrombackgate** [comment]
Yes, i have refreshed many times. Also, tried deactivating and reactivating
but it didn't work. I have filled up the form, form link as follows:
https://form.gov.sg/5e65c2da8bfe490011205a72

Thank you.

**Comment by mantariksh** [comment]
hey @Reevefrombackgate this is indeed a bug, apologies for the inconvenience and thank you for highlighting it to us! we're in the midst of fixing it (should be fixed less than an hour from now), I'll ping you again when the fix is out.

**Comment by mantariksh** [comment]
@Reevefrombackgate this has been fixed via #1896, thanks again for highlighting it!

**Comment by mantariksh** [comment]
Closed via #1896
