### ISSUE TITLE
[MyInfo 0.] Move to MyInfo v3 with existing fields 

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#19]
**Why**
- V3 has a lot more MyInfo fields
- By July 2020 user-provided fields will no longer be pre-filled (this might affect our code)
- MyInfo claims v3 has better security posture

**To do**

- Switch to Person API
- Deprecate old MyInfo fields by changing them to regular fields. see epic for list.

[Epic here](https://docs.google.com/document/d/1xa8KI560ZzQUpcB12-sn9LIm5aXYq_qUTw4OFf1bzyw/edit#heading=h.iaid9do5b4rh) 

[MyInfo V3 Migration Guide.pdf](https://github.com/datagovsg/formsg/files/3834804/MyInfo.V3.Migration.Guide.pdf)

prior discussion: https://github.com/datagovsg/formsg/issues/1392

**Comment by liangyuanruo** [comment]
@syan-syan suggest deprioritising in favour of MyInfo v4 with PKCE, so that we don't rework this twice in six months?

**Comment by syan-syan** [comment]
> @syan-syan suggest deprioritising in favour of MyInfo v4 with PKCE, so that we don't rework this twice in six months?

100% on board with that. i havent edited these tickets to reflect latest developments
