### ISSUE TITLE
Submitting private storage mode form gives wrong error message

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#1914]
Submitting a private storage mode form shows a vague error message:

![Screenshot 2021-05-18 at 10 48 54 AM](https://user-images.githubusercontent.com/29480346/118582848-a683df80-b7c6-11eb-9e1f-6b91f5d7dadd.png)

To replicate:
1. Activate a storage mode form
2. Open the form in a separate tab
3. In the admin panel, make the form private
4. Try to submit the form in the separate tab

This happens because the frontend attempts to access `error.message`, whereas the message returned by the backend is actually in `error.data.message`, so `error.message` is `undefined` and the frontend defaults to a generic error message.

While solving this problem, we should consider the UX of the error message. In email mode, we currently show a generic error message: "This form has been taken down. For assistance, please contact the person who asked you to fill in this form.". However, in storage mode, we return the form's `inactiveMessage` as the error message. The form's `inactiveMessage` may be more specific to the form, but that is contingent on the form admin providing an informative message. Furthermore, the default `inactiveMessage` is quite vague: "If you think this is a mistake, please contact the agency that gave you the form link."

**Comment by karrui** [comment]
Related to #1873, will do them together
