### ISSUE TITLE
Verified field OTP waiting time check is susceptible to clock drift

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#1923]
Server logs contain some instances of "OTP requested before waiting time elapsed" errors. The client UI enforces that OTPs can only be requested every 30 seconds, so this is likely to be a bug.

A possible diagnosis is server clock drift. The servers enforce a 30-second waiting time between requesting new OTPs for verified fields. However, this may be susceptible to clock drift between servers, as follows:

1. Server A is 1 second ahead of Server B.
2. Client requests OTP at 9:00:00am (Server A time). Server A saves the OTP hash to the database, created at 9:00:00am.
3. Client waits for 30 seconds and requests another OTP at 9:00:30am (Server A time).
4. OTP request goes to Server B. Server B reads from the database that the hash was created at 9:00:00am. However, the current time on server B is 9:00:29, so Server B rejects the request as only 29 seconds have elapsed. 

Consider adding a few seconds (maybe 10% = 3 seconds) of tolerance when checking whether the OTP waiting time has elapsed.

**Comment by liangyuanruo** [comment]
@mantariksh Seems like a low effort issue, but also a micro-optimisation that is unlikely to impact anything.

**Comment by mantariksh** [comment]
@liangyuanruo @syan-syan can I double check that you intended to close this? it’s potentially a current problem in production, as I’ve seen “OTP requested before waiting time elapsed” errors in the logs

**Comment by liangyuanruo** [comment]
@mantariksh what is the proportion of requests that are facing this issue though? can we address this by simply setting e.g. 30s duration in the client, but 27s in the server?

**Comment by mantariksh** [comment]
@liangyuanruo yeah the proportion is tiny, less than 1%. and yup the user can tap on the button again, and yup this can be addressed by setting a slightly shorter duration on the server.

**Comment by liangyuanruo** [comment]
That's why I think this is not really worth addressing. At higher transaction volumes. Clock drift always occurs across devices, and unlike the webhooks issue, the problem does not result in a persistent state of rejected transactions. I think this problem was amplified only because we had a sufficiently high volume of transactions, but otherwise it is not an issue.
