### ISSUE TITLE
Enable stricter checks from the TypeScript compiler

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#1930]
This would improve type checking in the codebase by enabling flags available for [tsconfig](https://www.typescriptlang.org/tsconfig):

- noFallthroughCasesInSwitch
- noImplicitOverride
- noImplicitReturns
- noPropertyAccessFromIndexSignature
- noUncheckedIndexedAccess
- noUnusedLocals
- noUnusedParameters

**Comment by wanlingt** [comment]
FRM-1401
