### ISSUE TITLE
Canadian phone number validation error

### ISSUE THREAD

**Issue by yhrchan** [opengovsg/FormSG#1989]
Hi,

Seems like I can't get past the validation error message on the phone number field when I use Canada as the country as shown in the screenshot.

![2021-05-28](https://user-images.githubusercontent.com/3683552/120043691-a5725f80-bfc9-11eb-8d76-587235e93042.png)

Thanks!

**Comment by jacksonOGP** [comment]
Hello there! Could you share the form link that you're accessing? You may email it to us at formsg@tech.gov.sg. Thanks!
