### ISSUE TITLE
[2?] Remove customMin and customMax virtuals from number and text field schemas

### ISSUE THREAD

**Issue by tshuli** [opengovsg/FormSG#2039]
Remove customMin and customMax virtuals from number and text field schemas, which were put in to allow for backward compatibility after customMin and customMax were removed as part of #408

**Comment by justynoh** [comment]
In particular, the following need to be removed:

- Lines setting the virtuals (i.e. starting with `ValidationOptionsSchema.virtual('customMin').get(function (`) in the files `src/app/models/field/xxxField.ts` (where xxx is the relevant field type - text/number etc)
- The type generic in `src/types/field/utils/virtuals.ts`
