### ISSUE TITLE
Stream decrypted responses directly to disk via Service Workers

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#2052]
May be an opportunity to make decryption + downloading of storage mode responses much more efficient with the new APIs afforded to us by dropping IE11 support

**Comment by liangyuanruo** [comment]
@karrui What new APIs are you referring to?

**Comment by karrui** [comment]
@liangyuanruo stream directly to disk? progress bars, etc haha

**Comment by liangyuanruo** [comment]
good idea, i'll update the issue title
