### ISSUE TITLE
Allow Pre-filling Table Fields

### ISSUE THREAD

**Issue by aniruddha-adhikary** [opengovsg/FormSG#2074]
# Introduction

Pre-filling the table fields is not currently allowed. Only short text fields are allowed for pre-fills. If we could use an index-based approach to allow the pre-fills, that could potentially automate a lot of FormSG submissions out there.

## Example Use Case

Swabbing Requests: When submitting a report for COVID-19 Swabbing, agents performing the swab are required to submit a form with the information of one/many individuals. It is quite tedious to manually fill up the fields with PII. A pre-filled link could ease their task by pre-filling the PII and only requiring them to enter operational details. i.e., the lab sample ID.

# Technical Specifications

### Suffixed Index

`{field_id}_{index}`

Example: `?60b482d72004d70011555a14_0=Lim,60b482d72004d70011555a14_1=Adhikary`

#### The Goods
* The Format is explicitly defining indexes, there is a reduced chance for index ambiguity.

#### The Bads
* The underscored prefix might not appeal to be of good taste in serializing.

### Standard Query Parameter Array

`{field_id}[]` -> `60b482d72004d70011555a14[]=Lim,60b482d72004d70011555a14[]=Adhikary`

#### The Goods
* The format is well known in the web community, have been used for a long time for submitting arrays.

#### The Bads
* The order is implicitly guessed. It is not explicitly defined. Could be a cause for ambiguity

### The Indexed Query Parameter Array

`{field_id}[index]` -> `60b482d72004d70011555a14[0]=Lim,60b482d72004d70011555a14[1]=Adhikary`

#### The Goods
* A fairly better way to serialize compared to proposal 1.
* Provides explicit indexing.

#### The Bads
* It might be frowned upon by standards enthusiasts.

**Comment by syan-syan** [comment]
@aniruddha-adhikary tagging p4 for now as there does not seem to be many user requests for this, probably will tackle after our react migration (ending q3). please let us know though if there is active/urgent demand for this from the covid swab team for instance - can link us up as well.

**Comment by aniruddha-adhikary** [comment]
> @aniruddha-adhikary tagging p4 for now as there does not seem to be many user requests for this, probably will tackle after our react migration (ending q3). please let us know though if there is active/urgent demand for this from the covid swab team for instance - can link us up as well.

The agency we had been working with changed its preferred method of data submission away from FormSG. Thus, also it is no longer important. Can remain as P4!
