### ISSUE TITLE
[TBD] Prefill enhancements

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#2082]
Customs would like to minimise contact between M’sian drivers and custom officers, by using OCR technology to scan passports & auto-populate additional form fields.

#### Specifications

**Validity**
- Prefill value must be checked for validity on the form. For example, dropdown fields should only accept valid values in the _fieldOptions_; similarly Yes/No fields should only accept one of the two allowed values.

**Logic**
- The prefill value must trigger logic calculations that subsequently allow more fields to be prefilled

**Comment by syan-syan** [comment]
prefill hidden behind logic is alredy supported
not clear that they need yes/no prefill
sorting this out with shuli & customs

**Comment by syan-syan** [comment]
closing for now as covid team is still triaging
