### ISSUE TITLE
Should only store `userId` in sessions instead of the entire user object

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#212]
As per title, should we have a single source of truth for the state of the user?

It currently does not matter much since we have no real features to update the user object once it is created (no email changes, no password changes, etc), and thus we can use `req.session.user` without any thought.

However, with the ability to update the user document now (emergency contact number feature #13), the source of truth may diverge.

Thus, suggest just storing the userId in session and retrieving them whenever needed.

**Comment by liangyuanruo** [comment]
Agree, this could be a bug waiting to occur when we automate ops. @syan-syan FYI
