### ISSUE TITLE
Address environment variable limit of 4096 bytes

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#2126]
Elastic Beanstalk deployments have a [limit of 4,096 bytes](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environments-cfg-softwaresettings.html#environments-cfg-softwaresettings-console) for environment variables, which is likely to block SGID integration.

One possible way to solve this issue is to use the [AWS Systems Manager Parameter Store](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html) to save the environment variables instead, and inject them into the EC2 environment during EB initialisation via `.ebextensions` configuration files. This [article](https://www.honeybadger.io/blog/configuration-with-ssm-parameter-store/) hints at the shell command that can do this.

The implementer should also update relevant internal documentation once the integration is complete.

**Comment by LoneRifle** [comment]
Relevant StackOverflow post to use parameter store in EB - https://stackoverflow.com/questions/60777164/get-value-from-aws-systems-manager-parameter-store-during-elastic-beanstalk-depl
