### ISSUE TITLE
Allow transfer ownership on email mode forms

### ISSUE THREAD

**Issue by arshadali172** [opengovsg/FormSG#214]
You can give _EDIT_, _READ_ and _OWNER_ privileges to collaborators on storage mode forms with this new [PR](https://github.com/opengovsg/FormSG/pull/111).

However, you can only give _EDIT_ access to collaborators on email mode forms. We should also allow _READ_ and _OWNER_ privileges to be given to collaborators of email mode forms.

**Comment by arshadali172** [comment]
@leonardloo @syan-syan thoughts on adding _READ_ access to collaborators to email mode forms since there is no data being stored by us?

I would argue, that we should allow _EDIT_, _READ_ and _OWNER_ consistently for both email and storage mode forms.  That is easier engineering wise as we don't have to code up specific checks for email or storage mode forms.

And that _READ_ access is still valuable for email mode forms as such collaborators can read the feedback stored by us.

**Comment by arshadali172** [comment]
@syan-syan update: we decided to have the same 3 options on the email and encrypt form pages (i.e. EDIT, READ, OWNER)

**Comment by syan-syan** [comment]
@arshadali172 also increase the height of the collaborator list? right now i can only see 2 collaborators
