### ISSUE TITLE
[1?] Remove feature manager endpoints

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#2147]
Since the feature manager is being removed as part of #1842, the `/frontend/features` and `/api/v3/client/features` endpoints should be deleted when the client no longer calls them.

**Comment by mantariksh** [comment]
28/6 update - still a lot of clients calling this endpoint, 100+ in the last hour

**Comment by mantariksh** [comment]
29/7/21 update - still 263 API calls in the past day

**Comment by mantariksh** [comment]
30/6/22 - no calls to this endpoint in the past 3 days, can delete

**Comment by foochifa** [comment]
Removed in #6344
