### ISSUE TITLE
Dropdown input height not adapting to long text

### ISSUE THREAD

**Issue by bubblybunii** [opengovsg/FormSG#2165]
**Current behavior**
![Dropdown fixed height issue](https://user-images.githubusercontent.com/6670095/121981638-a58f9f00-cdc0-11eb-99b1-e3977bcad979.jpg)
- Dropdown height of id `#dropdown-input` is fixed and not adapting to long text as seen in screenshot
- Text got cut off as a result, user need to click on dropdown in order to read the full text 
- Form link https://form.gov.sg/#!/60be05b95d28890012fa6323

**Expected behavior**
- Dropdown box height should adapt to the text height that is entered
- Line height for text can be increase for better readability for `class="ng-binding ng-scope"`

**Comment by syan-syan** [comment]
@f1zaz @pearlyong weigh in on desired behaviour? I also opened an issue for this previously as I thought it was concerning, maybe the visible lines can be capped at 3

**Comment by mantariksh** [comment]
still an issue in React, we can consider max visible lines

**Comment by pearlyong** [comment]
ideal behaviour:
- When collapsed, show one line only
- When expanded, show the entire option in list (not in the input)
- can see [notion doc](https://www.notion.so/opengov/Dropdown-height-6ed34e1351eb4897b5b1ec621b376fc8) for comparisons

**Comment by foochifa** [comment]
This is done
