### ISSUE TITLE
Update MyInfo Registered Address icon

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#2166]
The icons for UEN and MyInfo registered address fields are identical under the Build tab. The icon for "Registered Address" should be changed to `bx-home-circle` as per @pearlyong's recommendation.

<img width="738" alt="Screenshot 2021-06-15 at 8 59 05 AM" src="https://user-images.githubusercontent.com/29480346/121986769-babcfb80-cdc9-11eb-9b87-1afb7bd07664.png">

**Comment by timotheeg** [comment]
Addressed in #4280
