### ISSUE TITLE
Refactor client-side decryption code to use a threadpool pattern for maintainability

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#2170]
The existing client-side storage mode decryption code in the `downloadEncryptedResponses` function is based on message-passing via e.g. Worker `postMessage` and event emitters e.g. `worker.onerror`, making the code difficult to read, maintain, extend, or refactor.

It would help in the long term to refactor towards a [thread pool pattern](https://en.wikipedia.org/wiki/Thread_pool) instead.

Some potential libraries to leverage include:
- [josdejong/workerpool](https://github.com/josdejong/workerpool)
- [parallel-js/parallel.js](https://github.com/parallel-js/parallel.js)
- [padolsey/operative](https://github.com/padolsey/operative)
- [catiline](https://github.com/calvinmetcalf/catiline)

**Comment by liangyuanruo** [comment]
Discussion with @chowyiyin - will be proceeding with the _operative_ library due to ease of porting existing code, where the FormSG SDK has to be initialised prior to decryption.

**Comment by chowyiyin** [comment]
The libraries that were explored include:

[josdejong/workerpool](https://github.com/josdejong/workerpool)
This library implements the threadpool pattern and also abstracts the web workers' message passing, which is suitable for our use case
**Challenges:**
* Unsafe `eval` used, which violates the Content Security Policy (CSP)

[parallel-js/parallel.js](https://github.com/parallel-js/parallel.js)
This library does not implement the threadpool pattern but helps to abstract the web workers’ message passing
**Challenges:**
* In the current implementation, all web workers are initialised with the formsg’s sdk package but may not be possible with this library’s API
 * Implications: may have to result to initialising it before each decryption step or passing it through `env` option, which passes the object to workers each time as well
* Requires all data to be passed into the constructor of `Parallel`
 * Implications: we have to download all the data before decryption, although should not be a significant problem as ciphertexts not likely to take up too much memory
* Note: not entirely sure if this library violates CSP

[padolsey/operative](https://github.com/padolsey/operative)
This library does not implement the threadpool pattern but helps to abstract the web workers’ message passing
**Challenges:**
* Unsafe operation of creating blob from input script, which violates the CSP

[andywer](https://github.com/andywer/threads.js)
This library implements the threadpool pattern and also abstracts the web workers' message passing, which is suitable for our use case
**Challenges:**
* Requires changes to “module” and “moduleResolution” in ts-loader-config, which could be risky

**Comment by foochifa** [comment]
Will track internally
