### ISSUE TITLE
Remove deprecated form.permissionsList.read key

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#2177]
Old forms (created before March 2020) has a form.permissionsList.read key, but Joi validation is blocking this due to new schema shape. This deprecated key should be removed from the collection so Joi validation can be made stricter (again)

**Comment by syan-syan** [comment]
@karrui can close if no outstanding tasks?

**Comment by karrui** [comment]
we need to revert the loosening validation hotfix first before this can be closed. i will open a PR for that
