### ISSUE TITLE
Enforce (runtime?) type-checking in frontend submissions pipeline

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#2209]
Storage mode submissions saved to the database cannot be updated due to end-to-end encryption. This means that submissions saved in the wrong format can be difficult or impossible to salvage.

This presents a high risk to the frontend React migration, since the new frontend submissions pipeline will not be battle-tested nearly as well as the present AngularJS pipeline. Any mistakes made in the submissions code may cause irreversible corruption to the Submissions collection.

One way to reduce this risk is to create a type-checked frontend service for response encryption which enforces the shape of its arguments. Using this service with the present AngularJS code in production and subsequently reusing it with React can assure us that it the encryption is being performed correctly in the new frontend.

It is important to note that the type-checking in this service cannot merely be done by the TypeScript compiler, since most of the frontend is in JavaScript, so TypeScript does not guarantee that the types passed in to the service are correct at runtime. In order to be confident that the type signature of the service is correct, the type enforcement must be done via JavaScript code, e.g. the `in` keyword.

**Comment by liangyuanruo** [comment]
> It is important to note that the type-checking in this service cannot merely be done by the TypeScript compiler, since most of the frontend is in JavaScript, so TypeScript does not guarantee that the types passed in to the service are correct at runtime. The type enforcement must be done via JavaScript code, e.g. the in keyword.

Good point - I think we can use a type guard!
