### ISSUE TITLE
Allow semi-colon delimiter for email recipient

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#223]
The current frontend validation only supports comma-delimited email addresses.
![image](https://user-images.githubusercontent.com/5690550/91436468-c53df100-e89a-11ea-88ee-55ffdde3e252.png)

Update the application such that semi-colon delimiters are also allowed, so as to assist copy-pasting directly from an Outlook email client.

**Comment by syan-syan** [comment]
@karrui can we investigate what the longest length email list is before doing this? perhaps we are better off cleanly sticking to commas?

**Comment by karrui** [comment]
Will probably convert all semicolons to commas then as the first step. So when the user types in `;` it will automatically get converted to `,`. Allows for copy paste but also a consistent format. But probably will only pick up if I have bandwidth
