### ISSUE TITLE
Address tech debt of email submission recipients schema

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#225]
Related to https://github.com/opengovsg/FormSG/pull/222

Today, there is technical debt in the forms schema, where email recipients are saved to the database. We should migrate the existing `emails` key from this structure:

```javascript
emails: ['a@mail.gov.sg; b@mail.gov.sg, c@mail.gov.sg']
```

to a new `emailRecipients` array such as this:

```javascript
emailRecipients: ['a@mail.gov.sg', 'b@mail.gov.sg', 'c@mail.gov.sg']
```

where each element of the array is a fully-formed, valid email address

TODOs:
- [ ] Write database migration script to new schema
- [ ] API backwards compatibility for form creation 
- [ ] API compatibility when updating/deleting
- [ ] Email submission

**Comment by karrui** [comment]
Also related to https://github.com/opengovsg/FormSG/pull/326

**Comment by arshadali172** [comment]
Postponed for now because the submissions collection is too large for queries to be run efficiently. Running through the email submissions collection to check emails against a regex can take a good hour or more

**Comment by liangyuanruo** [comment]
@arshadali172 can we close this issue?
