### ISSUE TITLE
Error message on sign-in page is broken

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#2250]
Credit to @waynetee for finding this.

To replicate, request for OTP with a non-valid email domain (e.g. "open.gov.rg").

<img width="627" alt="Screenshot 2021-06-24 at 6 11 08 PM" src="https://user-images.githubusercontent.com/29480346/123245647-9c68a580-d517-11eb-9d62-361add98e525.png">

**Comment by aniruddha-adhikary** [comment]
#2321 fixes this!
