### ISSUE TITLE
Supply Repo Token when reporting test coverage to coveralls.io

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#228]
Duplicate service job IDs from Travis during job restarts cannot pass CI due to coveralls.io error. The existing workaround is to manually trigger a new job instead of restarting an existing one.

```bash
Bad response: 422 {"message":"service_job_id (378233677) must be unique for Travis Jobs not supplying a Coveralls Repo Token","error":true}
```

Introduce a Coveralls repo token so that jobs can be easily restarted.

**Comment by arshadali172** [comment]
Tried 2 possible solutions:

1. Specifying `COVERALLS_REPO_TOKEN` as suggested [here](https://github.com/lemurheavy/coveralls-public/issues/632#issuecomment-148815369)
1. Moving the coveralls script to `after_success` as suggested [here](https://github.com/operator-framework/operator-sdk/issues/3153)

**Comment by tshuli** [comment]
Stale
