### ISSUE TITLE
Tech design: testing coverage

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#231]
Start new doc outlining 

- [ ] automated test coverage: unit, integration, e2e
- [ ] manual verification protocol
- [ ] external services 

Helium reference doc https://docs.google.com/document/d/1gIyj3dZLp7ypR0ngc5-b3-1OOQCDAdYyrqeuBFsL0dY/edit#

**Comment by syan-syan** [comment]
duplicated in other repo

**Comment by karrui** [comment]
What other repo? :O
