### ISSUE TITLE
The CHANGELOG is flooded with too many dependabot commits

### ISSUE THREAD

**Issue by aniruddha-adhikary** [opengovsg/FormSG#2346]
## Problem

The CHANGELOG.md file is currently too clogged up with dependabot commits. Making it quite tough to find the human commits.

## Proposed Solution

We filter out the bot commits.

## Related

https://github.com/opengovsg/checkfirst/issues/550

**Comment by aniruddha-adhikary** [comment]
Fixed by #2349

**Comment by liangyuanruo** [comment]
Consensus between @timotheeg and I are that the changelog should capture all changes that could potentially alter production behavior, including automated commits.

**Comment by aniruddha-adhikary** [comment]
> Consensus between @timotheeg and I are that the changelog should capture all changes that could potentially alter production behavior, including automated commits.

Agreed. Especially with the node environment and countless dependencies, keeping track is necessary. Appreciate the feedback :D
