### ISSUE TITLE
betaFlag schema is an empty object in the user model

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#2351]
betaFlags were recently re-added into the codebase via #1986, but the schema was left untouched.

This may cause a user's betaFlags key-values to be reset if the user updates their user document, which can be triggered when the user updates their emergency contact number.

Low impact for now as users using the beta flags currently need to be manually onboarded, should be fixed by the next release.

The shape of the schema should be
```ts
betaFlags: {
  sgid: Boolean
}
```

**Comment by mantariksh** [comment]
Closed via #2373
