### ISSUE TITLE
CD pipeline deploys to production even when Docker build fails

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#2393]
The following screenshot is from the deploy stage in `release` branch. It shows that there was an `npm` error while building the Docker container, but the build still exited with code 0, and Travis still triggered a deployment on Elastic Beanstalk. This resulted in a "Requested image not found" error during the Elastic Beanstalk deployment, since the relevant container was never pushed to AWS ECR.

This does not impact production since Elastic Beanstalk will simply abort the deployment, but can still result in unexpected deploy failures.

![Screenshot 2021-07-14 at 11 58 11 AM](https://user-images.githubusercontent.com/29480346/125558849-0181c9f4-3fb2-4641-b8f2-bf00f21538f0.png)

**Comment by karrui** [comment]
Travis doesn't abort builds if error happens in `before_deploy` it seems, no documentation on that anywhere.

**Comment by karrui** [comment]
Don't think this is high priority tbh, requires a full rehaul of Travis from what it seems. Will open for discussion

**Comment by syan-syan** [comment]
do with #2526

**Comment by timotheeg** [comment]
Now that we are deploying with github actions, we have verified that deployment **does** stop if the docker build fails.

And thanks to that, we have now removed the double build from the deployment flow, which saves quite a bit of time 🎉

I'm closing this issue.
