### ISSUE TITLE
[1?] Deprecate ifValueType from form logic

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#2395]
The form logic condition schema has a field called `ifValueType` which is entirely unused in the backend and the logic module. Its only use is in rendering logic in the frontend. This key should be deprecated from all logic units in the database and the frontend should stop sending it in API requests to save and update logic.

**Comment by foochifa** [comment]
HMMMM this still exists in our `joiLogicBody` and `form_logic` schema 😅

Will track internally
