### ISSUE TITLE
[MyInfo 1.] Rework MyInfo flow

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#24]
Fka https://github.com/datagovsg/formsg/issues/2112

Discussion https://docs.google.com/document/d/1ccgdAHuyiJqyE_Ivrw_89bmowSIFrkx7wFHSoIAcvIg/edit#heading=h.uzyh5pif9vqm

Blocked by #19

**Comment by liangyuanruo** [comment]
Outdated from PKCE discussions
