### ISSUE TITLE
Unexpected scroll to bottom when clicking through storage mode responses

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#241]
![unexpected-scroll](https://user-images.githubusercontent.com/29480346/91788058-d8a3e000-ec3d-11ea-8670-acc2b62d82a5.gif)

**Comment by karrui** [comment]
This is not unexpected. This is intended behavior, it will scroll to the top of the respondent submission. It only seems like scrolling to bottom because your submission is short

**Comment by mantariksh** [comment]
oh chey

**Comment by mantariksh** [comment]
not sure if it's a good idea given that my intuition was to fight against it lol but ok

**Comment by karrui** [comment]
Yea, but on forms with a larger response, you can imagine how tiresome it would be to scroll up if you are already scrolled down after looking at the responses. But ya, we can probably calculate the height and etc etc, but that's probably for in the future. Can keep this issue to track it if we want
