### ISSUE TITLE
Unhelpful error message on OTP validation failure

### ISSUE THREAD

**Issue by seaerchin** [opengovsg/FormSG#2455]
## Problem
FormSG uses a OTP to log in. This OTP can only be comprised of numbers and should be 6 digit long. Although the frontend prevents characters from being inputted, this does **not** prevent copy-pasting errors. Hence, a user can paste an erroneous otp into the `input` and request to sign in. 

This results in the `celebrate` validation failing (as it should be number and 6 digits only) and the error is shown in the info box, which is extremely jarring and unhelpful to the user. 

## Steps to reproduce
1. Attempt to sign into form
2. at the otp page, paste any string containing alphabets (eg: `password`)
3. click sign in

## Suggested Fix 
Set default message on celebrate

## Screenshots 
![Screenshot 2021-07-28 at 2 58 35 PM](https://user-images.githubusercontent.com/44049504/127278191-e1cc4f69-ddf0-492d-9ced-62b7ef0b548d.png)

**Comment by timotheeg** [comment]
One more thing to investigate: why did the client side validation not pick up that the input content is not compatible with the field type and block sending a request at all.

**Comment by seaerchin** [comment]
> One more thing to investigate: why did the client side validation not pick up that the input content is not compatible with the field type and block sending a request at all.

i think this is because the `manageOtp` method (in `authentication.client.controller`) works via checking on keydown. this means that we don't disallow copy-pasting (cos they can copy-paste the valid otp)!
