### ISSUE TITLE
Fix breaking change on Express Session type definition

### ISSUE THREAD

**Issue by timotheeg** [opengovsg/FormSG#2464]
The package [`@types/express-session`](https://www.npmjs.com/package/@types/express-session) introduced a breaking change between `1.17.0` and `1.17.1` when it cleaned up its type definition. See discussion [here](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/d1259ee31e6b17c31a5a86e27a0d12f3ec7c5a19#r44080605).

Although our `package.json` declaration is `^1.17.0` indicates we should automatically upgrade when new updates are made available (and that would then break our builds), we have been protected from typescript compilation errors thanks to the version being locked in `package-lock.json`.

This is still a problem waiting to happen, where someone wishing to do  package-lock update will see unexpected breakages.

TODO:
1. Upgrade `@types/express-session` to latest
2. Fix broken types

**Comment by karrui** [comment]
Closed by #2463

**Comment by timotheeg** [comment]
Thanks @karrui , I forgot I had opened this 😓
