### ISSUE TITLE
Remove hardcoding of esrvcId regex

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#2471]
It will break whenever the SPCP team updates their esrvcId constrains, and will probably fail to notify us, causing us to have to update our validation again (see #2470).

We should remove the hardcoding of this regex. It was first attempted to remove the validation entirely in #2467, but our tests found that Corppass sign in will break entirely, showing a blank page when an esrvcId with whitespace (e.g. 'some invalid esrvcid') was given as the form's esrvcId.

Thus, we should concretize what is an is not an esrvcId with the SPCP team.

Long term suggestion:
Remove all character validation except for whitespace, so all esrvcIds can work and corppass won't break and rely on our validation check when the form is activated.

**Comment by syan-syan** [comment]
to remove regex validation entirely

**Comment by karrui** [comment]
> to remove regex validation entirely as it does not provide much benefit but could potentially block onboarding of new users, also dependency on spcp team. to do after react migration

I've already removed most validation in a separate PR, the new validation only allows for whitespace (because corppass breaks on any esrvcId with whitespaces...)

Forgot there was this duplicate issue.

Closed by #2521
