### ISSUE TITLE
Sentry for React migration

### ISSUE THREAD

**Issue by timotheeg** [opengovsg/FormSG#2515]
1. During release, sentry issues an error "project not found".
2. Sentry could allow us to be notified of unexpected frontend errors, but at the moment the signal-to-noise ration is too low to be useful.

**Comment by syan-syan** [comment]
to be done before releasing to users

**Comment by timotheeg** [comment]
Deliverable:
- Make sure sentry is added to the app
- Load whatever sentry-react connector is needed and do the needful for integration

Verify frontend errors are captured in sentry

**Comment by timotheeg** [comment]
Here is a scenario where we can expect sentry integration to help:

> During the last release of 5.22, we were monitoring submission failures in Google Analytics.
> 
> The number did not spike, so we did not suspect the build was broken, but we did see some occasional submission failures, and decided to investigate just in case.
> 
> It is not straightforward at all to identify the cause a submission failure. We resorted to making a copy of the form, and doing a manual submission, just to verify the form structure, fields, logic, and validation were OK, but this is time consuming.
> 
> TODO: find a way to identify error cause (error codes? stack traces? messages?) faster. Sentry could be a candidate for this.

**Comment by karrui** [comment]
We are probably going with Datadog over Sentry since they now have RUM, and that is tracked in #3645
