### ISSUE TITLE
Investigate possible deployment automation

### ISSUE THREAD

**Issue by timotheeg** [opengovsg/FormSG#2517]
The deployment process has many manual steps, to reduce the risk of human error, we should look at introducing automation as much possible. 

For e.g.
* Use script / cli tools do to the backporting of versions branches int develop and master branches
* Call cache clearing APIs on Cloudflare when build is deployed

Bottom line: anything that require a human interaction or intervention is susceptible to human error and should be reduced. Additionally, doing manual repetitive tasks for every release is just not the best use of engineer's time.

**Comment by syan-syan** [comment]
This issue is for relooking the entire deployment process. we can pursue this after react as an improvement to dev practice
