### ISSUE TITLE
Replace selectize with a better supported package

### ISSUE THREAD

**Issue by timotheeg** [opengovsg/FormSG#2559]
## Context

Form uses [Selectize](https://www.npmjs.com/package/selectize), which was last released 3 years ago.

Selectize has a low usage, and uses packages which are themselves unmaintained, into which vulnerabilities have been reported (e.g. [sifter](https://www.npmjs.com/package/sifter) > [optimist](https://www.npmjs.com/package/optimist) > [minimist](https://www.npmjs.com/package/minimist)). And it is clear that Sifter is abandonware, see [this PR and thread](https://github.com/brianreavis/sifter.js/pull/63) for details.

## TODO

We should remove our dependency on unmaintained software, either by selecting something that is more actively maintained with a larger user base, or by owning the module ourselves.

## Note:
This may not be urgent, and selectize itself may disappear with our React upgrade? (not sure?)

**Comment by karrui** [comment]
Yes, this will disappear with the React migration :P

**Comment by timotheeg** [comment]
Yay! Then I guess I'll just close this issue for now. Thanks @karrui 😄

**Comment by timotheeg** [comment]
Closing since issue will auto resolve with react migration.

**Comment by risadams** [comment]
Not to bump an old closed issue, but I found myself here while treading through sifter issues.
Selectize is once again being maintained, and the newer version can be found at @selectize/selectize
