### ISSUE TITLE
Migrate FormSG from Elastic BeanStalk AL1 to AL2

### ISSUE THREAD

**Issue by timotheeg** [opengovsg/FormSG#2564]
As follow up to https://github.com/opengovsg/FormSG/issues/2516, we need to migrate Form from Elastic BeanStalk AL1 to AL2.

References as follow:
* [Elastic Beanstalk Amazon Linux AMI platforms are deprecated](https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2021-07-08-linux.html)
* [Blue/Green Deployment](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.CNAMESwap.html)
* [Migrate AL1 environment to AL2](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.migration-al.html)

TODO: Prepare a new Elastic BeanStalk environment and perform a cname swap for transparent migration of traffic to the new platform.

**Comment by syan-syan** [comment]
supported until mid 2022

**Comment by karrui** [comment]
Done
