### ISSUE TITLE
Checkbox preview is broken

### ISSUE THREAD

**Issue by timotheeg** [opengovsg/FormSG#2577]
Selecting option 2 auto select "other" and shows the text input.

**Comment by timotheeg** [comment]
Some further investigation: the preview is not always broken. It is broken when a new option is added. The last option will then additionally select the "other" option (which is the real last option).

Note that saving the checkbox entry and opening it up again works.

But adding yet another option thereafter exhibits the same issue of double selection.

**Comment by mantariksh** [comment]
Closing because this is an AngularJS issue
