### ISSUE TITLE
Document how end-to-end encryption of attachments work

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#2599]
Need help to figure out where are the documentation gaps in the codebase for the aforementioned feature. e.g. what exactly is stored in the database vs S3 bucket, how filenames are generated, is file metadata stored in plaintext or ciphertext etc.

This will also help the team have greater clarity on how the feature works and whether it'll be possible to whitelist files by file extension.

**Comment by frankchn** [comment]
See https://docs.google.com/document/d/11UYYraaGQhUZrtmyUhpPrCs74iZM0OgWUV8lTIes3x0/edit?usp=sharing for a rough document on the workflows
