### ISSUE TITLE
502 and empty response errors in Sentry

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#263]
`/transaction` and `/frontend/features` endpoints are returning 502 as well as empty errors, resulting in tens of thousands of Sentry events.

A couple of representative examples:
![image](https://user-images.githubusercontent.com/29480346/91968142-c95c8980-ed46-11ea-9d34-36cb418ff7aa.png)

![image](https://user-images.githubusercontent.com/29480346/91968146-cbbee380-ed46-11ea-95f0-676afb8e6511.png)

**Comment by liangyuanruo** [comment]
Not an issue
