### ISSUE TITLE
Vaccination Cert for Diplomatic ID (below 15 years old) and Training Employment Pass Holders / individuals who do not qualify for Singpass

### ISSUE THREAD

**Issue by jasminembassy** [opengovsg/FormSG#2693]
**Is your feature request related to a problem? Please describe.**
We are having issues with retrieving the Notarised Certs for the Covid 19 vaccination. The individuals in this case are not eligible for Singpass. As such, they are unable to acquire their notarised certs. is there a workaround for this? I have contacted all, if not most agencies involved and have not gotten a solution to this. 

**Describe the solution you'd like**
Either manually retrieve the cert from back end and issue the certs / give vaccinated individuals who do not have Singpass a login for notarise.gov.sg

You may reach me at jasmin.embassy@gmail.com for further info with regards to this issue.

**Comment by syan-syan** [comment]
@jasminembassy I've routed your request internally to MOH but as this is not related to FormSG, i'll be closing it on this repo
