### ISSUE TITLE
Investigate and fix performance issues with pagination on submission ID search

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#276]
Blocks #174 

# Problem

In the proposed #174 implementation to allow form admins to search for a submission by its reference ID, the database needs to perform expensive scans to paginate to serve the first page (1) on load, and (2) each time the search box is cleared. The second scan is likely to be wasted work on the database's part as the user often immediately follows up by searching with a new submission ID.

![image](https://user-images.githubusercontent.com/5690550/92198435-f758df80-eea6-11ea-91fa-f0ca5307f957.png)

MongoDB is known for its inability to serve paginated queries efficiently (see [here](https://stackoverflow.com/questions/7228169/slow-pagination-over-tons-of-records-in-mongodb) and [here](https://www.codementor.io/@arpitbhayani/fast-and-efficient-pagination-in-mongodb-9095flbqr)) despite relevant indexes being created on the Submissions collection. This is also the root cause of CPU saturation on secondaries leading to service degradation on Aug 13.

**Chart showing CPU saturation on Mongo secondaries**
![image](https://user-images.githubusercontent.com/5690550/92101944-718a5500-ee10-11ea-99dc-86ef40779c43.png)

# Potential Approaches
(in order of difficulty)

1. (database) The existing database query is an aggregation which although complex, is assumed to be as performant as it can be given that relevant indexes are created. Investigate and confirm this using MongoDB's `explain()` operation.

2. (design) Use UI/UX to reduce the number of wasted hits to the database. For instance, instead of automatically firing off a query in the search debounce, introduce buttons that require explicit user interaction such as "search" and "clear" so that the database never does unnecessary work.

3. (design + engineering) Change pagination behavior to rely on the _natural ordering_ (which approximates the temporal ordering) of the documents based on their database `ObjectID`, as suggested by [this](https://www.codementor.io/@arpitbhayani/fast-and-efficient-pagination-in-mongodb-9095flbqr#approach-2-using-id-and-limit) post. This means that users can no longer "jump" to a specific page, but only visit pages immediately adjacent to the current page they are on. This should resolve performance issues, but may possibly lead to poorer UX if the earliest submissions are served first instead of the latest submissions, which are more likely to be relevant to the user.

**Comment by LoneRifle** [comment]
Can I add...

4. (design) Investigate how the search box is actually used. If general searches are minimal (and presumably they should be since responses are encrypted at rest and only can be searched once decrypted client-side) and the user is using it to jump between submission IDs (lookup id, clear, lookup id, etc), possibly replace the search box with a Jump to ID button

**Comment by frankchn** [comment]
@LoneRifle They are only using it to jump to particular submission IDs since it is technically a filter by `ObjectId` right now. That said, the current view responses page doesn't quite support a direct jump so there has to be some rearchitecting involved.

@liangyuanruo I think the best short-term solution is to just have a Filter and a Reset button and if people are just jumping to many IDs, then will just filter repeatedly and not need to Reset, alleviating the pagination issue.

**Comment by pearlyong** [comment]
Design for Search Submission ID here, using the same Search+Reset design pattern as Examples and Billing.
https://app.zeplin.io/project/5b29ffde48eaaf6318d01b05/dashboard?seid=5f2b71d865bd2a2798438461

**Comment by syan-syan** [comment]
> 3. (design + engineering) Change pagination behavior to rely on the _natural ordering_ (which approximates the temporal ordering) of the documents based on their database `ObjectID`, as suggested by [this](https://www.codementor.io/@arpitbhayani/fast-and-efficient-pagination-in-mongodb-9095flbqr#approach-2-using-id-and-limit) post. This means that users can no longer "jump" to a specific page, but only visit pages immediately adjacent to the current page they are on. This should resolve performance issues, but may possibly lead to poorer UX if the earliest submissions are served first instead of the latest submissions, which are more likely to be relevant to the user.

worth considering for v3 that it is unlikely [in general](https://dzone.com/articles/why-most-programmers-get-pagination-wrong) and also in our use case that users will want to jump to a specific page. 

also worth doing some user research on how admins are using the Data tab and if leaving admins to rely on excel for most of the filtering and visualisation is sufficient. personally the only Data tab requests i've seen is that they would like to be able to see and filter by response content - but nothing that cant be done via excel.

@pearlyong

**Comment by syan-syan** [comment]
downgrading to p4 since Filter & Reset seems to solve the issue for now, can reconsider optimising in future
