### ISSUE TITLE
Investigate quicker staging releases

### ISSUE THREAD

**Issue by timotheeg** [opengovsg/FormSG#2766]
It takes nearly 15mins to deploy to staging. This is quite slow, and forces engineer to context switch has they push their build to test it. If we could bring down pushing to staging to below 5mins, it would be fantastic.

Things to investigate:
* Unify on github actions, ditch travis
* Check where the time is being spent, is it building the docker image, spinning up new EB instances, where do we have room for improvements?

**Comment by foochifa** [comment]
Will track internally!
