### ISSUE TITLE
Investigate 403s 

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#2786]

**Comment by tshuli** [comment]
110 403s for the last 30 days (14 Aug to 12 Sep). These are 110 unique 'sessions' (A session is the period time a user is actively engaged with your website, app, etc.) so does not double count if user clicks twice on the same form

**Comment by karrui** [comment]
I don't think this is happening anymore, we only have ~150 `403`s in the past week. 

edit: seemed to have more than what @tshuli found, i forgot the original context lol
