### ISSUE TITLE
Link to OGP toolset!

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#2816]
New navbar link on our landing page 'Gov Apps' with dropdown menu to our other apps (use our component currently on admin user link) 

Order of navbar links from left to right: Gov Apps, GitHub, User Guide

![Screenshot 2021-09-16 at 5 35 06 AM](https://user-images.githubusercontent.com/55272802/133512884-78735d6d-0377-4c2e-9919-9e0ac303e900.png)

Menu items link to:
short links https://go.gov.sg/
mass messaging https://go.gov.sg/postmangovsg
eligibility checker https://go.gov.sg/checkfirstgovsg
voucher distribution https://go.gov.sg/redeemgovsg
website builder https://go.gov.sg/isomergovsg
payments https://go.gov.sg/pay
citizen identity https://go.gov.sg/idgovsg

**Comment by tohhengxing** [comment]
Hi, I can do this, can I be assigned this task? @syan-syan

**Comment by mantariksh** [comment]
hey @tohhengxing , welcome to the repo! maybe you can drop me an email at antariksh@open.gov.sg so we can link up? thanks!

**Comment by tohhengxing** [comment]
> hey @tohhengxing , welcome to the repo! maybe you can drop me an email at [antariksh@open.gov.sg](mailto:antariksh@open.gov.sg) so we can link up? thanks!

Hi i have emailed you!

**Comment by tohhengxing** [comment]
hi i finally got around to working on this just this night. Is this acceptable? (not exactly sure what admin user link meant but I searched the codebase and i assume admin user refers to just a User who is using the app.)

![image](https://user-images.githubusercontent.com/102740235/176252458-3bab12e3-5fdf-480a-8fcd-b2f741792ece.png)

I assume the component to be referenced was this component

![image](https://user-images.githubusercontent.com/102740235/176254695-98bc8bfc-5b6e-4e49-b076-b8aa5f5e080b.png)

**Comment by tohhengxing** [comment]
Hi, I've finished all except the css for screen width < 900px for mobile view. Is this okay? I tried to follow the intent of the drawing as best as i could. @mantariksh @syan-syan 



https://user-images.githubusercontent.com/102740235/176912372-7cf4c7dc-b16d-4891-86c9-bda8d8aeb975.mp4

**Comment by mantariksh** [comment]
done

**Comment by tohhengxing** [comment]
> done

Hi @mantariksh i'll probably port this over to the react version soon. Just to keep you in the loop. Thank you very much!
