### ISSUE TITLE
Enhance email sending resilience

### ISSUE THREAD

**Issue by timotheeg** [opengovsg/FormSG#2823]
Revisit SES resilience for verified fields

**Comment by mantariksh** [comment]
For clarity, this issue is to explore how to make our email sending infrastructure more resilient, e.g. by delegating email confirmations to a separate queue to reduce usage spikes

**Comment by timotheeg** [comment]
Additional use case from @kennethchangOPENGOV and Mindef to support the split use case.

Mindef is not receiving OTP emails from for UAT and goGovSg because these low-volume senders have a reputation of "low".

Mindef could whitelist sender IPs, but they don't really want to do it, because formSG allows user-submitted attachments, which we do not pre-scan for viruses. 

Splitting the email queues (OTP versus submissions), would allow OTP sender IPs at least to be whitelisted should the need arise.

**Comment by foochifa** [comment]
To track internally!
