### ISSUE TITLE
CRLF vs LF for init-localstack.sh

### ISSUE THREAD

**Issue by Vemrthiss** [opengovsg/FormSG#2895]
If one is using windows for development, after cloning the repo, the EOL of the init-localstack.sh must be changed from CRLF to LF, else the docker setup wouldn't work. I suppose this has no issues with UNIX-based systems, so just as a footnote in your README.md file, you could specify that in order to get the docker container to be setup properly, one needs to do an EOL conversion from CRLF to LF.

**Comment by foochifa** [comment]
Will track this internally!
