### ISSUE TITLE
[Feature Request] Direct Link to Individual Response

### ISSUE THREAD

**Issue by frankchn** [opengovsg/FormSG#294]
There should be a unique URL that takes a form admin to the individual response page. When viewing individual responses, the URL in the user's address bar should also change (if possible).

In addition, these URLs should be included in the CSV exports so that users can find individual responses and download attachments much more easily.

Proposed URL format: https://form.gov.sg/FORM_ID/admin/view-response/REF_ID

**Comment by syan-syan** [comment]
wontfix for now as we are not sure we will still have response pages in form v3 (after react). doing user research on this question now.
