### ISSUE TITLE
Logic for checkboxes

### ISSUE THREAD

**Issue by r00dgirl** [opengovsg/FormSG#30]
**Background**

Checkbox is the next most popular limited-choice field after those supported by logic - at 6.8% of all occurrences it is about as popular as Yes/No. The checkbox field serves unique use cases where admins want respondents to be able to select up to _n_ choices, instead of just one choice. 

Currently it is not feasible to set a logic condition for a respondent's choices having included a particular value. 
- the logic-based workaround is very unwieldy, you would have to ask about each choice as its own individual question, at the expense of respondent UX
- more likely you would just do away with logic, and just issue a text-based prompt to respondents to answer a further question if it is applicable to them, especially if you have lots of checkbox options

**Discuss**

'includes' enum for checkbox fieldType

**Comment by mantariksh** [comment]
bumping priority as engineering design is already complete, so this is an easy win which we can get while the engineering design is still up to date

**Comment by mantariksh** [comment]
design doc:
https://docs.google.com/document/d/1ggEb9UyHjK3EipQjXpCmOwaenM6_f1AqcE46VxBkIZI/edit

closed AngularJS PR:
https://github.com/opengovsg/FormSG/pull/2389

**Comment by tshuli** [comment]
Moved to linear
