### ISSUE TITLE
Icon to search for submission ID is not clickable

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#3111]
When attempting to search for submission ID in storage mode under data tab, clicking on the search icon does not trigger the search box to appear. Instead I have to hover my mouse around the top right of the icon until I see the cursor change to a pointer, upon which I can click and trigger the search box.

**Comment by LinHuiqing** [comment]
Closing as I am unable to reproduce and I don't see any complaints for this on support tix!
