### ISSUE TITLE
User research: Payments

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#313]
We've been getting requests through PaySG from agencies who would like payments.

possible options
- open separate link for payment and submit form separately
- submit form then redirected to payment page then thank you page 

user research
- useful to speak to PaySG team 
- then various users' use cases

can fill results in private issue discussion doc since agencies and users likely to be mentioned: https://docs.google.com/document/d/1ccgdAHuyiJqyE_Ivrw_89bmowSIFrkx7wFHSoIAcvIg/edit#heading=h.z07s2u4s0tz7

**Comment by liangyuanruo** [comment]
Reprioritising to P3 as this is to be done after React migration

**Comment by syan-syan** [comment]
partially completed, insights synthesised over 21 interviews / use cases 
https://docs.google.com/document/d/1ghoSjZt19kdqhy17VBs_8NG3p9z_7zHRMqmiyF-wLk4/edit#

will pick up again pending paygovsg team's design decisions
