### ISSUE TITLE
Downgrade BusBoy package back to 0.3.1

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#3299]
Filenames seem to be double-encoded, causing some differences in the file names in submitted attachments.
See relevant issue opened in https://github.com/mscdex/busboy/issues/274

**Comment by Fernando-R** [comment]
Also, the field Name Size validation seems to not be working, at least the field name is not being truncated, I just saw it and have not tested it properly, also have not tested if the value is being truncated. (I'm kinda busy right now so sorry about that)

**Comment by karrui** [comment]
> Also, the field Name Size validation seems to not be working, at least the field name is not being truncated, I just saw it and have not tested it properly, also have not tested if the value is being truncated. (I'm kinda busy right now so sorry about that)

What is the name size validation you are referring to? Is it an issue with FormSG or busboy?
