### ISSUE TITLE
Remove self from collaborator list

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#33]
**Give users the ability to remove themselves from collaborator lists of forms**

Currently only the form owner can remove a collaborator; this is slightly more inconvenient during events such as handing over administration of a form than if collaborators had the ability to remove themselves.

**Proposed solution** to add a bin next to own name for Editors and Read-only to remove oneself.

Confirmation modal: "You will be removed as a collaborator and will lose access to this form. You cannot undo this." buttons: "Remove me" and "Cancel"

**Comment by frankchn** [comment]
![image](https://user-images.githubusercontent.com/691628/122664876-d2dda380-d158-11eb-91fd-0efe4f6eb2a3.png)
