### ISSUE TITLE
[bug]: .JFIF extension logo uploads are being allowed in the client but is blocked in the server

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#3369]
**Describe the bug**

As an admin, client allows the upload of .JFIF (JPEG File Interchange Format) files, but Joi validation on the server only allows for certain file extension formats:

```ts
Joi.string()
  .pattern(/\.(gif|png|jpeg|jpg)$/im)
  .required(),
```

**To Reproduce**
1. Create a new form (or go to existing)
2. Edit start page, upload a logo, provide an image with the `.jfif` extension
3. Save form
4. 400 response by server, with toast "This page seems outdated, and your changes could not be saved. Please refresh" showing up for the user.

**Expected behavior**
Should either
1. Only allow GIF/PNG/JPEG/JPG extensions on the client and clearly display the error, or
2. Loosen joi validation since JFIF is a valid image file extension.

**Additional context**

Reported by one of our users.

**Comment by karrui** [comment]
@mantariksh @syan-syan  any updates on this? Have we gotten confirmation that `.jfif` files can be downloaded on GSIB?

**Comment by syan-syan** [comment]
@karrui just got confirmation that both jfif and mov can be downloaded
