### ISSUE TITLE
[8] Database read time spikes due to response downloads

### ISSUE THREAD

**Issue by timotheeg** [opengovsg/FormSG#3394]
When admin of large form downloads responses (thousands or tens of thousands), the current implementation issues one very large and long running query to mongoDB.

This consumes a long running operation on node and on mongo. While both should be broken down and driven in multiple requests from the client itself, at minimum we should split the mongo query into smaller paginated queries to ensure no query may lock the DB.

**Comment by mantariksh** [comment]
renamed this issue to better reflect the intention - perhaps we won't end up solving this by breaking up queries, maybe there's another easier way
