### ISSUE TITLE
Hand over function to transfer all ownership roles

### ISSUE THREAD

**Issue by r00dgirl** [opengovsg/FormSG#34]
What the admin sees:
confirmation message: "This will transfer all the forms you own to 'email address'. You will be removed as a collaborator and lose access to the forms you previously owned.

What should happen:
- [x] For all forms on which admin is Owner, replace ownership with new admin
- [x] Not touching editor and read-only roles for now
- [ ] Log all replacements

**Comment by tshuli** [comment]
@staceytan1998 

Our volunteer @jia1 is keen to take up this issue, could I trouble you to come up with the design for this please?
