### ISSUE TITLE
Duplicating storage mode form allows attachment limit to be exceeded

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#3462]
**Describe the bug**
We have a 7MB limit on total attachment file size in email mode. The corresponding limit in storage mode is 20MB, and duplicating storage mode forms into email mode allows form admins to circumvent the 7MB limit.

**To Reproduce**
1. Create a storage mode form
2. Add attachment field with 20MB size limit
3. Duplicate the form into email mode
4. You can now submit >7MB attachments

**Expected behavior**
Duplication should be rejected when total attachment size exceeds 7MB.

**Comment by LinHuiqing** [comment]
Not sure which PR fixed this, but I can no longer replicate this so it should be fixed!

Current behaviour: 
1. Create a storage mode form
2. Add attachment field with 20MB size limit
3. Duplicate the form into email mode
4. On submission of attachments > 7MB, a "Submission could not be parsed" error was thrown.
