### ISSUE TITLE
Set up testing for iframes

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#3480]
Some forms are embedded in iframes but we have no automated testing to ensure that FormSG can be embedded safely. This means we are vulnerable e.g. to iframes breaking due to CSP headers, and have no way of detecting this before deploying to production.

Possibilities:
- Add an end-to-end test to our existing TestCafe test suite which tests that an embedded form can be rendered correctly
- Spin up a Netlify site with an embedded form and use Pingdom to check that it is correct
  - However, not sure if Pingdom can check the DOM or only HTTP status codes

**Comment by tshuli** [comment]
I set up a netlify [page](https://suspicious-raman-512220.netlify.app/) with a iframe containing a form.

Thereafter, testing can be done in Pingdom using Transactions feature to click inside the iframe. If the iframe fails to load, the Pingdom test will fail.
<img width="968" alt="Screenshot 2022-03-04 at 12 43 24 PM" src="https://user-images.githubusercontent.com/63710093/156700856-64151cc2-3ad8-4d57-8538-73ed8f048d42.png">

If it is ok, will:
1) Set up the pingdom check using the team's account
2) Deploy the page using the team's netlify account (do we even have one?)

Do we still need an e2e test or should we save the eng time and set up the same pingdom check for staging?

@mantariksh

**Comment by tshuli** [comment]
iframe alerts have been set up to slack for both prod and staging. Closing issue
