### ISSUE TITLE
Decide MyInfo e2ee approach

### ISSUE THREAD

**Issue by r00dgirl** [opengovsg/FormSG#3492]
Assess approach recommended by MyInfo for supporting e2ee vs PKCE

**Comment by LinHuiqing** [comment]
No longer relevant as we're moving away from E2EE - Encryption Boundary Shift RFC: https://docs.google.com/document/d/1VmNXS_xYY2Yg30AwVqzdndBp5yRJGSDsyjBnH51ktyc/edit?usp=sharing
