### ISSUE TITLE
Feature request, add TOU/PP to all forms, OGP footer, and fixes

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#369]
**Feature request form**
- [x] add 'Feature Request' as first navbar item before Examples https://form.gov.sg/#!/5f986c77d241e400119b98b7

**Footer addition**
- design https://zpl.io/VDLgYnl
- Incorporates OGP footer with TOU and PP on all routes, including public forms. Right now TOU and PP are just on our landing page but we should put them in public forms for ease of access because some of these terms (e.g. privacy) are applicable to respondents. 
- [x] Footer for landing
- [x] Footer for public form

**TOU and PP in footer**
- formatting (e.g. indenting) is not standardised in word doc but let us standardise on front end
- do not bold/italicise the numbering, only the text
- PP https://docs.google.com/document/d/1l84g8VTd3rudU5J2OkM5DmgN6QuWha_L6lD_4QhX5-A/edit#
- TOU https://docs.google.com/document/d/12rlJWryR64riy8DYKC8Q7N0ciwODE2Qav2VCINlBHls/edit#
- update the dates on the PP and TOU to the release date
- [x] TOU updated
- [x] PP updated

other
- [x] on public form, move the following note on SPCP forms below the "Login with SPCP" button: "Login with SingPass to access this form. Your SingPass ID will be included with your form submission." Note should not exceed form title max width. In forms with long set of Instructions, this note is pushed all the way to the bottom and also exceeds the instructions container. 
- [x] ! does not disappear from user profile icon after emergency contact number has been added, until page is refreshed. fix quickly if possible, if not can push to react rewrite. 
- [x] change 'Verified?' on SMS config to say 'OTP verification' like on Email

**Comment by pearlyong** [comment]
design here: https://zpl.io/VDLgYnl
