### ISSUE TITLE
Investigate marginal cost of using NAT gateway to enforce static IP for webhooks

### ISSUE THREAD

**Issue by r00dgirl** [opengovsg/FormSG#3731]
**Why**
Many govt endpoints are behind firewalls and need to whitelist our originating IP addresses to receive webhooked traffic

**Discussion**
https://opengovproducts.slack.com/archives/CKHLS3W3X/p1649398657632879

**Comment by LinHuiqing** [comment]
Static IPs have been enforced, static IPs listed in guide here: https://guide.form.gov.sg/user-guides/advanced-guide/webhooks
