### ISSUE TITLE
Feature request: synchronous execution of webhooks

### ISSUE THREAD

**Issue by oliverchanyw** [opengovsg/FormSG#3782]
## Problem
- FormSG's webhook feature allows us to easily build programmatic flows triggered by user data entry.
- As we expand webhook usage, some of these transactional flows have grown more complex. They may reject on business-logic that's more complex than the data validation available on Forms.
  - [MOH clinics requesting for NAS whitelisting](https://form.gov.sg/#!/601bfcbb0101a800122f4df2)
  - [Doctors submitting Covid protocols](https://form.gov.sg/#!/61c45d23edf5ba0014230627)
- To complete the user flow with confirmation / rejection, the team has adopted a few patterns, all of which feel awkward
  - Taking email as a field so webhook can send a confirmatory 'ack'
    - For protocol submission, we took JWTs as a proof of identity, and it was even more awkward - we didn't send an email to PRPP to notify them of an invalid JWT because that'd open the possibility of an attacker spamming PRPP via us, by submitting many wrongly-signed JWTs.
  - Asking users to do their own data validation
<img width="500" alt="Screenshot 2022-04-23 at 2 47 21 PM" src="https://user-images.githubusercontent.com/25238106/164883578-5886b5c1-e51d-4e8f-a260-58cb42b79243.png">

- This delayed / incomplete user feedback loop widens the possibility of expensive reconciliation when the system built on top of Form webhooks has production incidents, since users receive the success screen upon form submission, and are not alerted to backend failure.

## Possible Solution
- Form to offer an option for synchronous webhook execution, which blocks user on webhook execution.
- Based on webhook response, Form can display some of this information to users.
  - Minimally, I suppose `statusCode` and `message`
  - Form webhook SDK might be a good place to enforce a contract for such handlers
- Errorful messages can allow users to resubmit the form with mistakes rectified, or take other action, e.g. doctors will check with their IT folks why their JWT is expired.
- In a way, Form would begin to resemble a low-code REST client

### Risks
- The user's experience of Form now depends on these 3rd party webhooks' timely execution and readability of their messages

**Comment by LinHuiqing** [comment]
Migrated to Linear: FRM-1411
