### ISSUE TITLE
Should validate parsed shape of incoming SNS message bodies in BounceController

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#3787]
**Describe the bug**
We currently only validate incoming SNS requests via its signatures and checking for available keys. However, there is still a possibility that the body is malformed after parsing the body, resulting in possible type errors such as

```
(node:18) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'headers' of undefined
at extractHeader (/opt/formsg/dist/backend/src/app/modules/bounce/bounce.util.js:13:28)
```

**Comment by LinHuiqing** [comment]
Closed by https://github.com/opengovsg/FormSG/pull/3959 and https://github.com/opengovsg/FormSG/pull/3832
