### ISSUE TITLE
[React/AdminLogic] Sort logic by question number

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#3796]
Currently backend is returning us logic according to creation date. 

Since backend is on a code-freeze, we should sort by question number on the react client. No big deal anyways since the amount of logic on a form should not be a huge number (like 100k) anyways.

**Comment by amitogp** [comment]
Hi @karrui, can we move this issue into an appropriate column instead of Out of sprint?

**Comment by LinHuiqing** [comment]
Migrated to Linear: FRM-1409
