### ISSUE TITLE
[UX revamp] Attachment field design

### ISSUE THREAD

**Issue by r00dgirl** [opengovsg/FormSG#38]
**problem**

today, the admin needs to collect some info in the attachments but does not know how many actual attachments the respondent has to submit. 
e.g. Submit screenshots of your error. Its one error, but could be 1, 2, 3, 4 screenshots.

despite this, only one attachment can be uploaded per field.

this means that if respondent has multiple attachments (pictures for example), they will need to zip them up before uploading. this is too difficult on mobile, and mobile is 75% of respondents.

**constraints**

- Emails have limit of 7mb attachments over entire form, Storage mode has limit of 20mb attachments. 
- mobile (75%) respondents would probably not be able to zip

**research** @wing-yiu 

- forms with multiple attachment fields that are sprinkled throughout the form, not clustered together
- forms with attachment fields hidden by logic 

**what we want**

for the respondent
- upload as many attachments as needed, but keep within the size limit
- be informed at point of upload if the size limit has been reached, so they dont fill in other fields before submission fails

for the admin
- be able to communicate that they want different kinds of attachments, subject to logic if necessary

possible design
- multiple uploads enabled for attachment field
- continue to have multiple attachment fields anyway, to support logic, communication of different types of attachments, and form admin flexibility
- each attachment field when clicked will show progress toward the size limit, similar to our design for attachment field config today

**Comment by syan-syan** [comment]
@leonardloo @liangyuanruo what was original motivation for the size limits? any eng constraints to be aware of?

**Comment by wing-yiu** [comment]
@syan-syan this is related to issue #854 on bulk attachment downloads. 

- Most submissions are no where near the 20mb size limit, 95th percentile of submission size is only 2.65mb.

- Forms typically have up to 2 attachment fields. Depending on logic, not all the attachment fields are visible to the respondent. What is the purpose of knowing whether attachment fields are sprinkled across the form?.

- Almost half of the forms with attachment field requires logic. _But the logic does not necessarily determine whether the attachment will be shown. Could be used for other fields in the form._

**Comment by tshuli** [comment]
Moved to Linear
