### ISSUE TITLE
Re-evaluate the message sent out to users when there are bounced responses

### ISSUE THREAD

**Issue by jacksonOGP** [opengovsg/FormSG#3809]
Currently, when there are bounced responses on form. Users will receive SMS with the following message (see ss attached)

![image](https://user-images.githubusercontent.com/70509050/165693587-bb37fe17-d341-465a-9603-70ccaa3557e1.png)

However, for this user (see tix for more info)
https://formsg.zendesk.com/agent/tickets/682

The bounce occur **due to reasons outside of full mailbox**. Which makes the SMS content inaccurate. This caused from level of panic/anxiety from user and we should re-evaluate the content in our sms.

Ideally It would be great to reflect accurately what happen and add in steps of rectification on user's end so there's a clear actions to be taken by user.

**Comment by LinHuiqing** [comment]
Migrated to Linear: FRM-1407
