### ISSUE TITLE
Report submissions timestamps in ISO format

### ISSUE THREAD

**Issue by timotheeg** [opengovsg/FormSG#3822]
We currently format the submission timestamp to be human readable (e.g. `Thu, 21 Apr 2022 03:27:39 PM`) in both the emails and collation tool json, but this has 3 problems:

1. it’s not a format readily understood by excel
2. it’s not lexicographically sortable
3. it’s dropping millisecond accuracy (which we have in DB!)

These make it hard for admins to sort by submission timestamp easily. It would be nice if we had an additional field `iso_timestamp` in standard format: `2022-04-21T07:27:39.000Z`

Well… excel does not understands ISO datetimes either 🙄 , but at least, the values would be sortable lexicographically.

**Comment by LinHuiqing** [comment]
Migrated to Linear: FRM-1406
