### ISSUE TITLE
Validate that logo and image URLs point to S3

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#3901]
URLs in the database which are meant to point to S3 are not currently validated as S3 URLs. In theory, an admin could update their logo or image URL to a non-S3 URL via API. This is unlikely but nevertheless can be easily prevented by model-level validation which ensures that URLs point to the correct S3 bucket.

We do not have validation for attachment S3 URLs either, but they cannot be accessed via API so this is less of a concern.

**Comment by tshuli** [comment]
If I'm not wrong, I think this only applies for image URLs - for logo, we only store `logo.fileId`, and then retrieve it directly from the s3 bucket on page load (see `src/public/modules/forms/helpers/logo.js`

(similarly the logo upload api doesn't accept custom url, and saves it only in the s3 bucket)

**Comment by mantariksh** [comment]
Longer-term fix for images would be to store the image ID instead of a URL like we do for logos, but this would be a backwards-incompatible change
