### ISSUE TITLE
Remove ability to clear dropdowns in field editing forms

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#3932]
e.g. Clicking the "X" in the "Number of steps" dropdown while editing Rating fields results in weird behaviour where the field disappears:
<img width="1478" alt="Screenshot 2022-06-01 at 10 27 38 AM" src="https://user-images.githubusercontent.com/29480346/171315674-6d33d588-3622-44a7-a7b5-df995ae4e1b5.png">

**Comment by karrui** [comment]
closed by #3942
