### ISSUE TITLE
Improve dev environment

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#3934]
Current dev environment has quite a few problems for developers, e.g. every time a new package is installed, the docker image needs to be deleted and rebuilt. Also it takes about 10-15min to build.

Once AngularJS frontend has been deprecated, investigate how we can improve this for developers.

**Comment by LinHuiqing** [comment]
Migrated to Linear - [FRM-1403 : Improve dev environment](https://linear.app/ogp/issue/FRM-1403/improve-dev-environment)

**Comment by LinHuiqing** [comment]
Migrated to Linear - [FRM-1403 : Improve dev environment](https://linear.app/ogp/issue/FRM-1403/improve-dev-environment)
