### ISSUE TITLE
Pre-fill does not allow # 

### ISSUE THREAD

**Issue by kennethchangOPENGOV** [opengovsg/FormSG#3951]
When pre-fill URLs have # in it, any pre-fills after the # will not work. 

Example here: https://form.gov.sg/625e20c24445f900126efa3c?6299852f3635bd0012e80607=Yew%20Tee%20Primary%20School&629986c4d9172c0012e95144=Yew%20Tee%20Secondary&629986c6a86cbf0012c99f42=Yew%20Tee%20Tertiery&629986cf3635bd0012e83ed2=Yew%20#Tee%20University&629986d1a86cbf0012c9a008=Yew%20Tee%20Kindergarten

**Comment by tshuli** [comment]
For now, can url-encode # with %23 as a workaround, e.g.

[https://form.gov.sg/625e20c24445f900126efa3c?6299852f3635bd0012e80607=Yew%20Tee%20Primary%20School&629986c4d9172c0012e95144=Yew%20Tee%20Secondary&629986c6a86cbf0012c99f42=Yew%20Tee%20Tertiery&629986cf3635bd0012e83ed2=Yew%20%23Tee%20University&629986d1a86cbf0012c9a008=Yew%20Tee%20Kindergarten](https://form.gov.sg/625e20c24445f900126efa3c?6299852f3635bd0012e80607=Yew%20Tee%20Primary%20School&629986c4d9172c0012e95144=Yew%20Tee%20Secondary&629986c6a86cbf0012c99f42=Yew%20Tee%20Tertiery&629986cf3635bd0012e83ed2=Yew%20%23Tee%20University&629986d1a86cbf0012c9a008=Yew%20Tee%20Kindergarten)

To look into this after react
