### ISSUE TITLE
[React/Exploration] Explore using streamsaver to stream csv responses download

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#3963]
instead of holding the decrypted responses in memory, we can explore using modern(ish) technologies to stream directly to the user's computer.

explore https://www.npmjs.com/package/streamsaver and alternative options.

not sure if GSIBs will work with this, so this should be purely exploratory and a separate download option.

can probably build on https://github.com/opengovsg/FormSG/pull/3953

**Comment by frankchn** [comment]
Some results of an preliminary investigation: I think ultimately this depends on whether we can do streamed decryption and it doesn't look like the core of `opengovsg/formsg-sdk` (based on [`tweetnacl`](https://www.npmjs.com/package/tweetnacl)) supports streaming decryption.

In that case, we won't be saving much memory so long as the Javascript engine does a good job with garbage collection by clearing the unused blobs from memory quickly. 

To implement this properly would require us to use another library (e.g. [`nacl-stream`](https://github.com/dchest/nacl-stream-js)) to decrypt attachments, which is a much larger effort. I am also not sure whether the other libraries are compatible with how we encrypt attachments currently. 

I can see how much RAM is required to actually download 20MB attachments consecutively to see if this is worth the effort to implement.

**Comment by frankchn** [comment]
After conversation: look into CSV saving after decryption, since that is the issue with large memory consumption, since we are buffering the entire CSV file into memory. Perhaps with StreamSaver.js, we can save each line of the CSV file bit by bit as they come in?

**Comment by frankchn** [comment]
Hmm looked at this again for just the CSV responses. Given that we write out the success count, error count, and unverified response count at the top of the CSV, we have to buffer the responses and write them out all at once after writing the success/error/unverified response count.

**Comment by LinHuiqing** [comment]
Migrated to Linear: FRM-1397
