### ISSUE TITLE
Increase responsiveness of autoscaling rules

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#3970]
Update autoscaling rules so that more instances can be added faster. See [this issue](https://docs.google.com/document/d/1gPou4qriMOaYDwopBx6CkAL45OZ2wDpYUkd1C7ntrEc/edit#).

**Comment by LinHuiqing** [comment]
Superseded by https://github.com/opengovsg/formsg-private/issues/137 too, which should be tackled next year!
