### ISSUE TITLE
[React] What's New Feature

### ISSUE THREAD

**Issue by siddarth2824** [opengovsg/FormSG#3984]
Currently the only way form admins are able to see the latest feature updates, is by viewing it at https://guide.form.gov.sg/Roadmap.html#latest-features. This is not ideal as form admins will not always be updated of what the new feature updates are for FormSG unless they visit the latest-features page periodically. Hence to make it more convenient for form admins to be notified whenever there are new feature updates, the “What’s New” tab on the navigation bar of FormSG will notify form admins whenever there is a new feature update.

- [x] #3985
- [x] #3986
- [x] #3987
- [x] #3988
- [x] #3989
- [x] #4582 
- [x] #4093 
- [ ] #4598

**Comment by mantariksh** [comment]
going out with React rollout
