### ISSUE TITLE
[React] Explore reCaptchaV3

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#3994]
Can further be used in other endpoints we should prevent automation on such as the otp generation public form endpoint.

To explore v3, and if we find a relatively decent score threshold, can use v3 on submission endpoint too.

**Comment by mantariksh** [comment]
bumping priority back down to reduce duplicate work between current and new React frontend

**Comment by LinHuiqing** [comment]
Superseded by turnstile integration in https://github.com/opengovsg/FormSG/pull/6483
