### ISSUE TITLE
[React] Field builder does not close after saving

### ISSUE THREAD

**Issue by kennethchangOPENGOV** [opengovsg/FormSG#4018]
![image](https://user-images.githubusercontent.com/103998698/174702196-3950aae4-1829-484b-806d-1b4306fb5045.png)

It is intended for it to close so that user can continue to build other fields without having to press back or close it manually.

**Comment by justynoh** [comment]
Should the builder close entirely, or should it go back to field selection?

**Comment by tutntut** [comment]
> Should the builder close entirely, or should it go back to field selection?

<img width="919" alt="image" src="https://user-images.githubusercontent.com/103998698/175207358-3a8e428c-089d-4bc1-9755-eea2e9c733d3.png">

It should go back to the field selection.

**Comment by justynoh** [comment]
resolved!
