### ISSUE TITLE
Redundant ValidationOption object properties for short text, long text and number fields

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#408]
The `ValidationOption` object defines the required validation rules for the short text and long text fields. An example for Short Text is shown below:

```typescript
enum ShortTextSelectedValidation {
  Max = 'Maximum',
  Min = 'Minimum',
  Exact = 'Exact',
  Range = 'Range',
}

{
  customMax: number | null
  customMin: number | null
  customVal: number | null
  selectedValidation: ShortTextSelectedValidation | null
}
```

The type model is potentially inconsistent for the following reasons:

- Short text and long text fields do not offer range validation, so the type system is not reflective of application functionality today.
- The key `selectedValidation` defines the validation rule being applied, while the `customVal` property defines the number of characters to validate against. This makes the `customMin` and `customMax` keys redundant and runs the risk of inconsistent application state.

TODOs:
1. Verify that the database is internally consistent today for all short text and long text fields:
  a. `customVal === customMin` when `selectedValidation === 'Minimum'`
  b. `customVal === customMax` when `selectedValidation === 'Maximum'`
  c. `customVal === customMin === customMax` when `selectedValidation === 'Exact'`
  d. `selectedValidation === 'Range'` should not exist
2. Simplify the codebase by removing references to `customMin`, `customMax` and `Range`
3. Write a database migration script and/or mongoose hooks to fix inconsistencies discovered

**Comment by tshuli** [comment]
@liangyuanruo should we extend this to include number field? The same considerations apply as (i) number field does not offer range validation, and (ii) customMin and customMax are redundant

**Comment by liangyuanruo** [comment]
Yes, let's do that!
