### ISSUE TITLE
TOU and Privacy Policy numbering should match AngularJS app

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#4111]
In the AngularJS frontend, each sub-clause in the TOU and privacy policy is hierarchically numbered such that the sub-clauses contain both the clause and sub-clause numbers. E.g. sub-clause 1 of clause 3A is listed as `3A.1` rather than just `1.`:

<img width="1103" alt="Screenshot 2022-07-06 at 4 37 46 PM" src="https://user-images.githubusercontent.com/29480346/177507904-cb4b6c68-c0e8-4a10-b6f0-de5cb1172913.png">
 
But in React, only the sub-clause numbers are shown, and the 1,2,3 numbering changes to a,b,c:
<img width="834" alt="Screenshot 2022-07-06 at 4 38 31 PM" src="https://user-images.githubusercontent.com/29480346/177508060-2b25b74b-3bfa-454a-9b84-cdd26479d8d2.png">
 
Legal has requested for each sub-clause to contain the full clause number (e.g. `3A.1` rather than just `1.`). Also, numbering which was previously 1,2,3 should be kept that way, not changed to a,b,c.

**Comment by tohhengxing** [comment]
Hi @mantariksh can i be assigned this card? I have worked out and implemented a draft solution that doesn't depend on hard coding the subsections. However, there are some minor style limitations to my approach. I tried my best to imitate the angular version with the spacings and such.

Here are some pictures

![image](https://user-images.githubusercontent.com/102740235/179827896-ff6b4435-c4c5-4dbc-90b1-6967c99f1377.png)

![image](https://user-images.githubusercontent.com/102740235/179827928-2149bc40-580c-432b-b995-96cec689e4a7.png)

![image](https://user-images.githubusercontent.com/102740235/179827962-da8cf6d5-c3ea-4345-9587-014baa3be8cb.png)

![image](https://user-images.githubusercontent.com/102740235/179828014-57d73029-6d1c-4d4e-9b88-ac4b3a398552.png)

![image](https://user-images.githubusercontent.com/102740235/179828042-2cd09908-de7a-47c4-b12e-36fdd3ec5646.png)

**Comment by mantariksh** [comment]
hey @tohhengxing sorry for the late response, thanks for picking this up! we're sprinting for React migration right now so apologies if it takes a while to review your code, but we'll get back to you.

**Comment by karrui** [comment]
closed by #4424
