### ISSUE TITLE
[React] Form admins are able to attempt creation of MyInfo fields even when they do not have it enabled

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#4118]
backend correctly rejects this, but we should still block it properly in the client.

![Recording 2022-07-06 at 16 53 35](https://user-images.githubusercontent.com/22133008/177688861-9ce67a46-7044-4f59-bc77-385f99ba85e4.gif)

**Comment by karrui** [comment]
Closed by #4233

**Comment by seaerchin** [comment]
Why does it not auto close ._.

**Comment by karrui** [comment]
not main branch haha
