### ISSUE TITLE
[0.5] Make response table row highlight on hover

### ISSUE THREAD

**Issue by justynoh** [opengovsg/FormSG#4128]
1. Currently, clicking on storage response table rows directs the user to a page with an individual response. However, this is not apparent to the user from the page itself. We can consider changing the cursor to a hand as well as highlighting the row when the cursor hovers over the row to make it more apparent that the row is clickable. Look for @pearlyong for design specifics on this :)

4. Additionally, right now, the reference ID in the table is not highlightable (clicking and dragging along the reference ID causes the individual response page to open instead). Lumping in with this issue because it involves the same component.

**Comment by pearlyong** [comment]
hover and active state [here](https://www.figma.com/file/u00dlQLsaQfvqv6ot5ZrJZ/Form-Design-System?node-id=921%3A25818)

**Comment by wanlingt** [comment]
discussed with @pearlyong - will leave behaviour in 2) as it is to maintain parity with angular, also it's not super necessary
