### ISSUE TITLE
[React] Instantiate emergency contact modal in admin header

### ISSUE THREAD

**Issue by wanlingt** [opengovsg/FormSG#4153]
Emergency contact modal should be instantiated in the admin header, not the workspace page. 
Also, clear emergencyContactKey in local storage upon logout
(Refer to this [PR](https://github.com/opengovsg/FormSG/pull/4125) for context)

**To be done after #4006 Admin Header component is complete**

**Comment by karrui** [comment]
is this completed? @wanlingt

**Comment by wanlingt** [comment]
> is this completed? @wanlingt

yup thanks!
