### ISSUE TITLE
[2] a11y: required fields are reporting as "required invalid data" even when there are no errors yet

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#4177]
Seems to be a quirk of screen readers (maybe don't flame me if i'm wrong), known issues from quick Googling.

One fix could be to set `aria-invalid=false` when there are no errors explicitly: https://stackoverflow.com/a/72463036

We should experiment with a bunch of aria props so we can check which approach is best.

Further reading: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-invalid

**Comment by justynoh** [comment]
This may not be the universally correct approach - refer to this set of reference forms to see why

https://russmaxdesign.github.io/accessible-forms/index.html#required

 It seems that setting aria-invalid doesn't really cover everything. Instead, the approach suggested here is to ignore the `required` attribute completely, and use `aria-required` instead along with backend validation before form submission (which we already have with rhf, anyway, so we don't really need the `required` attribute, right? - correct me if i'm wrong)

The downside to this approach is that we provide `isRequired` to chakra `use*(props)`, which return css props that have the `required` property, so we will have to override that with `required = false` universally somehow...

**Comment by karrui** [comment]
closed by #4916
