### ISSUE TITLE
Bulk attachment download on Storage mode: UX

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#418]
**Flow**

1. user selects date range, and clicks export which drops down into csv and attachments as in sketch done below by design
2. on clicking Attachments, modal appears " **You are about to download attachments for 1,049 responses** // This may take a while. Click Download to continue, or Back to adjust your date range. "
3. attachments will download in individual zip files, one per submission, to the user's downloads (or other default) folder
4. progress bar to be implemented in another engineering issue

**Sketch**

https://docs.google.com/presentation/d/1aPd00VAuMH41jcL9rq1sq8KHcE0ZY8UcSvAotz3f-ZI/edit#slide=id.g77fcc4c89b_0_4

**Comment by pearlyong** [comment]
zeplin screens here for first cut: https://app.zeplin.io/project/5b29ffde48eaaf6318d01b05/dashboard?seid=5f87c5ed5cf4fc4b800abbde

will do up a progress bar for next cut

**Comment by syan-syan** [comment]
@pearlyong can we have a view for failures/errors? toastr also ok if you think that is enough. 

@frankchn @liangyuanruo to note

**Comment by syan-syan** [comment]
update after discussion today

for **option 1: download attachments by pasting responseId list**, as mentioned in case of error we can return admin a list of responseIds in modal/csv to retry. there will then be no overlap between successful and retried downloads.

for **option 2: download attachments by selecting date range**. best we can do is return admin a list of responseIds and dates, or a date range for the failed downloads, so they can retry that date range. BUT there will be overlap between successful and retried downloads, because downloading is only loosely chronological. the duplicate downloads will download as "folder (1)" etc. a little hard to catch

@pearlyong @frankchn @liangyuanruo feel free to add on if you think of other options

in view of above I am in favour of option 1 in the meantime until we can figure out a better UX for error handling.
