### ISSUE TITLE
Percentage-based React rollout for form admins

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#4217]
We should be able to progressively roll out the React frontend for form admins (workspace, form editing etc) by randomly assigning them a React/Angular cookie based on a predefined rollout percentage.

Ideally, we should have independent rollout thresholds for the admins and respondents. This is because given that the admin side is much more complex than the respondent side, there may be issues which purely affect form admins and might require us to roll back the admin side. In this case, ideally we can let the respondent side continue being tested while we fix the admin side.

Our current assessment is that independent thresholds are not difficult to implement, but if they turn out to be more complex than expected, we can discuss the possibility of making the admin rollout percentage identical to the respondent (no auth) rollout percentage.

Note: the previous plan was to have 2 weeks of allowing admins to opt in to React, after which they would see React by default. However, the risk of this is that we might not have enough testers in the first two weeks, and might then see a spike in issues when React becomes the default. A percentage-based rollout helps us avoid this.

### Once on React, stay on React

We also don't want users to be flipped back and forth between React and AngularJS as it will be disruptive to flip back to AngularJS just as they are getting used to React. If they get assigned React, they should stay on React.

### Once opting for Angular, stay on Angular until React is stable

We don't want situations where users opt in to Angular because they are facing issues, then we forcibly put them back on React, then they face issues again.

### Ability to increase rollout percentage

If we go with the current implementation where the admin cookie expiry is 2 months, we won't be able to ramp up the percentage progressively. This is because a user who gets randomly assigned AngularJS the first time (e.g. when rollout percentage is 1%) will continue being assigned AngularJS even when the rollout percentage is increased.

However, it is okay to have the actual percentage of admin users on React be higher than the rollout percentage (e.g. our percentage is 35% but actually 45% of users are on React).

So an implementation like this would work: when randomly choosing React/AngularJS, if choosing React, set a 2-month expiry. If choosing AngularJS, set a session expiry. Then when the rollout percentage is increased, those previously on AngularJS would be randomly assigned again, while those on React would stay on React. This means that e.g. when we increase rollout percentage to 10%, in reality it will be 10% + whoever was previously assigned React, but this is fine.

**Comment by wanlingt** [comment]
**Admins** cookie expiry (refer to #4263 )
- random assignment
  - react: 2 months
  - angular: session
- personal choice - react to angular: 2 months
- personal choice - angular to react: 2 months
