### ISSUE TITLE
Restrict email domains toggle should be hidden if sms feature is not enabled

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#422]
As seen on a deployment where all features are disabled:

![Screenshot 2020-10-06 at 3 06 39 PM](https://user-images.githubusercontent.com/22133008/95169493-8b3f0380-07e5-11eb-9fa8-83163a1c26a1.png)

**Comment by syan-syan** [comment]
btw how come our email OTP verification is under sms feature

**Comment by karrui** [comment]
> btw how come our email OTP verification is under sms feature

It's under `verified-fields` feature though, not `sms` feature. `sms` is gated by Twilio envvars, `verified-fields` is gated by verification signature env var
