### ISSUE TITLE
Singpass authentication options are missing tooltips and additional info

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#4246]
Authentication options in settings page should have the same tooltips as in AngularJS, as well as the "Contact Us" link for SGID.

**Comment by justynoh** [comment]
is sgID login supposed to be disabled by default (like in the angular app)?

may be related to this todo in `frontend/src/features/admin-form/settings/components/AuthSettingsSection/AuthSettingsSection.tsx`

<img width="487" alt="image" src="https://user-images.githubusercontent.com/25571626/180148707-5d5e1d47-c673-4663-abef-d1f938d19db5.png">

**Comment by mantariksh** [comment]
@justynoh yes, supposed to be disabled unless user has `betaFlags.sgid` enabled. can cross check with Angular app
