### ISSUE TITLE
Switch to React via URL

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#4289]
Rollout email being sent to power users will contain a link where admins can click to immediately try the new FormSG. Making it a one-click process will significantly reduce friction for potential power user testers.

Implementation - create a GET endpoint where we add the admin React cookie and redirect to the landing page.

**Comment by karrui** [comment]
@wanlingt is this in progress/done?

**Comment by wanlingt** [comment]
> @wanlingt is this in progress/done?

@karrui nope not yet!! was gonna do it but ended up working on another issue after talking to pearly so removed myself first! feel free if u want :D
