### ISSUE TITLE
Link workspace row actions to implemented features

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#4298]
Workspace row actions have been implemented but not linked to each workspace row item.

<img width="456" alt="Screenshot 2022-07-25 at 5 17 07 PM" src="https://user-images.githubusercontent.com/22133008/180742747-219d7636-8a3c-491d-abe3-c59813ae4c3b.png">

- Clicking on preview should navigate the admin user to the preview page: `/admin/form/:formId/preview`
- Duplicate form feature (is not implemented yet) #4198
- Share form should open `ShareFormModal` component
- Manage form access should open `CollaboratorModal` component
- Delete form feature (is not implemented yet)

**Comment by karrui** [comment]
@syan-syan may have some conflicts with #4464 since i'm implementing duplicate form and delete form features haha

edit also added context, maybe i get you to review

**Comment by justynoh** [comment]
Quick note for workspace row actions: need to ensure view only collaborators
- don't see the delete option
- don't see the edit collaborator section of the collaborator modal
- (should they see "View" instead of "Edit" in the button on the right?)

**Comment by karrui** [comment]
> * don't see the edit collaborator section of the collaborator modal

should already be the case, since behaviour is controlled by the modal component

**Comment by karrui** [comment]
closed by #4542
