### ISSUE TITLE
[React QA] Copy changes

### ISSUE THREAD

**Issue by r00dgirl** [opengovsg/FormSG#4301]
Detailed here:
https://docs.google.com/document/d/1A4hzmaoSY4dnu3HqfHE7fkFC1aMeAiGUHdApMd6gSiA/edit#heading=h.4rkxoo10iv51

Landing page
Footer
Login page
Instructions
Thank You field
Twilio credentials page
Feedback

**Comment by timotheeg** [comment]
Closed by #4318
