### ISSUE TITLE
Save button gets cut off

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#4305]
<img width="805" alt="Screenshot 2022-07-25 at 7 00 03 PM" src="https://user-images.githubusercontent.com/29480346/180762137-963f52c2-458b-4476-ac0c-5b8f93539f8e.png">

**Comment by mantariksh** [comment]
not sure how to replicate, can check with @karrui or @pearlyong

**Comment by karrui** [comment]
also suddenly unable to replicate locally, but i will still add a padding

**Comment by karrui** [comment]
able to replicate, figuring out why now

**Comment by karrui** [comment]
fixed by #4451
