### ISSUE TITLE
User should see MyInfo instead of Basic fields upon saving MyInfo field

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#4309]

**Comment by justynoh** [comment]
Currently, MyInfo fields are not labelled in the form builder preview, whereas there is a label for them in the AngularJS version. See below for diff.

<img width="1571" alt="image" src="https://user-images.githubusercontent.com/25571626/180916945-18846cb0-5995-435e-ab91-8ee97d8e753c.png">

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/25571626/180917009-a1795c9c-6aac-48c6-bda7-8953fb185cf1.png">

**Comment by karrui** [comment]
closed by #4515
