### ISSUE TITLE
SPCP/MyInfo e-service ID should be validated on form activation

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#4311]
See AngularJS app for implementation details

**Comment by karrui** [comment]
There is no longer any validation after moving to OIDC though. What should be the new behaviour?

**Comment by tshuli** [comment]
we could reuse the current behavior i.e. remind user to check that eserviceId is correct?

**Comment by mantariksh** [comment]
I see, will close this until SPCP gets back to us with a solution
