### ISSUE TITLE
Improve error message when user is offline

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#4316]
When user is offline, error message shown is always "Network Error". To replicate:
1. Go to Network tab and switch "No throttling" to "Offline"
2. Attempt to make any network call e.g. edit form field or request OTP
3. Error message is "Network Error"

We should change this to something more informative: "You may have a problem with your network. Please refresh and try again."

**Comment by tutntut** [comment]
Confirmed that it has changed to: 

There was a problem with your internet connection. Please check your network and try again.
