### ISSUE TITLE
Change copy of form activation to "inactive" instead of "closed"

### ISSUE THREAD

**Issue by tutntut** [opengovsg/FormSG#4334]
<img width="478" alt="Screenshot 2022-07-26 at 1 19 33 PM" src="https://user-images.githubusercontent.com/103998698/180929187-6d6d02b2-0cd5-4eac-b3a0-5ede157b142b.png">

**Comment by mantariksh** [comment]
hold off on this until we decide on what terminology to use

**Comment by mantariksh** [comment]
conclusion was to stick to open/closed
