### ISSUE TITLE
Date field should be a range field

### ISSUE THREAD

**Issue by tutntut** [opengovsg/FormSG#4338]
Pending range implementation and design research

<img width="546" alt="Screenshot 2022-07-26 at 1 33 03 PM" src="https://user-images.githubusercontent.com/103998698/180930789-29f32943-5876-4aa4-9c3a-6ba55f74b340.png">

Ideally, by selecting a date range, the responses should filter to reflect that.

**Comment by mantariksh** [comment]
Closing this first as it's pending design research
