### ISSUE TITLE
"Can't find your secret key" should be underlined in Storage Mode Results

### ISSUE THREAD

**Issue by tutntut** [opengovsg/FormSG#4339]
<img width="171" alt="Screenshot 2022-07-26 at 1 37 35 PM" src="https://user-images.githubusercontent.com/103998698/180931413-90a7a4c3-e82f-4cc7-822b-6fe6a0d9c900.png">

**Comment by timotheeg** [comment]
@pearlyong @karrui  the link behaviour (no decoration at rest, and underline decoration on hover) seems to be intentional. Is this issue valid?

**Comment by timotheeg** [comment]
The design system indicates link should have over-decoration only, but I see some exception, at least one like the email mode details
![image](https://user-images.githubusercontent.com/935223/181212634-d5bf7ae3-a998-428d-8af6-e93f6875f14f.png)

@pearlyong for your comment please 😄  Thanks!

**Comment by pearlyong** [comment]
ah my bad - only inline links (used within sentences/paragraphs) are underlined by default, so can close this!

**Comment by timotheeg** [comment]
Thanks for the clarification @pearlyong ! Closing now
