### ISSUE TITLE
Copy change on logic start page 

### ISSUE THREAD

**Issue by tutntut** [opengovsg/FormSG#4342]
Current:

<img width="601" alt="Screenshot 2022-07-26 at 1 44 50 PM" src="https://user-images.githubusercontent.com/103998698/180932237-1ce43679-7ae9-49bc-a996-083033707ff3.png">

Proposed:
“Show or hide fields depending on user input, or disable form submission for invalid answers. Learn to work with logic”

**Comment by timotheeg** [comment]
Closed by #4396
