### ISSUE TITLE
[2] Localisation broken when changing admin cookie and refreshing

### ISSUE THREAD

**Issue by tutntut** [opengovsg/FormSG#4345]
We should fix the URL routing when refreshing into AngularJS so this will not happen instead of fixing the localisation issue

Steps to replicate:
1. Ensure react variant of the app
2. go to random url, for example form logic tab.
3. remove admin respondent cookie, or set it to angular variant
4. refresh the page. express will render angularjs variant, but localisation json will not load and result in broken text.

<img width="1012" alt="Screenshot 2022-08-22 at 4 36 03 PM" src="https://user-images.githubusercontent.com/22133008/185877412-0e7f89ef-388d-43e4-b6fa-cbb4803eb4c8.png">

**Comment by mantariksh** [comment]
this might have been fixed already? can't replicate anymore

**Comment by karrui** [comment]
Making this clear, we should fix the URL routing when refreshing into AngularJS so this will not happen

**Comment by wanlingt** [comment]
solution: change the cookie expiry to one year (basically a long duration)
