### ISSUE TITLE
Redesign of attachment field's size bar

### ISSUE THREAD

**Issue by tutntut** [opengovsg/FormSG#4346]
<img width="165" alt="Screenshot 2022-07-26 at 1 57 33 PM" src="https://user-images.githubusercontent.com/103998698/180933922-e73a1cb3-467c-4878-9145-a74d6c3d04a2.png">

**Comment by tutntut** [comment]
In angular, a "xx / xx MB" label is used instead, if we were to revert to previous design

**Comment by pearlyong** [comment]
can be same as angular, and label the used storage as Used

**Comment by mantariksh** [comment]
seems to have been fixed
