### ISSUE TITLE
Attachment fields should be disabled once 20mb is reached

### ISSUE THREAD

**Issue by tutntut** [opengovsg/FormSG#4347]

**Comment by mantariksh** [comment]
imo actually this is okay as long as:
1. total attachment size in the form cannot exceed 20MB; and
2. users know why they cannot add any more attachments.

I think the current impl fulfills these 2 conditions as when attempting to create an attachment field which exceeds the limit, focus us redirected to the "Attachment size" dropdown which has an error message.
