### ISSUE TITLE
[5] Attachments greater than 1MB cannot be submitted and returns an error code (in staging)

### ISSUE THREAD

**Issue by tutntut** [opengovsg/FormSG#4348]
413 on React and 200 on Angular

**Comment by justynoh** [comment]
Did some investigation on this and found the following

- Issue occurs on **both react and angular when on staging**, but not in prod, likely indicating that this is more of a bug with our staging setup.
- Response headers on staging returned with cloudflare headers but not express headers, indicating that the request did not even reach the app. 

It might be an issue with our cloudflare settings? I poked around but couldn't find the relevant settings on cloudflare. [This stackoverflow](https://stackoverflow.com/questions/18908426/increasing-client-max-body-size-in-nginx-conf-on-aws-elastic-beanstalk) seems to imply that we can override the `client_max_body_size`, but we don't already do that in production so it must be something else that the difference can be attributed to.

**Comment by wanlingt** [comment]
Tested using `develop` branch on staging, the attachment **can** be submitted

**Comment by wanlingt** [comment]
somehow this is working now... tested the latest [`form-v2/develop` branch on `staging-alt`](https://github.com/opengovsg/FormSG/actions/runs/2859205418), for both email and storage mode forms

**Comment by karrui** [comment]
on react too? @wanlingt

**Comment by wanlingt** [comment]
> on react too? @wanlingt

yup react and angular

**Comment by karrui** [comment]
ya works for me too. can close i guess :P

**Comment by karrui** [comment]
Happening again

**Comment by justynoh** [comment]
Y = uploadable
X = not uploadable

????

```
App ver / Env | staging | staging-alt
------------- | ------- | -----------
develop       |    X    |      ?
v2/angular    |    X    |      Y
v2/react      |    X    |      Y

**Comment by justynoh** [comment]
tried, coudn't figure out why. should we even bother?

**Comment by mantariksh** [comment]
- make sure to test this in production when it's 0% rollout
- wait for AWS to get back to us, see how easy to fix
- if not easy (e.g. if need to change .ebextensions), can wait until after React
- for future QA, QA on staging-alt

**Comment by amitogp** [comment]
It will be tested in react 0% rollout QA
