### ISSUE TITLE
[4] Storage mode responses cannot be downloaded on React

### ISSUE THREAD

**Issue by tutntut** [opengovsg/FormSG#4349]

**Comment by mantariksh** [comment]
Download errors (e.g. only 13/15 decrypted) + cannot decrypt responses with Singpass logins

**Comment by tshuli** [comment]
seems that this is no longer an issue from yesterday's QA? @mantariksh

**Comment by mantariksh** [comment]
@tshuli I still can't decrypt Singpass form responses, could you double check?

**Comment by tshuli** [comment]
Closed by https://github.com/opengovsg/FormSG/pull/4888
