### ISSUE TITLE
Tooltips and examples missing in active / new logic component

### ISSUE THREAD

**Issue by justynoh** [opengovsg/FormSG#4351]
As we have them in angular

<img width="905" alt="image" src="https://user-images.githubusercontent.com/25571626/180959586-a442523f-e1f2-453a-aeb6-14834500eb51.png">

**Comment by tohhengxing** [comment]
Hi @justynoh , may i work on this if this isn't an urgent task? I'll probably submit a PR during the weekends when I am free!

**Comment by justynoh** [comment]
Hi @tohhengxing! We'll discuss the design for this and keep you updated on whether this issue is still necessary, given that the react app has most of the info already. Thanks :)

**Comment by justynoh** [comment]
Hi @tohhengxing! Thanks for waiting, after discussion we don't think these are necessary given that the language used in the logic builder for react is much clearer than for Angular, so we'll close this as unplanned :)
