### ISSUE TITLE
Attachment size graphic is not clear when attachment size is exceeded

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#4353]
The whole bar is yellow which doesn't tell the user anything, and the vertical grey line is hidden by the bar.

<img width="529" alt="Screenshot 2022-07-26 at 6 31 41 PM" src="https://user-images.githubusercontent.com/29480346/180985800-9f8fa0b1-7229-44b3-b746-86abb9801e63.png">

**Comment by karrui** [comment]
what should the fix be? might need new design then. @pearlyong

**Comment by pearlyong** [comment]
same as angular for now, fleshed out the [different cases](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=1375%3A26) (default, used, exceeded)
