### ISSUE TITLE
Copy update for Share infobox

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#4356]
**Pending final decision on form activation terminology: open/closed, activate/deactivate, pubic/private**

Current:

This form is currently closed to new responses. \[Activate your form\]\(settings URL\) to allow new responses.

New:

This form is currently closed to new responses. Activate your form under \[Settings\]\(settings URL\) to allow new responses.

**Comment by justynoh** [comment]
complete in ^ except form activation terminology discussion

**Comment by justynoh** [comment]
Since we decided on open/close, this is complete!
