### ISSUE TITLE
Start page editing hover state

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#4361]
Hover state for start page in builder should show that it's clickable

See also #4277

**Comment by pearlyong** [comment]
hover and active states [here](https://www.figma.com/file/u00dlQLsaQfvqv6ot5ZrJZ/Form-Design-System?node-id=2153%3A3956)

**Comment by justynoh** [comment]
Should the form instructions also have a hover state in the builder?

**Comment by pearlyong** [comment]
discussed already - Instructions should behave like a Field, so expected behaviour and [design](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=10614%3A119039) here:
- User should be able to click on Instructions
- Design tab opens and focuses on Instructions field
