### ISSUE TITLE
Answers for MyInfo fields in builder should not be editable

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#4362]
e.g. "PHUA CHU KANG" for Name should not be editable, to more easily differentiate MyInfo fields from regular fields

**Comment by justynoh** [comment]
Also, MyInfo fields in the builder should be labelled as such (#4441 )

<img width="949" alt="image" src="https://user-images.githubusercontent.com/25571626/182078621-452b26eb-b681-4333-ac09-73861d4e9c6d.png">

**Comment by justynoh** [comment]
Seems like there was a [discussion on this](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3?node-id=6437:100944#214680337) before...

**Comment by wanlingt** [comment]
> Seems like there was a [discussion on this](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3?node-id=6437:100944#214680337) before...

discussion has been resolved, refer to the figma discussion link for more details

**Comment by wanlingt** [comment]
Closing this issue because we decided to leave myInfo fields in the builder editable. The reason this issue was raised was to easily differentiate MyInfo fields from regular fields, which has been [solved by labelling MyInfo fields](https://github.com/opengovsg/FormSG/pull/4538)
