### ISSUE TITLE
Radio button error state styling is inconsistent with rest of app

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#4380]
Should be in line with "Other" text input
<img width="300" alt="Screenshot 2022-07-26 at 11 53 05 PM" src="https://user-images.githubusercontent.com/29480346/181052532-cc351cc6-e062-41c7-ac53-8d9307c03328.png">

**Comment by justynoh** [comment]
Isit hahaha

<img width="320" alt="image" src="https://user-images.githubusercontent.com/25571626/181692636-01fc1b53-7316-427f-b396-0df624cef6cf.png">

**Comment by pearlyong** [comment]
there are two types!
1. If Field is required and user has not selected any, then can align with start of question like above
2. If user selected Other but has not entered any text, then it should align with Other input

**Comment by pearlyong** [comment]
also, the checkbox should always be blue!

**Comment by justynoh** [comment]
current implementation is correct :)
