### ISSUE TITLE
Review calendar usability on mobile

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#44]
Review if calendar usability is fine on mobile. If ok, can close

--- 

#2078 is done, but mobile view might not be as optimised. Understand mobile design is here (https://zpl.io/blYnMXD), but it seems a bit squeezy for fat fingers, especially on an iphone 7 screen. 

Circles are cut off, might want to fix this first (update from @jonathangohjy that circles are no longer cut off)

![image](https://user-images.githubusercontent.com/4787315/86331610-ea87f780-bc7b-11ea-9721-ccfa183b89d9.png)

**Comment by jonathangohjy** [comment]
Circles aren't cut on the design shown on zeplin, is it an issue with front-end?

**Comment by syan-syan** [comment]
added to ux issues doc and closing
