### ISSUE TITLE
MyInfo fields in the builder should be labelled

### ISSUE THREAD

**Issue by justynoh** [opengovsg/FormSG#4441]
As they are in angular

<img width="949" alt="image" src="https://user-images.githubusercontent.com/25571626/182078757-23bbca25-2196-4fa0-acca-f4170253c0fa.png">

**Comment by pearlyong** [comment]
updated [here](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=6437%3A100944)

**Comment by wanlingt** [comment]
^ oops sorry, realise there are still unresolved questions about the design
