### ISSUE TITLE
Display hidden fields differently in builder

### ISSUE THREAD

**Issue by justynoh** [opengovsg/FormSG#4442]
In Angular, any field initially hidden by logic is shown in grey. We should replicate this behavior in react.

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/25571626/182079196-ec1b090b-b2d9-46a9-b220-53024532acf3.png">
<img width="965" alt="image" src="https://user-images.githubusercontent.com/25571626/182079231-de50f065-858d-4542-bcbe-13a3e40520e6.png">

**Comment by pearlyong** [comment]
updated [here](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=11333%3A134852) - 30% opacity

**Comment by justynoh** [comment]
should we also have the corresponding message "This field will be hidden by default." somewhere in the design? @pearlyong 

<img width="999" alt="image" src="https://user-images.githubusercontent.com/25571626/182545697-3fa53772-a81d-451f-854b-66474e18ff25.png">

**Comment by pearlyong** [comment]
updated design [here](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=11458%3A125095) to include tooltip on hover. also changed copy slightly to 'This field is hidden by logic' fyi @mantariksh

**Comment by mantariksh** [comment]
suggest "This field may be hidden by your form logic"
