### ISSUE TITLE
Mobile OTP verification should be disabled if user clicks out of modal without understanding

### ISSUE THREAD

**Issue by justynoh** [opengovsg/FormSG#4446]
**Describe the bug**
The Verified SMS Billing modal allows users to click out without clicking "Yes, I understand". We should disable OTP verification if they did not click on the button (i.e. clicked outside the modal, or clicked on the X).

https://user-images.githubusercontent.com/25571626/182085265-523885e4-3b0c-465f-8ad7-28ba952eb08c.mov

**Comment by karrui** [comment]
closed by #4513
