### ISSUE TITLE
[React] Submission success page should not show sections and instructions

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#4453]
Seems to be introduced in #4155, but there are few regressions in the way the app handles the rendering of various public form page states.

We should only show the form end page without other public form components such as sections and instructions. 

![Screenshot 2022-08-01 at 6 20 44 PM](https://user-images.githubusercontent.com/22133008/182128331-bd207dde-0b00-4ad5-a4f6-8dd6e99b63da.png)

Also related to #4443

**Comment by timotheeg** [comment]
Done in #4455 4455
