### ISSUE TITLE
Long form titles should be wrapped

### ISSUE THREAD

**Issue by wanlingt** [opengovsg/FormSG#4472]
**Describe the bug**
Admin: Long titles cover the builder header
Public form: Long titles are truncated

**Expected behavior**
Form title should be wrapped

**Screenshots**
Admin
![image](https://user-images.githubusercontent.com/56983748/182512623-b33f21e8-827d-4f6c-abe2-aa4da9fe1835.png)

Public form
![image](https://user-images.githubusercontent.com/56983748/182746879-e052140e-47e8-41f2-8d0c-10b5113fb464.png)

**Comment by karrui** [comment]
@wanlingt are you sure about this design? mignt want to enable wrap instead. Check with design?

**Comment by wanlingt** [comment]
> @wanlingt are you sure about this design? mignt want to enable wrap instead. Check with design?

okie messaged pearly! @pearlyong for reference

**Comment by wanlingt** [comment]
clarified with @pearlyong , titles should be wrapped

**Comment by karrui** [comment]
have you already picked this up? @wanlingt if not assign me i'll do it

**Comment by wanlingt** [comment]
> have you already picked this up? @wanlingt if not assign me i'll do it

not yet; just assigned TY

**Comment by karrui** [comment]
closed by #4517
