### ISSUE TITLE
[React] Forms with empty form fields show a `0` text

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#4473]
hehe

<img width="918" alt="Screenshot 2022-08-03 at 10 44 49 AM" src="https://user-images.githubusercontent.com/22133008/182513058-f01bd027-a72d-4104-9700-38fc012d5424.png">

**Comment by tohhengxing** [comment]
@karrui so sorry this is my fault! i have pushed a bug fix for the bug fix..

**Comment by karrui** [comment]
> @karrui so sorry this is my fault! i have pushed a bug fix for the bug fix..

Haha don't worry about it!
