### ISSUE TITLE
[React bug] jiggling vibrating form builder form when moving between share and preview buttons

### ISSUE THREAD

**Issue by tohhengxing** [opengovsg/FormSG#4474]
**Describe the bug**
UI shifts when cursor moves between preview form and share form at builder. probably because of the scrollbar overflow property being enabled and disabled

**To Reproduce**
<details>
<summary> watch the video </summary>

https://user-images.githubusercontent.com/102740235/182519547-859781c0-7b80-40d3-9abd-27b4cf4e7c7f.mp4
</details>

**Expected behavior**
probably should not jiggle or wiggle

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser chrome
 - Version 103

**Comment by mantariksh** [comment]
can't replicate jiggling, wiggling nor vibrating. suspect this has been solved.
