### ISSUE TITLE
[0.5] Link to form guide in form builder

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#4478]
Current form guide button is not very discoverable as it is on the dashboard rather than the builder, even though users are likely to encounter more issues on the builder.

**Comment by mantariksh** [comment]
pending design

**Comment by justynoh** [comment]
@pearlyong

**Comment by pearlyong** [comment]
can place help button on the side nav. can see [here](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=11333%3A134780) for example!
