### ISSUE TITLE
Headers hidden by logic still show up in section sidebar

### ISSUE THREAD

**Issue by justynoh** [opengovsg/FormSG#4506]
Create a form with a header hidden by logic

<img width="575" alt="image" src="https://user-images.githubusercontent.com/25571626/182987473-9f71f2b4-d076-43c0-a1be-9c35b0e8f063.png">

Go to form, header still shows up in sidebar

<img width="1657" alt="image" src="https://user-images.githubusercontent.com/25571626/182987525-177f6f44-053b-4b4b-bccf-10c070161dfd.png">

Clicking on the header link does nothing. Only when the header is visible, clicking on the header link brings the window to the header.

<img width="1659" alt="image" src="https://user-images.githubusercontent.com/25571626/182987635-9e5c6eb0-433e-4cc6-a65c-e1a0a61bb355.png">

Should the header show up at all? Or should it be represented in the sidebar, in some other way (maybe as "Header _(hidden)_"?)? Tagging @pearlyong for design input.

Eng wise should not be too difficult - we have a function that creates the section refs and a function that determines the visible field IDs. We can just filter the section IDs with the visible IDs to determine which are visible and which are not in the sidebar.

**Comment by mantariksh** [comment]
I think don't show at all. The idea of form logic is to only show fields relevant to the form respondent. If they see it in the sidebar but they can't access it, they won't know what to do with that info, and they might think there's a section of the form they need to fill but they cannot access it
