### ISSUE TITLE
Form width is inconsistent

### ISSUE THREAD

**Issue by wanlingt** [opengovsg/FormSG#4507]
**Describe the bug**
The width of forms without headers/instructions in preview mode is smaller than it should be

**To Reproduce**
1. Open up a form (without headers/instructions) in preview mode
2. Open up the same form in public mode
4. Preview mode form appears narrower

**Expected behavior**
The form width should be consistent

**Screenshots**
Preview
<img width="1620" alt="image" src="https://user-images.githubusercontent.com/56983748/182997620-980aa86d-b1d6-4abc-871c-b4bb29b9e581.png">

Public
<img width="1620" alt="image" src="https://user-images.githubusercontent.com/56983748/182997662-71674933-f6da-456d-8263-8048f40809e4.png">

**Additional context**
The public form might have a wider width due to the React announcement banner. Have to check whether the same problem exists on the public form if the banner is removed

**Comment by karrui** [comment]
i wonder if this is fixed by #4451

**Comment by karrui** [comment]
checked, closed by #4451
