### ISSUE TITLE
window does not focus on admin navbar upon loading workspaces page

### ISSUE THREAD

**Issue by wanlingt** [opengovsg/FormSG#4535]
**Describe the bug**
Upon logging in, the window focuses on the workspaces page and the admin navbar is not displayed

**To Reproduce**
1. Log in
2. Observe that window does not start from top of page

**Expected behavior**
<img width="1576" alt="image" src="https://user-images.githubusercontent.com/56983748/183800288-40875753-f023-4acc-a5dc-08b061569520.png">

**Screenshots**
Upon logging in:

<img width="1620" alt="image" src="https://user-images.githubusercontent.com/56983748/183800237-748d95db-a486-4b95-a349-e7c7fb462080.png">

**Comment by wanlingt** [comment]
creds to @siddarth2824

**Comment by karrui** [comment]
should be fixed by #4537
