### ISSUE TITLE
Update env vars in AWS before prod rollout

### ISSUE THREAD

**Issue by wanlingt** [opengovsg/FormSG#4587]
New env vars which will be used for the React rollout
`REACT_MIGRATION_ANGULAR_END_DATE` - last date that angularJS will be available
`REACT_MIGRATION_ADMIN_ROLLOUT` - between 0 and 100
`REACT_MIGRATION_RESP_ROLLOUT_EMAIL` - between 0 and 100
`REACT_MIGRATION_RESP_ROLLOUT_STORAGE` - between 0 and 100
`REACT_TO_ANGULAR_FEEDBACK_FORM_ID` - form Id for bug report feedback form

Github secrets
`GA_TRACKING_ID` - for GA4

**Comment by mantariksh** [comment]
we should fold this into a checklist of what we need to do on the day before / day of rollout
