### ISSUE TITLE
Make response ID more discoverable on end page

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#4593]
Some form admins tell their respondent to take note of the response ID for record-keeping. The response ID used to be visible by default on the end page. However, in React it is hidden under an accordion which is not very obvious.

The rationale for hiding under an accordion is to make the end page less busy. We can also achieve this by removing the form title and timestamp, and just including "Response ID: abcdef" (not hidden under accordion).

**Comment by pearlyong** [comment]
updated design [here](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=8129%3A115758)
