### ISSUE TITLE
[3] signed in ID should show up on authed public form header on submission end page

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#4597]
Currently does not

![Screenshot 2022-08-17 at 1 58 57 PM](https://user-images.githubusercontent.com/22133008/185045561-4ae079f3-87cf-4bf6-a4df-6c3a7450960e.png)

**Comment by pearlyong** [comment]
[figma screens](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=12553%3A126166) - 4 variations
- Agency logo, Singpass
- Agency logo, no Singpass
- No logo, Singpass
- No logo, no Singpass

**Comment by karrui** [comment]
closed by #4698
