### ISSUE TITLE
[1] Form logic behaves wrongly for number/decimal

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#4617]
For form logic, fields shown by default are wrong if the IF condition is for number or decimal fields is “number/decimal field is less than or equals to”. E.g. if I add a condition saying “If Number is less than or equals to 2, then show Image”, then Image is visible by default before I fill the Number field. This shouldn’t be the case - the Image field should be hidden by default.

**Comment by wanlingt** [comment]
- Hidden field is visible even after deleting the input
- Multiple hidden fields linked to different number/decimal field conditions: ALL hidden fields are visible even if only one number field condition is fulfilled
