### ISSUE TITLE
Tooltip for form items

### ISSUE THREAD

**Issue by qin-guan** [opengovsg/FormSG#4620]
**Describe the bug**
Tooltips are missing in form items when editing

**To Reproduce**
1. Create a form
2. Add a field
3. Hover over the duplicate/delete buttons 

**Expected behavior**
Tooltip should show on hover

**Screenshots**
<img width="144" alt="image" src="https://user-images.githubusercontent.com/10321883/185886244-0d6bd835-49c1-4891-a19a-c12bfbd4df87.png">

**Comment by mantariksh** [comment]
Copy:

Duplicate field
Delete field
