### ISSUE TITLE
[0.5] Fix padding between buttons on Log in page

### ISSUE THREAD

**Issue by pearlyong** [opengovsg/FormSG#4631]
Login buttons
- For Resend OTP, it’s 16px gap in between
- For Have a question, since it’s a link and has no padding, it’s 24px gap
- Can see [figma](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=4139%3A72550) also

<img width="198" alt="Screenshot 2022-08-22 at 5 23 23 PM" src="https://user-images.githubusercontent.com/28617936/185887338-96b20a2f-5c46-4761-ba59-01b3ea154d82.png">

**Comment by wanlingt** [comment]
@pearlyong in figma the padding is inconsistent - 32 / 40px for resend OTP, and 24 / 40px for Have a question in different screens. I've followed your instructions in this issue for now (16px for Resend OTP, 24px for Have a question), but let me know if that changes

**Comment by pearlyong** [comment]
yes that's correct! (16px for Resend OTP, 24px for Have a question)
i've updated figma to reflect that
