### ISSUE TITLE
[5] MyInfo logins redirect to angular before react, causing prefill data to be lost

### ISSUE THREAD

**Issue by justynoh** [opengovsg/FormSG#4639]
Logging in with MyInfo with MockPass redirects back to the login screen, not the prefilled form. After preliminary investigation, something to do with admin and respondent cookies and redirecting to angular form before react.

<img width="366" alt="image" src="https://user-images.githubusercontent.com/25571626/185887796-d81cbdf6-aa02-4c6f-87e6-5ec181162623.png">
<img width="625" alt="image" src="https://user-images.githubusercontent.com/25571626/185888094-27283b36-b666-4dba-af82-1dd37adf44aa.png">

`v2-respondent-ui` is `angular` even though the `v2-admin-ui` is `react`.

**Comment by pearlyong** [comment]
Can't QA - 404 error when trying to sign in with Mockpass
