### ISSUE TITLE
[0.5] Excess padding in footer on 404 pages

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#4643]
Possibly other pages too, double check>

![image3](https://user-images.githubusercontent.com/22133008/185888566-135391bb-911f-4197-9704-5d20d5276f8c.png)

**Comment by karrui** [comment]
cannot replicate anymore. closing

**Comment by karrui** [comment]
nvm, happens on specific viewport size

**Comment by wanlingt** [comment]
<img width="870" alt="image" src="https://user-images.githubusercontent.com/56983748/192203250-da84405f-4eff-4297-87f1-33a631e52602.png">

oops

(left padding for footer)
