### ISSUE TITLE
[0.5] Delete field modal copy change

### ISSUE THREAD

**Issue by justynoh** [opengovsg/FormSG#4644]
Delete field modal should display question titles rather than the field type (more relevant with MyInfo fields, where users associate fields with their intended content rather than datatype)
Fix for rollout: match Form Deletion modal. 

Modal title is just "Delete field"
Show field title in modal content with icon of field type and name of field (where form icon and form name are in the delete form modal)

<img width="611" alt="image" src="https://user-images.githubusercontent.com/25571626/185888447-525ce8c4-6c90-4aa7-8ade-066bd91e1a7b.png">

**Comment by mantariksh** [comment]
Combining with #4627 - show different copy if it's not too much effort to check whether the field is involved with logic (shouldn't be).

New copy for fields involved in logic:
This field is used in your form logic, so deleting it may cause your logic to stop working correctly. Are you sure you want to proceed?

@pearlyong thoughts? a bit long but I felt "Deleting this field may cause your logic to stop working" is a bit unclear by itself as I might interpret it as a generic warning when deleting any field, so I thought it's impt to make it clear that the field is actually used in logic

**Comment by pearlyong** [comment]
**Delete field**
Are you sure you want to delete this field? This action can’t be undone.

**Delete field used in Logic**
This field is used in your form logic, so deleting it may cause your logic to stop working correctly. Are you sure you want to delete this field?
(i changed it from Do you want to proceed, to make it a bit clearer and not as cold!) lmk if ok

[figma here](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=11933%3A126698)
