### ISSUE TITLE
[2] Navigating to billing then refreshing results in 400 error

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#4647]
Navigating to billing then refreshing results in 400 error due to conflicting routes in server and client

Should also check for conflicting routes for entire client and server

**Comment by mantariksh** [comment]
just checked datadog, there haven't been any requests to the `GET /billing` endpoint in the past week so we can deprecate that endpoint. but we should still check that there are no other conflicting routes.

**Comment by karrui** [comment]
> just checked datadog, there haven't been any requests to the `GET /billing` endpoint in the past week so we can deprecate that endpoint. but we should still check that there are no other conflicting routes.

Added doc on endpoints in Notion. Will proceed to remove unused routes.

**Comment by karrui** [comment]
This will be fixed when `develop` is next merged into `form-v2/develop` (and when #4806 is merged into `develop`).

**Comment by karrui** [comment]
closed by #4806
