### ISSUE TITLE
[2] Unable to edit existing number or select other countries in Emergency Contact modal

### ISSUE THREAD

**Issue by justynoh** [opengovsg/FormSG#4651]
Can’t actually select other countries in the mobile field even though it’s presented as an option

**Comment by tshuli** [comment]
Could you add more details to reproduce? Seems fine when I tried it:

<img width="554" alt="Screenshot 2022-08-23 at 8 43 47 AM" src="https://user-images.githubusercontent.com/63710093/186043870-36a96d30-7ae6-42bd-a121-54b84c830646.png">

**Comment by mantariksh** [comment]
it's also behaving weirdly for me - when I try to backspace, it autopopulates my phone number again
