### ISSUE TITLE
Leading 0s should not be allowed in decimal fields

### ISSUE THREAD

**Issue by wanlingt** [opengovsg/FormSG#4652]
**Describe the bug**
Decimal fields with leading 0s can sometimes be submitted. Decimal fields should not allow leading 0s, only number fields should. 

![unnamed](https://user-images.githubusercontent.com/56983748/185894759-7465d12d-10ba-4118-9f97-daf17885a64e.gif)

**Comment by wanlingt** [comment]
somewhat related to #4640

**Comment by mantariksh** [comment]
@wanlingt this is the same as #4640 right? feel free to close this if so

**Comment by wanlingt** [comment]
> @wanlingt this is the same as #4640 right? feel free to close this if so

hm the problem is slightly different, #4640 is about the error message while this one concerns buggy submission. but you're right both will be solved by including the frontend validation. Will close this!
