### ISSUE TITLE
Lengthy form title warnings

### ISSUE THREAD

**Issue by justynoh** [opengovsg/FormSG#4653]
In angular, >40 characters shows warning that a shorter form title is advisable. This is missing in react.

**Comment by karrui** [comment]
<img width="773" alt="Screenshot 2022-10-26 at 2 53 53 PM" src="https://user-images.githubusercontent.com/22133008/197955516-80757592-af1e-41b1-970b-3cc40cd09525.png">

Already there. Marked as unneeded
