### ISSUE TITLE
Remove Twilio credentials button looks like an error message

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#4658]
![image44](https://user-images.githubusercontent.com/22133008/185896015-1b24d803-fafc-4ad1-90b8-52363692692c.png)

**Comment by pearlyong** [comment]
supposed to be danger button, [figma](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=5177%3A102162)
