### ISSUE TITLE
[4] Drag and drop with trackpad is wonky and makes UI wonky

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#4690]
To replicate:
1. Climb down from your fancy developer ivory tower and use your trackpad instead of your mouse
2. Go to the form builder and start dragging a field into the form (don't drop it yet)
3. **While holding down the trackpad to drag**, use two fingers to scroll up and down the form
4. Observe that drag and drop positioning gets messed up
5. Also form fields start blending into each other in the UI:

<img width="1792" alt="Screenshot 2022-08-26 at 8 09 19 AM" src="https://user-images.githubusercontent.com/29480346/186790118-8835b2f7-8abd-4dd5-8add-0c994464dd31.png">

**Comment by karrui** [comment]
easy fix: disable scrolling when drag is in progress. this is what many dnd libraries do exactly to "solve" this problem.

**Comment by karrui** [comment]
oh but drag scroll is broken, might be due to #4451

**Comment by karrui** [comment]
Not needed, found an easy fix. It was actually a regression
