### ISSUE TITLE
Refreshing form causes html title of form to change to "FormSG"

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#47]
Steps to reproduce:
1. Go to any form (or this test form created for this issue https://form.gov.sg/5ebe2d79b561af00110ea58b)
2. Look at the tab title: Should be "(debug) Test form" or whatever the form title is.
![Screenshot 2020-05-15 at 1 52 40 PM](https://user-images.githubusercontent.com/22133008/82016317-59e95e00-96b3-11ea-94ac-31ac629a63df.png)

3. Refresh the form
4. Form title changes to generic "FormSG"
![Screenshot 2020-05-15 at 1 51 29 PM](https://user-images.githubusercontent.com/22133008/82016248-2eff0a00-96b3-11ea-9d96-b84fd57b2577.png)

Expected behaviour:
The title displayed in the tab should remain as the form title regardless of refresh

Speculation:
This is probably due to the redirect from the non hashbanged url https://form.gov.sg/5ebe2d79b561af00110ea58b to the hashbanged version https://form.gov.sg/#!/5ebe2d79b561af00110ea58b

**Comment by tohhengxing** [comment]
hi @syan-syan can i be assigned this? I have fixed it and can submit a PR if given the go ahead.
