### ISSUE TITLE
[0.5] Landing page updates - copy, modify stats endpoint

### ISSUE THREAD

**Issue by justynoh** [opengovsg/FormSG#4709]
1. Landing page “Build secure government forms in minutes.” should not have period
2. Landing page image “Staff Travel Declarati\nons 2021” i thought we are changing the image
3. ~OGP Products modal~ (post rollout)

Passing on to PM/Design

**Comment by pearlyong** [comment]
updated copy and graphics/animations for [landing page](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=8422%3A116194). **please let me know if the jsons do not work!**

- almost all blocks have updated copy
- hero animation: animation-hero.json
- no onboarding animation: animation-typing.json
- storage/email mode animation: animation-mode.json

[JSON assets here
](https://drive.google.com/drive/folders/1aRAAXMIdi7XJPBN5zTifD5TyfxmKxnXP?usp=sharing)

**Comment by pearlyong** [comment]
failed QA 26/09 but i think it's because staging-alt doesn't have the latest changes yet

**Comment by wanlingt** [comment]
> failed QA 26/09 but i think it's because staging-alt doesn't have the latest changes yet

you should be able to see the changes now!
