### ISSUE TITLE
[2] Table field - cannot add rows in public form

### ISSUE THREAD

**Issue by wanlingt** [opengovsg/FormSG#4717]
Can add rows in admin preview, cannot add in public form. 
To replicate:
Click add another row - ok
Click again - error required field (not supposed to show here)
Click again - goes to an empty page

**Comment by wanlingt** [comment]
@pearlyong could you help to add the exact steps to replicate?

**Comment by pearlyong** [comment]
**GSIB issue**
To replicate:
- As an admin, add a Table field
- Select 'Allow respondents to add more rows'
- Set Maximum rows allowed to 5 (5 is arbitrary)
- Try adding more rows in Admin builder preview, it should work fine
- Go to public form view and add more rows
- If you add 1 row, it's ok
- If you add another row, there'll be an inline error 'This field is required' (this error is not supposed to appear now)
- If you add one more, the page will go blank
