### ISSUE TITLE
[1] [mobile] Individual responses page is very wonky

### ISSUE THREAD

**Issue by justynoh** [opengovsg/FormSG#4748]
<img width="430" alt="image" src="https://user-images.githubusercontent.com/25571626/187178945-cf03b1f0-cc39-48af-b431-e41f323945d7.png">

**Comment by wenhaogoh** [comment]
Failed QA:
- Components did not stack properly on iPhone 12 iOS Safari
- Large padding when response table is scrolled all the way to the right

![IMAGE 2022-09-26 14:46:38](https://user-images.githubusercontent.com/52305097/192210652-ea10d2b2-4849-4f8b-9ece-2fcefae32859.jpg)
