### ISSUE TITLE
Image field design update

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#4749]
Image box layout is updated, see [correct padding](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=2580%3A1447)

**Comment by justynoh** [comment]
seems correct currently. can check what was this about? maybe it's already fixed

**Comment by karrui** [comment]
If padding seems correct then it should already be fixed. 

I cleaned up the padding in #4525 I think
