### ISSUE TITLE
[3] Design tab custom logo cannot be added on GSIB

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#4759]
Logo seems to be successfully uploaded, but attempting to save changes results in error message: there was a problem with you internet connection

**Comment by wanlingt** [comment]
@justynoh and I investigated, it's to do with SIS policy and the staging site. Angular on staging has the same issue. No problems with angular prod.

![issue-4759](https://user-images.githubusercontent.com/56983748/189612264-856b71c0-80f4-4f28-a663-99f5325abd61.PNG)

**Comment by wanlingt** [comment]
@mantariksh I've closed this for now, but do we want to look into whitelisting it on SIS? Not sure how that works
