### ISSUE TITLE
Headers are not visually related to content in individual response view

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#4760]
In AngularJS storage mode individual response view, the header is clearly linked to the fields under it:
<img width="792" alt="Screenshot 2022-08-29 at 6 27 03 PM" src="https://user-images.githubusercontent.com/29480346/187181126-c988941d-400d-4c51-8645-d8574787a7f8.png">

Whereas in React it's not so clear:
<img width="771" alt="Screenshot 2022-08-29 at 6 27 17 PM" src="https://user-images.githubusercontent.com/29480346/187181168-303f51f3-3184-4952-a8c4-7976f16498ea.png">

**Comment by pearlyong** [comment]
can reduce bottom padding for Header so it's closer to the other fields - [see figma here](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=5242%3A101294)
