### ISSUE TITLE
[Design] Collaborator button is difficult to find for several users.

### ISSUE THREAD

**Issue by tutntut** [opengovsg/FormSG#4785]
May need to look into redesign or place in settings

**Comment by amitogp** [comment]
This should be picked sooner so that we can build right habits among users.

**Comment by tutntut** [comment]
In addition, we need to rethink how adding/removing collaborators + "recipients where responses will be sent" in email mode work hand in hand also. It is a common misunderstanding that adding as a collaborator = receive responses. 
@amitogp
