### ISSUE TITLE
Support copy and pasting emails into email recipients tag field

### ISSUE THREAD

**Issue by justynoh** [opengovsg/FormSG#4828]
Currently, pasting a list of comma-separated emails in the email recipients settings and pressing "Enter" will result in the entire list being amalgamated into a single (invalid) tag. We don't support this feature now, but I could imagine situations where admins may want to copy and paste a list of people who they want to add as recipients for multiple forms.

https://user-images.githubusercontent.com/25571626/189051832-8ad98afb-263b-4e7b-871d-fa018f77f9ce.mov

**Comment by mantariksh** [comment]
moving to kanban board to tackle post-rollout

**Comment by karrui** [comment]
Closed by #4833
