### ISSUE TITLE
Implement MyInfo error page

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#4856]
This error state in MyInfo is not designed/implemented in React:

<img width="1128" alt="Screenshot 2022-09-12 at 1 59 07 PM" src="https://user-images.githubusercontent.com/29480346/190043043-1f38facc-5cfb-43d8-832b-b6990a886083.png">

This occurs when there is an error while logging into MyInfo, or if the user does not consent to share their data with FormSG. It appears when the user is redirected back to FormSG after trying (and failing) to log in to Singpass.

We can change the presentation of the error, e.g. it can be a toast instead of a permanent error message. But the form fields should still not be shown (consistent with all authenticated forms before the user is logged in).

**Comment by pearlyong** [comment]
would we be able to know what error it is specifically? i'm thinking of the messaging

**Comment by mantariksh** [comment]
@pearlyong currently nope. based on the current implementation, we just know whether there was an error or not

**Comment by pearlyong** [comment]
ok added a toast error and tweaked copy a little [here](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=12465%3A124745)
