### ISSUE TITLE
Docker port 5000 clash with apple control center

### ISSUE THREAD

**Issue by lovewithmind** [opengovsg/FormSG#4865]
After Mac Os Monterey upgrades the control center in Mac runs on 5000 and 7000. Which causes a port clash with formsg **5000** port in the **docker-compose file for local development**.

Article on the same: https://developer.apple.com/forums/thread/682332

To avoid port clash we can use some other port other than the common port i.e 5000.

This bug can be faced in Monterey and above version of Mac OS

**Comment by lovewithmind** [comment]
HI @timotheeg 
As you managed to merge my PR . Can we close this open issue as well

**Comment by timotheeg** [comment]
Closed by https://github.com/opengovsg/FormSG/pull/4954
