### ISSUE TITLE
[2] Display submission time from server

### ISSUE THREAD

**Issue by timotheeg** [opengovsg/FormSG#4880]
### Context

FormSG displays the submission time in the thank you page. The time is displayed from checking the client clock. Client clock are notoriously unreliable, as they can be off by few seconds or more. 

We have received a question from a form admin who had their form start time at 9am, but saw a form submission at 08:59am, and was wondering whether an error happened.

There was no error, but the client clock was behind by a bit (for whatever reason, accidental or malicious)

### TODO / Suggestion

(from @karrui 💪) We should return the submission time (in UTC) from our server and use that to display on the client success page instead of using client time.

The submission endpoint should return the submission timestamp in ISO format (**with timezone**!), like this:
```javascript
{
    "datetime": "2022-09-15T01:00:00.000+00:00"
}
```
Note that the UTC timezone can also be specified like this:
```javascript
{
    "datetime": "2022-09-15T01:00:00.000Z"
}
```

On the client, a `Date` object can be instantiated from that ISO string representation:
```javascript
const submissionDatetime = new Date("2022-09-15T01:00:00.000+00:00")
```
And the final date+time can be displayed by extracting the required various "bits" of the date and time in local timezone:
```javascript
// if client timezone is Singapore as GMT+8
submissionDatetime.toString() // "Thu Sep 15 2022 09:00:00 GMT+0800 (Singapore Standard Time)"

submissionDatetime.getDate() // 15
submissionDatetime.getHours() // 9
submissionDatetime.getMinutes() // 0
```
It's probably a good idea to use a date-to-string functions to format the final value, rather than doing it by hand. The existing code for the thank you page likely already has that code btw, and hopefully the only change needed will be to supply the Date object coming from the server to it, rather than instantiating a Date object on the client.

**Comment by justynoh** [comment]
Actually should we show the submission time in UTC+8 instead? Sure we'll have a couple of international respondents, but I think it's better to reduce the mental load for the majority of respondents (Singaporeans) rather than give them the headache of having to +8 every time.

**Comment by timotheeg** [comment]
I think KarRui's suggestion is to do exactly that (read suggestion again 😅)

As in, not displaying the UTC timestamp, but **_use_** the UTC timestamp to display the submission datetime in client timezone.
