### ISSUE TITLE
upgrade react app dependencies

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#4889]
Dependencies have not been upgraded (or only upgraded on adhoc instances) since we were all working on gaining parity with AngularJS. Now that React is *almost* complete, we should take a look at upgrading our dependencies.

This is partially triggered by https://github.com/opengovsg/FormSG/pull/4885.

Big ones to upgrade as of my quick glance at the repository:
- [ ] React 18 (blocker for some dependencies due to the new concurrent/double rendering bugs in strict mode)
- [ ] Chakra v2 (blocked by React 18)
- [ ] react-beautiful-dnd (does not work with 18, but there is a drop-in replacement/fork now in https://github.com/hello-pangea/dnd)

The other dependencies should be able to be updated without trouble.

**Comment by darrelhong** [comment]
might want to look into react-scripts as well #4567
