### ISSUE TITLE
[1] Table field maximum rows is required in react when it's optional in angular 

### ISSUE THREAD

**Issue by justynoh** [opengovsg/FormSG#4935]
Expected behaviour: maximum rows is optional
If no max rows specified, then considered as unlimited

<img width="325" alt="image" src="https://user-images.githubusercontent.com/25571626/192224223-fe470605-c0e6-40a8-9383-88a5f427585c.png">

**Comment by wanlingt** [comment]
@karrui checked the schema, all good can go ahead with making max rows optional
