### ISSUE TITLE
[Mobile] Unable to select "Try it here!" button to switch from Angular to React on iOS Safari

### ISSUE THREAD

**Issue by wenhaogoh** [opengovsg/FormSG#4941]
![IMAGE 2022-09-26 16:07:20](https://user-images.githubusercontent.com/52305097/192225582-6a77dc83-831a-4870-8cc8-cbae2d29db76.jpg)

**Comment by wanlingt** [comment]
duplicate of #4939

**Comment by wenhaogoh** [comment]
Duplicate of #4939

**Comment by wenhaogoh** [comment]
Duplicate of #4939
