### ISSUE TITLE
Add change to CSVs to React enhancements

### ISSUE THREAD

**Issue by wanlingt** [opengovsg/FormSG#4970]
See [here](https://github.com/opengovsg/FormSG/pull/4950#issuecomment-1260622425) for context

**Comment by wanlingt** [comment]
@amitogp what changes were you specifically thinking of - add to the what's new page, or the form homepage? will leave it to you and pearly to discuss!

**Comment by amitogp** [comment]
@pearlyong will need your help in understanding how we are showing new react enhancements to users. Then we can decide where to put this enhancement.

**Comment by pearlyong** [comment]
- [Final copy](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=8530%3A118729) for What's new panel
- [Link to Guide](https://go.gov.sg/formsg-guide-faq-security-quote)
