### ISSUE TITLE
Make new form owner email more prominent in the transfer ownership confirmation modal

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#499]
objective is to reduce the probability of typos. this would cause forms to be transferred to an invalid email address, which can only be fixed by intervention from the Form team. we want to minimize this ops workload.

todo: change email address to same red as Yes, Transfer ownership button

opening another ticket for stronger validation as well.

**Comment by pearlyong** [comment]
The email address text colour can be changed to red.
More importantly, there should be inline validation to detect if it's is a valid gov.sg email

**Comment by syan-syan** [comment]
@pearlyong we are working on the technical aspect separately, but it's not trivial because we would have to send a ping to the email to find out if it exists, and we currently don't do anything like that anywhere in the application.
but on presentation front, ok will change email address text colour to red.

**Comment by syan-syan** [comment]
@tshuli can we put this tiny ticket in with next release?

**Comment by tshuli** [comment]
@syan-syan done!
