### ISSUE TITLE
Add thank you page to the sidebar.

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#5014]
For consistency in form creation flow, the thank you page should be made part of sidebar.

Design will confirm the copy and icon and update here: https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=2584%3A106218

**Comment by staceytan1998** [comment]
Icon and design updated! Please refer to this link here: https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=7019%3A109487
