### ISSUE TITLE
Change Design button icon and copy.

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#5015]
Refer to the design here: https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=12890%3A206082

**Comment by staceytan1998** [comment]
Icon and copy updated, also updated the drawer title, can refer here: https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=2278%3A56343
