### ISSUE TITLE
Remove sections from fields and rearrage field icons.

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#5016]
All the fileds inside builder will be part of a single list. i.e. No sections such as 'Field' or 'Page'.

Design link for copy and icons arrangement: https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=2278%3A56352

**Comment by staceytan1998** [comment]
Updated! Can refer to the link above, take note of the arrangement of the fields!
