### ISSUE TITLE
[0.5] Other copy changes based on user tests

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#5017]
Sidebar:

Change Builder button tooltip to 'Add fields'
Change Logic button tooltip to 'Add logic'
Change BUILDER Widget drawer title to 'FIELDS'
Change Header field to 'Heading'

Everything will be updated here:
https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=2278%3A55894

Please take a go ahead by pm/designer before making the changes.

**Comment by staceytan1998** [comment]
Design and copy changes updated! Can refer here: https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=4862%3A103434
