### ISSUE TITLE
Users see a flash of the homepage before the public form loads

### ISSUE THREAD

**Issue by wanlingt** [opengovsg/FormSG#5037]
Instead of the homepage, we should see a loading spinner.

To replicate, 
- set admin rollout to 100%
- set email form rollout to 1%
- make sure your cookies are cleared, load a public email form. the homepage flashes for a split second before the publicc form page loads. both the admin and respondent cookies are set.

**Comment by karrui** [comment]
~~Cannot replicate, is it due to cache? @justynoh~~ nvm replicated on a non-slow 3G mock speed
