### ISSUE TITLE
Change copy for feature tour

### ISSUE THREAD

**Issue by wanlingt** [opengovsg/FormSG#5040]
(Implement this after the thank you page has been completed)

**Comment by staceytan1998** [comment]
Here are the changes to feature tour! Do note that there are changes to the others because the naming changed as well: https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=13016%3A127157

**Comment by justynoh** [comment]
done with thank you page pr because I'm touching that file anyway
