### ISSUE TITLE
International mobile number field validation issue

### ISSUE THREAD

**Issue by justynoh** [opengovsg/FormSG#5060]
“Please enter a valid mobile number” still shows even though it is valid
To replicate
1. Type a wrong number first
2. Then remove characters to match correct characters

<img width="470" alt="image" src="https://user-images.githubusercontent.com/25571626/194281469-b9295115-ad72-4dbc-a06b-086e6432c764.png">

Find Kenneth for more info, issue was kinda flaky.

**Comment by tohhengxing** [comment]
not sure if this can actually be replicated, the invalid number in the picture is actually invalid. Would like more info on this if possible in order to debug...

**Comment by amitogp** [comment]
Let's try to replicate it with a valid phone number.
