### ISSUE TITLE
Paragraph field does not display the content as typed

### ISSUE THREAD

**Issue by justynoh** [opengovsg/FormSG#5061]
<img width="357" alt="image" src="https://user-images.githubusercontent.com/25571626/194281816-2b510b68-02ad-4308-8a25-ffb5b06ab592.png">

This is an issue both with the builder and public form. As compared to angular, which shows the paragraph field contents exactly (even with multiple newlines exactly the same)

**Comment by karrui** [comment]
grrr i thought this was fixed, regression somewhere :(. or is it edge/gsib-only?

**Comment by justynoh** [comment]
the screenshots were on edge and gsib, seems like the same on mac tho



![Image](https://user-images.githubusercontent.com/25571626/194286607-198f6bf0-95e8-47cb-90f9-43bd51335e8e.png)
