### ISSUE TITLE
investigate e2e tests for react

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#5112]
Current e2e tests will soon become useless due to being tailored for AngularJS client. 
To get some semblance of safety during automated dependency updates (and releases), we should set up e2e for the react client.

Should be a heavy undertaking, this issue marks the set up of the e2e framework to be used for react.

suggest using playwright framework (actually already start liow so NO CHOICE I CHOOSE IT)

**Comment by justynoh** [comment]
"suggest" 🤔
