### ISSUE TITLE
write initial e2e tests for react

### ISSUE THREAD

**Issue by karrui** [opengovsg/FormSG#5113]
As a first cut, should be more or less parity with current e2e tests in what they cover. may not need to be that detailed.

- [x] login e2e tests
- [x] form creation
- [x] form duplication
- [x] form field updating
- [x] email mode form filling (and submission)
- [ ] storage mode form filling (and submission)
- [x] auth'd form filling (and submission)
- [ ] storage mode responses downloading

**Comment by justynoh** [comment]
half complete in #5876 , storage mode to be done in a future PR
