### ISSUE TITLE
Investigate inability to send emails in dev environment

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#512]
This makes local development difficult as we cannot receive OTPs.

**Comment by jia1** [comment]
Did this issue get reported because of me...? I asked @karrui if I could use his email address and he said he found the OTP email in Spam. Since my group email does not seem to have a Spam folder, I could not receive the OTP email.

**Comment by mantariksh** [comment]
@jia1 mine doesn't work either. it worked for a while then stopped.

**Comment by mantariksh** [comment]
Closed via #613
