### ISSUE TITLE
Filter by active/inactive forms on dashboard

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#5156]

**Comment by staceytan1998** [comment]
Design here for filter: https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=13410%3A131745 !

**Comment by staceytan1998** [comment]
Design updated for mobile and tablet as well: https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=13526%3A132353 

Note there is a count on the icon button!
