### ISSUE TITLE
bug: forms with 1 text field refreshes on enter

### ISSUE THREAD

**Issue by wenhaogoh** [opengovsg/FormSG#5157]
**Describe the bug**
Forms with only 1 text field refreshes when the user presses the enter button after focusing on the field.

**To Reproduce**
1. Create new form
2. Add short field
3. Click preview/Open form link
4. Select field
5. Enter something (Optional)
6. Press enter
7. The page will refresh and any input will be cleared

**Expected behavior**
The page should not refresh on enter.

**Comment by justynoh** [comment]
bug may not be with only 1 field, could it be if only one text input is rendered?

**Comment by wenhaogoh** [comment]
@justynoh Seems like it, I've updated the issue title and description, thanks!

**Comment by tohhengxing** [comment]
@wenhaogoh What is the desired behaviour supposed to be? 😅

**Comment by wenhaogoh** [comment]
@tohhengxing Updated the description, sorry for the confusion!
