### ISSUE TITLE
[Review] Use-template feature for forms on react

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#5161]

**Comment by amitogp** [comment]
Reasons for prioritizing:
* Users have requested for this features because it helps the new public officers to get an idea of various forms and choose a form that they can use as inspiration.
* Feature parity between angular and react
* /use-template has about 3.5k monthly traffic in angular and is very useful for investigating P1 issues. /template end-point also has 5k traffic. Ref: https://www.notion.so/opengov/1c8ac7b2d000492da30bd6b537887705?v=06bc747bd92f4a009b4f09c29b81acba&p=28cb64f3f42f4c7ca1e0481f05b1cedd&pm=s

Emaples button on the top right of angular can be modified into templates and we can use the existing example forms as templates: 

![Image](https://user-images.githubusercontent.com/107169604/196342846-eb30335f-2434-4621-9cdf-fe98161687d2.png)

The use-template endpoint can also follow the exsiting angular design.


![Image](https://user-images.githubusercontent.com/107169604/196343403-31b81a46-b98b-4ecc-b668-18b67bd9e3fc.png)

**Comment by wanlingt** [comment]
[figma](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=13854%3A135280) (wip)

**Comment by staceytan1998** [comment]
[Link](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=14009%3A131213) to use-template! Added notes to the file as well, but below are the key things to note:

- Share template link will be found in the share modal, similar to angular
- Template preview will be full size unlike current one where its a frame and the background is the examples page
- Flow of share template:
- If admin is not logged into Forms, they will be redirected to login page after clicking on share template link, after logging in they will be redirected to the template
- If admin is logged into Forms, they will be directed to the template
- Template preview bar will be [sticky](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=14009%3A131315) to the top of the browser as the user scrolls through the form
- Included a button to go back to Forms home page from the template page

Changed design for [preview mode](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=14009%3A131279) also!

**Comment by wanlingt** [comment]
expected behaviour:
- user can still click submit but the response doesn't show up in responses (similar to preview mode)
- the new form title is prefixed with 'Template_'

**Comment by timotheeg** [comment]
Task was under-estimated (2 instead of 3), accomplished 2, leaves 1 for next sprint
