### ISSUE TITLE
Replace top navbar Back button with breadcrumb

### ISSUE THREAD

**Issue by pearlyong** [opengovsg/FormSG#5165]
- Users are confusing the Back button with going back to the Builder, when it actually goes back to the Workspace
- Therefore, we're replacing the Back button with a breadcrumb, which will show All forms / Form name so it's clear that clicking on All forms goes back to Workspaces
- In this case, we won't be able to accommodate the Saved at... under breadcrumb, so we are moving it to the right

[figma here](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=11333%3A134780)

**Comment by pearlyong** [comment]
Also moving the Saved at... to the right
[figma here](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=11333%3A134780)

**Comment by staceytan1998** [comment]
Also the Saved at... is moved to the slide out menu in mobile, see [here](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=11420%3A122902)  

All the navbars are [here](https://www.figma.com/file/u00dlQLsaQfvqv6ot5ZrJZ/Form-Design-System?node-id=861%3A24286)
