### ISSUE TITLE
Radio, dropdown duplicate detection not kicking in on focus out/onblur

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#5174]

**Comment by amitogp** [comment]
Radio button and Dropdown, do not detect duplicate options on focus out, and select both options when we select one on the right panel. Detection happens only on clicking create field .

Checkbox also has the same issue but does not do double selection on selecting one.


![Image](https://user-images.githubusercontent.com/107169604/195786644-db1a4701-b5dc-448e-acb3-4a685e98f1be.png)



![Image](https://user-images.githubusercontent.com/107169604/195786680-78bd4e2a-70c6-421c-ba69-5dae04f8335b.png)



![Image](https://user-images.githubusercontent.com/107169604/195786714-11d629df-2028-4de5-b6f3-d178b9e2f690.png)



![Image](https://user-images.githubusercontent.com/107169604/195786751-56b900ac-32ca-471d-9e0c-f125b7a684f9.png)

**Comment by wanlingt** [comment]
"select both options when we select one on the right panel." - this is correct behaviour
we want to detect duplicates on blur, rather than when "create field" is clicked
