### ISSUE TITLE
Find alternatives to recaptcha

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#5183]

**Comment by amitogp** [comment]
Multiple users have complained that recaptcha is very hard to fill and may even lead to user drop off.

**Comment by qin-guan** [comment]
CloudFlare Turnstile is an interesting alternative since they do not prompt for visual challenges. 

They also have a guide for migration from reCAPTCHA https://developers.cloudflare.com/turnstile/get-started/
