### ISSUE TITLE
Add radio buttons for getting categorized feedback from users

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#5185]

**Comment by pearlyong** [comment]
[design here](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=13459%3A131984)

**Comment by wanlingt** [comment]
discussed during sync today: don't submit the feedback form if 'I’m not used to the new FormSG' is selected

**Comment by amitogp** [comment]
@wanlingt this needs a small modification. On clicking "Switch to the original version" for respondent view, the modal has direct focus on the email field instead of the radio button which is the first and the only required field. 

![Image](https://user-images.githubusercontent.com/107169604/198007508-6b83d49a-4544-4ce4-8fa9-2f17ac7a0126.png)

Ideally the focus should be on the radio button, something like this:

![Image](https://user-images.githubusercontent.com/107169604/198007795-e36d17de-99f0-4425-8be8-a2848cbc3682.png)

**Comment by wanlingt** [comment]
> @wanlingt this needs a small modification. On clicking "Switch to the original version" for respondent view, the modal has direct focus on the email field instead of the radio button which is the first and the only required field.

> Ideally the focus should be on the radio button, something like this:


good spot amit! will fix
