### ISSUE TITLE
Add functionality to open forms in new tabs

### ISSUE THREAD

**Issue by wanlingt** [opengovsg/FormSG#5223]
**Describe the solution you'd like**
On the admin's form dashboard page, the user should be able to right click and open the form in a new tab.
can allow middle click (or open in new tab) by changing buttons into links

**Comment by karrui** [comment]
doing it out of scrum on LEARNING FRIDAY where THERE ARE NO RULES

**Comment by wanlingt** [comment]
> doing it out of scrum on LEARNING FRIDAY where THERE ARE NO RULES

#rebel
