### ISSUE TITLE
Weird breakpoint, tabs appearing as mobile on UI when in desktop

### ISSUE THREAD

**Issue by staceytan1998** [opengovsg/FormSG#5243]
RUM session: https://app.datadoghq.com/rum/replay/sessions/359974c8-859d-40fa-a732-1c20e3078a0d?seed=87e935b3-5a90-4a51-b81c-a736a7917c59&ts=1666673714165 

Another RUM session: https://app.datadoghq.com/rum/replay/sessions/2b858ddf-4b74-4877-aa43-a728093f5443?seed=c131329c-3e58-4bab-bef1-362db53a433a&ts=1666666014051 - can see from 4:41 onwards, view suddenly changed to tablet and then back to desktop when he saved

Issue:
- User seems to be using desktop but the tab in the top nav bar is mobile tab
- When user clicks on a field, it doesn't open the drawer
- Drawer behaviour is mobile 
- Happened to Pearly when she tried to replicate the bug and also resulted in form options on home page disappearing, did a hard refresh and it was back to normal after that

**Comment by wanlingt** [comment]
should have been solved by #5250
