### ISSUE TITLE
Use feedback button as a way for respondents to give feedback to admin before form submission

### ISSUE THREAD

**Issue by tutntut** [opengovsg/FormSG#5279]

**Comment by tutntut** [comment]
Before React had the feedback button, we did not have visibility on issues that respondents have.

Furthermore, many of these issues could be affecting their submission of their form (e.g. missing options, attachment size limit, general plea). Unless respondents submit a response successfully, they will not be able to feedback to the admin to make necessary changes.

Additionally, we have already spent the effort to create the feedback button. I believe we can repurpose it for admins and make it optional for them to enable the setting.



![Image](https://user-images.githubusercontent.com/103998698/198957124-14bdbfcf-3d1c-418d-bd39-48b78eab6997.png)

**Comment by tutntut** [comment]
- Require some research on how other forms are doing it

Suggested solution
- Allow respondents to "contact form admin"
- Brings to a page similar to thank you page
- Includes 3 things
  - Email (short answer)
  - Contact (mobile number)
  - Feedback (long answer)
- This information will be displayed under current Results page
- Separate from "feedback" tab
- Naming: Enquiries, Message, issues, concerns etc (to think)

**Comment by staceytan1998** [comment]
[Public form implementation here](https://www.figma.com/file/CMq0CJtawn7NGM7Zdpi8Ti/Form-Design-Master?type=design&node-id=16047-155830&t=QoE2nyNY9IPHGTRa-4)! Just one field for contact, respondents can either enter number or email! 

Pending admin view.
