### ISSUE TITLE
Display overflowing text for dropdown field

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#5281]
Based on a feedback received for this form: https://form.gov.sg/5ca57a54531c010010c61a75
The user is not able to select the program because the options are not completely visible on dropdown.

![Image](https://user-images.githubusercontent.com/107169604/198545644-07490d6b-f294-414e-b328-919bc5202b50.png)

The options were clearly displayed in Angular:
![Image](https://user-images.githubusercontent.com/107169604/198546607-bc024d54-c67f-41ac-a0c7-90e391c87345.png)

**Comment by timotheeg** [comment]
* Engineer work in FormSG
* Update design system in Figma to account for multi-lines
* Update component in design system repo
