### ISSUE TITLE
Adding/Removing Email collaborators should prompt if they want to make amendments to recipient list

### ISSUE THREAD

**Issue by tutntut** [opengovsg/FormSG#5289]
Reference ticket: https://formsg.zendesk.com/agent/tickets/17932

**Comment by tutntut** [comment]
![Image](https://user-images.githubusercontent.com/103998698/198955929-7e1992c3-1950-4e4e-b14e-e532798dcd0a.png)

Adding/removing collaborators don't automatically add/remove them from the setting "emails where responses will be sent". This is an issue because a new to FormSG user would assume that being an editor/viewer means they automatically receive email responses.


![Image](https://user-images.githubusercontent.com/103998698/198956191-dc628c7f-4b49-4b7c-bb47-8bc537ca8f30.png)

Potential solutions:



(1)
- additional column in the "add collaborators" button named "responses"
- toggleable

(2) 
- when users add/remove collaborators, it will prompt them if they want to add/remove emails from the recipient setting

**Comment by tutntut** [comment]
++ consideration for payments

**Comment by FormSG-Ops** [comment]
Some admins will add external organisation recipients so we may need to relook how to display external organisations in the collaborators list. External orgs should not gain access to FormSG.
