### ISSUE TITLE
Stabilize CI tests

### ISSUE THREAD

**Issue by timotheeg** [opengovsg/FormSG#5296]
Many PRs initially fail on failed tests for e2e tests, or backend test. 

The failed tasks need to be rerun and typically eventually succeed. The flakiness of the tests is a big waste of time for everyone.

Stabiize tests that fail frequently (e.g. missing wait in e2e frontend tests?))

**Comment by justynoh** [comment]
Did investigation, but no rectification yet (still investigating)
