### ISSUE TITLE
Form option (Duplicate/Delete) not rendering in some machines

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#5335]
Some computers have not been able to render our form options (Delete, Duplicate, etc):

![Image](https://user-images.githubusercontent.com/107169604/199886479-0342ad42-9b86-48a1-8c7e-82d80059f14b.png)

@karrui has done a call with a user who faced this and and concluded that Mobile UI is rendering somehow and the form options start displaying the moment the user goes to 'inspect element'. 

Solving this issue sooner is crucial to remove the banner sooner.

![Image](https://user-images.githubusercontent.com/107169604/199886875-36e61aad-06a7-4638-a7cd-9e3562db3c56.png)

**Comment by wanlingt** [comment]
I've verified with the user that this issue has already been fixed in #5250
