### ISSUE TITLE
Implement search and filter for form organization

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#5397]

**Comment by amitogp** [comment]
Figma: https://www.figma.com/file/sLYgTbw8tCQe1qmYsz9QE0/Form-Exploration?node-id=6370%3A90332&t=21D6C4Qs1ENExg11-4

**Comment by justynoh** [comment]
https://github.com/opengovsg/FormSG/issues/5407#issuecomment-1321494681
