### ISSUE TITLE
Email domain restriction

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#54]
**Problem**
Some form creators only want their forms to be filled in by their agency. 

**To do**

- [x] Add validation to email field titled 'Restrict email domains'. Use textarea field, placeholder '@example.com, @nextexample.com'

- [x] If 'Restrict email domains' is toggled on, 'Verification' is automatically toggled on. 

- [x] If user tries to toggle 'Verification' off while 'Restrict email domains' is on, show error toaster " 'Verification' must be selected with 'Restrict email domains'."

- [ ] Server-side check when saving email field setting. If 'restrict email domains' is on, 'verification' should also be on.

- [x] (Public form) Error shown when invalid email domain entered 'Not an allowed email domain'. Verify button is also disabled.

- [x] (Email verification flow) To insert: check to see if email is within the restricted email domain list, if not, do not send OTP.

- [x] Copy: Also change 'Verified?' to 'Verification (OTP)'

- [x] (stretch) Pre-fill agencies' email domains in 'Email domain restriction' textarea. should not be possible to modify until toggle is on.

**Comment by syan-syan** [comment]
@pearlyong we're adding this feature on the Email field to restrict the possible email domains that respondents can enter and use to submit. can see the linked PR to see what it looks like. this is something that will be useful for many of our users who are asking for submissions to only be limited to their own agencies for example.

challenge in presenting this feature is this: when Email domain restriction is switched on, Verify via OTP should also be switched on, to make sure that respondents own the emails they are declaring. 

we've discussed options including these below and would benefit from your input:

- Error message when user tries to save change without toggling Verify on also -- We will do this anyway as we need to validate server-side. _The remaining question is should we communicate the need to also toggle on Verify before the user saves changes, and if so how?_
- showing a toaster or modal after Email domain restriction is turned on that tells the user that they must also select Verification in order to set Email domain restriction. If they try to save without, above error message shows. (currently in favour of this as it is the simplest even though it might look a bit crowded)
- hiding Email domain restriction under Verify, unseen until the user toggles Verify. one consideration we discussed is the user might not know that it is under Verify and thus never select it, but might select both if they knew this feature existed.
- disabling Email domain restriction toggle until Verify is turned on, with some user messaging to inform users that they must toggle on Verify before toggling Email domain restriction. In other places, we have comm'ed similar ideas via toaster (Authentication method cannot be changed until form is deactivated), but toaster also looks more crowded in a smaller space.
- Not disabling Email domain restriction toggle, but toggling Verify on automatically when Email domain restriction is toggled on. If the user toggles Verify off subsequently, we show the error message when they save. The downside with automatically toggling Verify on is that this modal informing users of the free tier limit will/should appear after that happens although it is seemingly unprompted by the user: https://app.zeplin.io/project/5b29ffde48eaaf6318d01b05/screen/5eb8e5aa3f2c5e4d08e2c7db. (this modal has not yet been implemented but is going in prob next week's release)

**Comment by syan-syan** [comment]
@jia1 updated mockups showing behaviour https://app.zeplin.io/project/5b29ffde48eaaf6318d01b05/screen/5f51efc4575d1a868cbe0dd9 

additional comments:
- placeholders should be list as we discussed, not comma-delimited run-on
- for the placeholder list, the first item should be taken from the user's login, followed by "@agency.gov.sg" e.g. for mine it would be

@open.gov.sg 
@agency.gov.sg

**Comment by jia1** [comment]
@syan-syan I need access to the Zeplin project. Thank you!
