### ISSUE TITLE
Addressing form organization comments

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#5407]

**Comment by staceytan1998** [comment]
Hey @justynoh , here is the [final design](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=14174%3A145335&t=t1XHen26Fi4pkg8H-4) for the search + filter! 

For desktop, there is a new component created for search [here](https://www.figma.com/file/u00dlQLsaQfvqv6ot5ZrJZ/Form-Design-System?node-id=10966%3A27413&t=mrTgtyWDdTUhhJ9B-4)! It comprises of the search bar and also a new xs size button [here](https://www.figma.com/file/u00dlQLsaQfvqv6ot5ZrJZ/Form-Design-System?node-id=10970%3A27909&t=mrTgtyWDdTUhhJ9B-4)!
