### ISSUE TITLE
Change 'Then Show' fields to new line for each field

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#5425]
The current 'Then show' box is making it harder for users to read or update complex logic. Following screenshots share by a user provides context.

In angular:

![Image](https://user-images.githubusercontent.com/107169604/202914474-3322fbc0-aee7-4102-8380-78c9311882da.png)

In react:

![Image](https://user-images.githubusercontent.com/107169604/202914485-066ee9d9-2019-4827-b438-8244a4d23ee0.png)

@staceytan1998 please update the design according to [this comment](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3?node-id=4953:90732#311295900).

**Comment by staceytan1998** [comment]
Design is [here](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=14219%3A139327&t=tfBkeOOzjAGNJkjh-4)!

**Comment by staceytan1998** [comment]
![Image](https://user-images.githubusercontent.com/99157017/203507167-2c0b8c19-98a7-401a-8da8-49af170a3a7d.png)

Also pointing this out, for Paragraph field it shows up as statement in logic and also has no preview of the content. Think there is an issue for this already but just leaving it here.
