### ISSUE TITLE
Statement and image data do not show up in logic builder

### ISSUE THREAD

**Issue by justynoh** [opengovsg/FormSG#5431]
<img width="704" alt="image" src="https://user-images.githubusercontent.com/25571626/202970019-18c3a5cb-8c14-440d-a06e-6b3b0d317c05.png">

But they do in angular

<img width="697" alt="image" src="https://user-images.githubusercontent.com/25571626/202970140-6f7401fc-85cb-46ee-bae0-f38429c6c410.png">

**Comment by justynoh** [comment]
@staceytan1998 @pearlyong if #5507 fixes this then we can close this! what do you think?

**Comment by staceytan1998** [comment]
statement and image name data will show up when the tags are extended right, if they do then yeah we can close this!

**Comment by justynoh** [comment]
great!
