### ISSUE TITLE
Database flag to control text field prefill

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#548]
Add a boolean flag in the model to control whether a text field can be prefilled with query parameters, which defaults to false. No UI is necessary for the time being.

Any forms that rely on this feature should have their form field state updated in the database before deployment.

**Comment by karrui** [comment]
SInce there may still be old clients without the check (even with the new flag returned from the server), need to be cognisant that some forms will still have "prefillability" even with this change until the clients update
