### ISSUE TITLE
Show 'then show' fields in new lines

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#5495]
![Image](https://user-images.githubusercontent.com/107169604/204692104-d267495f-7b5d-4959-b064-0881458aec39.png)

**Comment by amitogp** [comment]
@staceytan1998 please update the figma link here.

**Comment by justynoh** [comment]
Figma link: [here](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=14219%3A139327&t=tfBkeOOzjAGNJkjh-4)
