### ISSUE TITLE
Logic builder feature parity and enhancements

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#5520]
Issues: 
1. Every field should be shown in a new line in the `then show` box.
2. Image should be denoted with image file name.
3. Statement should be denoted with the content of the paragragh.

![Image](https://user-images.githubusercontent.com/107169604/205587571-9e4822d2-28b0-40dc-890f-68eb89f42d39.png)

@staceytan1998 please add the figma design for engs to pick it up

**Comment by karrui** [comment]
Closed by #5507
