### ISSUE TITLE
Transfer form ownership for encrypt forms

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#56]
Fka https://github.com/datagovsg/formsg/issues/859

**Requirements**
- [x] Check that user email is from whitelisted agency (this check already exists for collaborators
- [x] Check that user email is email of an existing user (update: we have a significant ~5k/15k collaborators that are not existing users) 
- [x] Button when transferring form ownership should say "Transfer" not "Send Invite" 
- [x] Change comment on Editor to be 'Can edit but can't delete forms' (on Storage mode only) 
- [x] Change collaborator modal to full page modal
- [x] When (1) Transfer Ownership is clicked from the Add collaborator field or (2) when choosing dropdown Owner role for another collaborator, another modal appears "Are you sure? You will no longer be the form owner and will lose rights to delete this form. You will still have Editor rights." with 2 options "Yes, transfer" (red button) and "Cancel"
- [x] Two sections 'New collaborators' and 'Existing collaborators', same style as current 'Add collaborators'. Remove existing 'Collaborators' column header. 
- [x] Change copy when trying to downgrade/upgrade existing collaborator: "This user is an existing collaborator. Please edit permissions below."
- [x] Clear pop up options after transfer
- [x] Don't display Owner role in pop up when Editor tries to transfer

Mockups:
https://app.zeplin.io/project/5b29ffde48eaaf6318d01b05/dashboard?seid=5dbbd257edf4a42c0f75715c

**Comment by arshadali172** [comment]
closed by https://github.com/opengovsg/FormSG/pull/111

**Comment by arshadali172** [comment]
related to https://github.com/opengovsg/FormSG/issues/214
