### ISSUE TITLE
[MyInfo 3.] Support MyInfo on Storage mode

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#57]
This is important for migrating users from Email mode to Storage mode.

Technical design https://docs.google.com/document/d/1cHQbKMykTlekkoj4XlwQFTlubNjQC_7TkMzxoc5qqdc/edit#heading=h.199pf2fyqba2

**Comment by liangyuanruo** [comment]
Outdated given our PKCE discussions
