### ISSUE TITLE
Improve OTP identification

### ISSUE THREAD

**Issue by timotheeg** [opengovsg/FormSG#5710]
## Context

Email and SMS OTPs can sometimes be slow to deliver, especially email OTP over government mailboxes, where the email filtering and validation can take time.

Because of that, many user request new OTPs, and when they receive the first email (delayed), they are dismayed to get an error that the OTP did not match. That's because there can only be a single active OTP for a user at a time, and the request for a second one made the first invalid. 

Unfortunately, users have no way of knowing which OTP is active, in relation to the emails and sms-es they are receiving. 

## Proposal: An OTP identification prefix

An identification prefix can be generated when an OTP is requested.  The prefix is sent as part of the email/sms, and will be shown in the submit form as static text, but it is not a user input. 

As in, the OTP will still be a 6-digits code, like `123456`, but the SMS/email contain the code `ABC-123456`, and the text field to enter the OTP shows `ABC-[...]` . That way people will know what OTP they are looking at.

Reference: DBS uses that prefix system in their OTP, see SMS content below:

> Fr DBS: Do not reveal OTP to anyone for your online txn of SGDXX.XX on VISA ending 9999 at Shopee. To approve, use **HTW-191206** within 3 min.

**Comment by LinHuiqing** [comment]
Reopening for the SMS and Email verification fields!

**Comment by foochifa** [comment]
@LinHuiqing Should we close this and open a more specific issue for SMS and Email fields?

**Comment by LinHuiqing** [comment]
Created #5865 and #5866 for respondent-side OTP verification!
