### ISSUE TITLE
Issue with webpack-cli on build

### ISSUE THREAD

**Issue by quantrpeter** [opengovsg/FormSG#5791]
Mac doesn't allow export NODE_OPTIONS=--openssl-legacy-provider

<img width="2080" alt="image" src="https://user-images.githubusercontent.com/50471577/219856046-e2605feb-a016-4183-99d6-3b388cbf2a58.png">

**Comment by darrelhong** [comment]
@quantrpeter looks like an issue with webpack-cli, you might be using a different version of webpack-cli. would re-install node_modules and try again.

**Comment by quantrpeter** [comment]
i changed to windows, one more problem, i have installed VS 2022 community and updated all patch:

![image](https://user-images.githubusercontent.com/50471577/219947438-8024683f-a62d-444a-aad0-c655d13eaad1.png)

**Comment by quantrpeter** [comment]
using node 18, no luck

![image](https://user-images.githubusercontent.com/50471577/219948216-9556f259-58a4-4141-9dfc-6fca0de24550.png)

**Comment by quantrpeter** [comment]
what node version we should use. Below info are misleading

![image](https://user-images.githubusercontent.com/50471577/219948296-1d4bbe56-e711-4f79-afd7-c10ba5794313.png)

**Comment by darrelhong** [comment]
Issued a PR to update the README, node 18 should be used for this project. node-gyp is pretty common on windows, could maybe try to install the package globally and refer to the docs for any window specific instructions. https://github.com/nodejs/node-gyp. For the second pic, you may be using node 16 instead 18, can try to confirm with `node -v`

**Comment by justynoh** [comment]
The readme has been updated. As Darrel mentioned, the problem does not seem to be with Mac but rather with webpack-cli on build. Have updated the issue name to reflect this

**Comment by justynoh** [comment]
Closing this issue since there's been no further conversation, feel free to open another issue if you require more clarification!

**Comment by darrelhong** [comment]
@justynoh unrelated but i realised the backend service won't start without first building react frontend, could look into not requiring dist/frontend to be available on local dev

**Comment by darrelhong** [comment]
@quantrpeter if you are still facing the issue, it might be due to conflicting webpack versions in the root project
installing webpack-cli v4 in the frontend project may help solve the issue
`npm install webpack-cli@4.10.0 --save-dev --legacy-peer-deps`
