### ISSUE TITLE
Image field schema breaks principle of dependency injection

### ISSUE THREAD

**Issue by r00dgirl** [opengovsg/FormSG#58]
Currently the Image field schema saves the full URL, like this:

```javascript
let imageFieldSchema = () => new Schema(
  {
    url: {
      type: String,
      required: true,
      validate: {
        validator: (url) => validator.isURL(url, { allow_underscores: true }),
        message: `Please ensure that your url is in the valid format`,
      },
    },
    fileMd5Hash: {
      type: String,
      required: true,
    },
    name: {
      type: String,
      required: true,
    },
    size: {
      type: String,
      required: true,
    },
  },
)
```

This schema breaks the principle of dependency injection.

For example, after duplicating FormSG production database to staging, and even after dumping all images from production S3 bucket into staging bucket, features such as form and field duplication will cease to work because the URL lookup does not respect environment variables.

**Comment by tshuli** [comment]
stale
