### ISSUE TITLE
Enable retrying payment without refilling form

### ISSUE THREAD

**Issue by wanlingt** [opengovsg/FormSG#5806]
Test with all the errors listed here: https://stripe.com/docs/testing#declined-payments

![Image](https://user-images.githubusercontent.com/107169604/223599541-d5586efa-11f9-4cf8-8fae-f58c6788273f.png)

![Image](https://user-images.githubusercontent.com/107169604/223599598-cae64b76-9f0b-4802-af62-15ee34f481f8.png)

![Image](https://user-images.githubusercontent.com/107169604/223599663-c60a23e0-6e8b-4ac1-9b43-8250c8085bcc.png)
![Image](https://user-images.githubusercontent.com/107169604/223599703-6e87d710-f77c-4814-abb6-63da13b7153c.png)

Special tests for 3D Secure: https://stripe.com/docs/testing#regulatory-cards

**Comment by LinHuiqing** [comment]
Solution can be in the form of [#5932](https://github.com/opengovsg/FormSG/issues/5932)

**Comment by justynoh** [comment]
Closing as duplicate
