### ISSUE TITLE
Add email field to stripe payment element

### ISSUE THREAD

**Issue by wanlingt** [opengovsg/FormSG#5810]
If user has email, receipt will be sent to that email
If email is not provided, user can still download the receipt but we will not send (obviously)

=> email is optional

**Comment by amitogp** [comment]
@wanlingt we can close this ticket as we are adding email field in the confirmation modal before payment page.

**Comment by LinHuiqing** [comment]
Yea I think with the new flow and our decision of just giving them all the payment-related information, this is no longer required.

**Comment by LinHuiqing** [comment]
Sorry, didn't realise it'll close as completed 😅
