### ISSUE TITLE
Determine metrics to track on payments dashboard

### ISSUE THREAD

**Issue by foochifa** [opengovsg/FormSG#5824]
We should have the dashboard ready

Questions to be answered
- How many users are on payment 
- On payment flow
  - How many users created payment but didn't complete payment
  - How many users successfully paid
- How many forms are payment forms

**Comment by wanlingt** [comment]
Dashboard [here](https://app.datadoghq.com/dashboard/ryu-zku-x7n/formsg-payments?from_ts=1680682411107&to_ts=1681287211107&live=true) (still WIP)

**Comment by wanlingt** [comment]
Some stats will be on DD payments dashboard, and some on MongoDB charts. The ones on MongoDB charts are only available when payments is on prod, as the charts use the prod analytics node (so blocked for now).

Another option is to get these mongodb queries onto datadog, which we do plan to do in the future - related issue #6107
