### ISSUE TITLE
Delete publishable key from form model when account is unlinked

### ISSUE THREAD

**Issue by justynoh** [opengovsg/FormSG#5848]
![Image](https://user-images.githubusercontent.com/25571626/221742096-a5aa98a7-2c5c-432a-9d44-d96bcc9c4393.png)

removePaymentAccount does not overwrite `publishableKey` :(

Dependency
- #6012

**Comment by foochifa** [comment]
![image](https://user-images.githubusercontent.com/59867455/227851680-1bb2049a-4c0b-4407-83c6-6fcaf5541a46.png)

Currently, payment channel properties are set as optional as we only remove the target_account_id in removePaymentAccount. We should remove the entire payment channels instead. And make the above properties required.

**Comment by KenLSM** [comment]
Note: We should first ensure that the `target_account_id` and `publishable_key` are migrated to payment records before shipping this. 

In the event that admin unlinks the account, responders will not be able to query for their payment status.

**Comment by foochifa** [comment]
Done #6036
