### ISSUE TITLE
Clone pending submission to submission collection when charge succeeds

### ISSUE THREAD

**Issue by timotheeg** [opengovsg/FormSG#5870]
* Clone pending submission to submission collection
* Update payment document with:
    * submission id
    * status to charged

steps B6B, B7, B8

**Comment by wanlingt** [comment]
closely linked to #5817

**Comment by amitogp** [comment]
Contingent on the outcome of #5899

**Comment by KenLSM** [comment]
@justynoh cmiiw #5944 should have covered this completely -- want to see if we can close this early
