### ISSUE TITLE
Get email from payment element

### ISSUE THREAD

**Issue by timotheeg** [opengovsg/FormSG#5873]
We need to get the respondent emial from the payment element and transfer it to a user object when we call stripe, to ensure emails are sent:

[documentation](https://stripe.com/docs/js/elements_object/create_payment_element#payment_element_create-options-fields-billingDetails-email)

**Comment by timotheeg** [comment]
On the long term, we cannot rely on the email from payment element, because payNow doesn't have an email ID.

**Comment by amitogp** [comment]
Can close this ticket if we are planning to capture email from confimation modal before payment page.

**Comment by foochifa** [comment]
Closed in favour of #5897, adding email to payment field in form
