### ISSUE TITLE
Add all payment information before proceed to pay button

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#5896]
Respondent should know about the payment amount aand payment description, before clicking submiting the form and proceeding to pay.

@staceytan1998 please link design for this.

**Comment by staceytan1998** [comment]
Payment amount and description on public form: [here](https://www.figma.com/file/CMq0CJtawn7NGM7Zdpi8Ti/Form-Design-Master?node-id=15512-139831&t=DZOtFjsg3EvHBCU7-4)

**Comment by amitogp** [comment]
Commented on the Figma design:
We don't have a sub-description for payment. Hence the GST line would not be required.

**Comment by KenLSM** [comment]
Closed (pending PR link from chifa)

**Comment by foochifa** [comment]
#5917
