### ISSUE TITLE
Choose a strategy (pending submission collection VS submission with pending flag)

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#5899]

**Comment by KenLSM** [comment]
## Creating Pending Submission Collection

**For**
- clean `submission` collection

**Against**
- index shown to user can be a different index (mongo's object id vs our own id)
  - our own index should be independent of how mongo stores it
  - best to not couple our new concept of submission lifecycle with mongodb's generation. We should create our own index to handle it.
  - mongoobject id is not random, thus information on our tables may be exposed/guessed. i.e., when it was submitted (this may not be a valid concern)

## Submission with pending flag

**For**
- single index that user can track, less confusing/frustration for user

**Against**
- need to create index on a boolean value (not sure if this is efficient on mongo)

## Creating a holding entry on submissions table

**Comment by KenLSM** [comment]
We will proceed with our current plans of `Creating Pending Submission Collection` and look at the problem of creating a unified ID at a later stage.

Context:
Having multiple IDs shown to the user is undesired but non-blocking.

**Comment by KenLSM** [comment]
Chosen `pending_submission`
