### ISSUE TITLE
MOE embedded form loading in Angular

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#5920]
**Describe the bug**
MOE Form https://www.moe.gov.sg/feedback is an embedded form that is still loading in Angular instead of React

**To Reproduce**
1. Go to https://www.moe.gov.sg/feedback
2. The form will load in Angular

**Expected behavior**
The form should load in React

**Screenshots**
<img width="730" alt="image" src="https://user-images.githubusercontent.com/107169604/224647091-eaca4484-5269-4d9d-9d66-820142d760f2.png">

**Comment by darrelhong** [comment]
Problem: 
/embed routes handled by PublicFormController.handleRedirect
returns angular index.html [`index.server.view.html`](https://github.com/opengovsg/FormSG/blob/09820aebae29e8227553857b713d970f74ba0ec3/src/app/views/index.server.view.html#LL16C37-L16C37)
calls /api/v3/client/redirect  
return js snippet [`window.location.hash = "#!/<%= redirectPath%>"`](https://github.com/opengovsg/FormSG/blob/09820aebae29e8227553857b713d970f74ba0ec3/src/app/modules/frontend/frontend.controller.ts#L107)
updates `window.location.hash` from `https://www.form.gov.sg/5e608f156bbaaf0011222f04/embed` -> `https://www.form.gov.sg/#!/5e608f156bbaaf0011222f04`

this should cause another redirect to /:formId but it does _not_ seem to do so when embedded in an iframe

Solution:
handle /embed routes in migration router, simply redirecting to /:formId

https://github.com/opengovsg/FormSG/compare/develop...darrelhong:FormSG:fix/embed

**Comment by packirisamykaran** [comment]
Hi I would like to contribute to this project. Guide me on how I can help fix this issue

**Comment by darrelhong** [comment]
@packirisamykaran nice, have you already got the project running locally? Do refer to the README for info. If you encounter any issues can seek help here

**Comment by packirisamykaran** [comment]
ok thanks I'll get started 

> @packirisamykaran nice, have you already got the project running locally? Do refer to the README for info. If you encounter any issues can seek help here

ok thanks I'll get started
