### ISSUE TITLE
rate limit the downloadPaymentReceipt endpoint

### ISSUE THREAD

**Issue by wanlingt** [opengovsg/FormSG#5924]
We should add rate limits to the route GET `/receipt/:formId/:submissionId/download` in `payments.routes.ts`

Rationale for rate limit:
* endpoint does external calls to stripe, so we want to make sure we can't be used as a source of abuse
* pdf generation is heavy, so we should protect our capacity

**Comment by KenLSM** [comment]
Completed in 
- #5927
