### ISSUE TITLE
Create dedicate payment page with unique url

### ISSUE THREAD

**Issue by KenLSM** [opengovsg/FormSG#5932]
Can be used for #5806 

Dependency
- #5872
- #5870

**Comment by KenLSM** [comment]
To breakdown into smaller tasks
Dedicated pay page

- [x] [FE] Split to different URL
- [x] [BE] Support api `/payment/:paymentId/getinfo` (payment info)
- [x] [BE] Support api `/payment/:paymentId/status` (receipt/BE sync status)
- [x] [FE] Support polling
- [x] [FE] Refactor for handling receipt
- [x] [BE] Refactor for handling receipt
- [x] [FE] redirection from proceed to pay should lead to new pay url
- [x] [BE] form submission should be stored in in pending_submission collection

**Comment by justynoh** [comment]
From @wanlingt 

Test with all the errors listed here: https://stripe.com/docs/testing#declined-payments

**Comment by KenLSM** [comment]
Additional tasks
7. redirection from proceed to pay should lead to new pay url
8. form submission should be stored in in pending_submission collection
