### ISSUE TITLE
Payment description should mention its significance

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#5956]
Payment description should mention:
"This will appear in the payment receipt"

**Comment by foochifa** [comment]
@staceytan1998 need design help for this!

**Comment by staceytan1998** [comment]
design [here](https://www.figma.com/file/CMq0CJtawn7NGM7Zdpi8Ti/Form-Design-Master?node-id=15512-139590&t=Ekrjxw79Ccc7TWpM-4)

**Comment by foochifa** [comment]
Done PR #5998
