### ISSUE TITLE
Add payout information and receipt number to response ui and csv

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#5957]
Following payment information should show up in the response:
Payment_id
Payment_status
Payment_amount
Payment_date
Payout_status
Payout_date
Payout_id
Payout_trace_id
Transaction_fee
Receipt_number

**Comment by amitogp** [comment]
Requires investigation and discussion

**Comment by wanlingt** [comment]
`receipt_number` is available for the [charge object](https://stripe.com/docs/api/charges/object) - we might need to update the payments object to store this additional property (at the same time when we store the `receipt_url`)
