### ISSUE TITLE
Stop respondent from making payment if the form has been modified

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#5959]
We should not allow the respondent to proceed to pay or even make a payment if the admin has made any change in the form or made changes in payment amount/description.

**Comment by amitogp** [comment]
Waiting for 
- [Removed]~#5958~

**Comment by foochifa** [comment]
@amitogp how aggressive should we be for checking form modification:

1. We could be hyper aggressive and track every small change (e.g. changes to form title, some description items etc)
2. We could only check for form & payment field changes
3. We could only check for payment field changes

Thanks @justynoh

**Comment by amitogp** [comment]
The level of aggressiveness should be same as what we currently have for
stopping the respondent from submitting a non-payment form. This applies to
both “proceed to pay” and “pay now” buttons.

**Comment by justynoh** [comment]
we don't do this for storage mode forms, as only email mode forms can be backend-validated. should this still be relevant for our implementation then?

**Comment by KenLSM** [comment]
Dropped to P4 as there is a workaround to request not to modify the form.
