### ISSUE TITLE
Make captcha mandatory for payment forms

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#5963]
Recatcha saves us from fraud attacks such as: Card testing attack

**Comment by amitogp** [comment]
Confirm with Girish.

**Comment by KenLSM** [comment]
To clarify with Girish on which scenario is recommended.

Scenario 1:
Form Filled -> Captcha -> createPaymentIntent -> Pay Now

Scenario 2:
Form Filled -> createPaymentIntent -> Captcha -> Pay Now

Additional Context:
- Stripe can potentially add a captcha between `createPaymentIntent` and `Pay Now`

**Comment by amitogp** [comment]
Scenario 1 looks better if Stripe can add captcha between createPaymentIntent and Pay Now. 
No need to make recaptcha mandatory if Stripe has their captcha in place.
@KenLSM

**Comment by KenLSM** [comment]
It is recommended by Stripe to have Captcha, but checking further on whether it is common to have both captcha (pre-PI, and Stripe Element + Customer Signal) available

**Comment by KenLSM** [comment]
Quoting in verbatim:
> I checked internally - Captcha from Stripe is not something you should rely on for a card testing attack. We still require the merchant to have their own mechanism to block card testing

@amitogp With that, it seemed to be best that we keep our captcha at the cost of more friction for users. Workarounds, in the event that we are blocking too many users, would be to disable it on the form itself as you've mentioned.
