### ISSUE TITLE
Local storage mode to track incomplete submissions/payments

### ISSUE THREAD

**Issue by timotheeg** [opengovsg/FormSG#5970]
In local storage, add a marker that a form submission and payment has been submitted and is ongoing. The marker can be deleted when the payment flow is complete.

If the form page is loaded while the marker is present and recent (recency specifications TBD), we can query FormSG's server to check the status of the submission, inform the user of the details, and ask the user if:
1.  he/she is sure she wants to proceed to make a new submission
2. proceed to payment page if the submission was pending

Dependency
- #5932

**Comment by amitogp** [comment]
Blocked by dedicated payment page.

**Comment by LinHuiqing** [comment]
Design work required for toasts in the case of incomplete stuff!

**Comment by KenLSM** [comment]
Design/UX Required:
- Showing of toast, when + where
- Dismissal of toast (to have a "x" or text or something brilliant)

Probable Copies Required:
- "You have a previous payment action [here](url)"
- "Forget me"

Eng constraints:
- Prompt to clear can show anywhere
- Saving/updating submissions in storage can only be done after user clicks `Proceed to Pay` as we will track the `paymentId`
