### ISSUE TITLE
Recaptcha for payments, if rendered beyond the screen cannot be scrolled

### ISSUE THREAD

**Issue by FormSG-Ops** [opengovsg/FormSG#6002]
Unable to scroll and you have to manually zoom out

![IMG_3768](https://user-images.githubusercontent.com/103998698/228177046-c717e704-e3c3-49c6-befa-65725a588a59.jpg)

**Comment by LinHuiqing** [comment]
How urgent / important is this actually 😅 compared to payments / the other issues we have

**Comment by foochifa** [comment]
Technically, the user can circumvent this by zooming out. But it really depends on the competency of the respondents, for those who don't know how to manoeuvre it, the form become unfillable

**Comment by foochifa** [comment]
Cause: Payment modal locks scrolling

Two solutions for this thanks @KenLSM 
1. remove scroll lock in payment modal (not recommended from chakra for accessibility?)
2. **close modal before rendering captcha** (not sure if there are design consideration for this) (Stacey is okay for this!)

**Comment by KenLSM** [comment]
Design confirmed that option 2 is acceptable.
