### ISSUE TITLE
Investigate how to better identify metrics for scaling

### ISSUE THREAD

**Issue by wanlingt** [opengovsg/FormSG#6005]
To better cope with surge in traffic

Possible metrics:
- CPU load
- number of hits on FE and BE
  - form-specific (eg NDP / CEA) and across all forms? 
  - Measuring FE hits: Fetching of form is fast, submission of form is slower. Relying on fetching of form would give us a faster signal

**Comment by sebastianwzq** [comment]
Moved to linear for tracking
