### ISSUE TITLE
On closed forms, responders who have completed the payment should still be able to view their receipts

### ISSUE THREAD

**Issue by KenLSM** [opengovsg/FormSG#6012]
Currently the page will display `form not found` instead of the payment page.

![Image](https://user-images.githubusercontent.com/12391617/228501886-bfd7f25e-c3dd-4944-b377-9f67b487a8ae.png)

We should still show the payment page with receipt even if the form is closed.

**Comment by KenLSM** [comment]
As `formId` detection is verified before the `paymentId` is executed, we will need to introduce a different logic for `forms with payments` or `payment page` itself.

**Comment by justynoh** [comment]
is it necessary to gate the payment page behind `:formId`? what if we have a separate routing for `/payment/:paymentId`
