### ISSUE TITLE
API to allow setting up webhook in form

### ISSUE THREAD

**Issue by timotheeg** [opengovsg/FormSG#6013]
Integrations like Zapier and Plumber generate a webhook for form submission to be sent to, and subsequently build any automation users want and need.

Manually integrating is annoying however. The integration tool generates a webhook url, that the users need to copy into the form settings.

Ideally, the integration could set the webhook url automatically, by acting on the user's behalf (typically with oauth authorization). Even more ideally, we would have audit logs of who made the change (the users should be logged in), although at the moment, we do not have audit logs. 

Still, if a user knows the formid and form private key, these 2 information could constitute a loose identification that is good enough to perform a change. It's not an identification that is individual (several admins and collaborators can have the key), but it is still a mark of ownership.

Now, the private key should never be sent to the formSG servers, but a 2-calls challenge mechanism could be devised to allow identification. Something like this:

1) caller calls` GET /admin/forms/<id>/key_challenge`
1a) formsg gets form definition and retrieves form's public key
1b) formsg computes a random nonce and encrypts it with the public key
1c) formsg stores the clear value of the nonce in a short lived-store under a random reference id (60s expiry max)
1d) formsg returns the encrypted nonce and the reference id to the caller
2) caller uses the private key to decrypt the encrypted nonce
3) caller calls `POST /admin/forms/<id>/set_webhook` (w/ payload: `{ admin_email, reference_id, nonce_value, webhook_url }`)
3a) formsg verifies call:
3a1)`nonce_value` should match stored value
3a2)admin_email should be owner (or collaborator?)
3b) if validation matches, formsg sets the `webhook_url` in the form definition
3c) formsg deletes the nonce from the store

⚠ This issue should be discussed further before implementation and get approval from PM and Tech Lead.

Considerations to discuss:
* The private key never travels to the formsg server ✅
* This implementation allows ownership of the private key to be a form of authentication. Is that wise/desirable?
    - possibly the challenge flow could be secured with MTLS and only available to trusted services like plumber, where we know the admins would have logged in, and we know we can have some trust to the `admin_email` provided.

**Comment by sebastianwzq** [comment]
Moved to linear for tracking
