### ISSUE TITLE
Shift Payment Drawer from Payment Tab to Build and Design Tab

### ISSUE THREAD

**Issue by foochifa** [opengovsg/FormSG#6018]
As seen in Form Design master, there is no payment tab in the side bar, instead payment should exists as a tab in the Build and Design Tab -> Field List Drawer.

This will affect how we render the payment content as well

From: 

![Image](https://user-images.githubusercontent.com/59867455/231409601-9d6a9725-fc8b-4494-94b7-7e74bf9bc430.png)

To:

![Image](https://user-images.githubusercontent.com/59867455/231409711-33f149d0-5322-4b15-b1ec-33878bb97de5.png)

**Comment by tutntut** [comment]
Need to amend guide 
- Change of payment field location
- No need to toggle payment since it is automatic after connecting to Stripe
