### ISSUE TITLE
Show payment 404 if  payment/getinfo not found on BE

### ISSUE THREAD

**Issue by KenLSM** [opengovsg/FormSG#6039]
**Problem**
We currently do not have a `payment not found` error page when the `payment/:paymentId/getinfo` API returns `404`.

**Solution**
We should have an `<ErrorBoundary />` component to capture and render an error page. 

**Dependencies**
- #6001

**Comment by justynoh** [comment]
come to think of it, should this endpoint just be `GET payment/:paymentId` haha
