### ISSUE TITLE
Performance optimization for large forms

### ISSUE THREAD

**Issue by timotheeg** [opengovsg/FormSG#6045]
Large forms (>~75 fields) are very laggy in the admin interface, and somewhat laggy in the respondent view.

That makes the product unusable in these cases.

TODO:
* instrument and do performance analysis on code, to find out the bottleneck (I assume we're going to see overly heavy react render cycles for some reason)
* Experiment with solutions to improve situation, pick best fit and release

**Comment by timotheeg** [comment]
@foochifa we can consider this done yeah?

**Comment by foochifa** [comment]
The user is gonna test out on Wed morning!

tagging @kennethchangOPENGOV

There are still a few smaller perf issues such as lag when dropping the fields, some lag when editing the field, not sure if those are critical though

**Comment by timotheeg** [comment]
Thanks! And yes I think we can be open specific issues to fix those. For now, I think we can close this on successful test Wednesday.
