### ISSUE TITLE
Payment MVP internal QA

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#6049]
Happy flow and error flow QA to be performed in personal, HVB, and GSIB machines.

**Comment by KenLSM** [comment]
**Staging-alt**
- test credit card
- do we fill up our own form?

**UAT**
- live credit card
- do we fill up our own form?


**Platforms**
- PC
- Mobile

**Flow Types**
Regression [completed]
- storage mode, non-payment
- email mode, non-payment

New features
- storage mode, payment
- storage mode, payment, but payment disabled after at least one response
