### ISSUE TITLE
Generate invoice based on Stripe receipt and make it downloadable

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#6052]
Blocked by:
- #6051 

Following is @timotheeg's design:

![Image](https://user-images.githubusercontent.com/107169604/229962619-3f1a6dda-aefb-4a1c-9f4a-2317ad78095c.png)

Following are the changes suggested by JTC:
Change to - Invoice from JTC Corporation
Invoice # present – ok
JTC GST reg– ok (Note: actual number should be MB81000306)
JTC address present – ok
Change to - Invoice Date
Amount paid - ok
Description of goods/service -  this will follow the FormSG input e.g. Tender packet or IGLS packet (for Amy to confirm)
Amount charged (includes GST) – ok
Pending Amy to provide the email address for customer contact point.

**Comment by amitogp** [comment]
@timotheeg please update with the link to your script for generating invoice.

**Comment by KenLSM** [comment]
> @timotheeg please update with the link to your script for generating invoice.

Circling back on this, it's received.
