### ISSUE TITLE
Send PDF invoice to payer along with payment confirmation

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#6053]
Requires @staceytan1998's input in drafting the payment confirmation email to be sent to the payer.

**Comment by KenLSM** [comment]
> The invoice is generated on the fly (download from stripe -> insert invoice stuffs -> formatAsPdf)

> The email can be as simple as our OTP email.
> Just add a button/link to that. Generating on the fly works!
> Attachment makes sense but to save time, choose the quickest

**Comment by KenLSM** [comment]
Raising to P1 as we need this before JTC onboard

**Comment by amitogp** [comment]
**Suggested copy for email**

Subject: Your payment on FormSG was successful

Body:
Hello there,

Your payment on FormSG form: <FORM_TITLE> has been received successfully. Your response id is <RESPONSE_ID> and your payment invoice can be found [here](invoice_url).

Regards,
FormSG team

**Comment by KenLSM** [comment]
Raised to P0
