### ISSUE TITLE
Get stable submission id even at pending submission state

### ISSUE THREAD

**Issue by timotheeg** [opengovsg/FormSG#6054]
We want to be able to show the submission id in the receipt, which means it needs to be known when we create the payment intent with Stripe. 

At the moment, because we have a pending submission collection, we do not have the final submission id in the current design.

TODO:
* Find a solution to have a submission id from the beginning.

Possible suggestions (not exhaustive):
* Drop pending submission collection, use submission collection with a `pending:true|false` flag
* Create a empty object in the submission collection early on just to "reserve" an id
* Clone the pending submission into the submission collection so they share the same id across collections (how to have guarantees?)
* Any more... ?

**Comment by KenLSM** [comment]
Decision made:
- Reuse the pending submission’s ID as the submission document’s ID. 

> Ultimately, we need to reduce the overhead of user education for having multiple IDs to handle, with different IDs in different places. This will quickly become confusing for admins and respondents alike. However, since this option tampers with the global uniqueness property, we want to be sure that uniqueness is guaranteed within the submissions collection when copying over documents.
