### ISSUE TITLE
Track audit log of changes made to forms

### ISSUE THREAD

**Issue by timotheeg** [opengovsg/FormSG#6058]
Generally speaking, because forms can be edited live, submissions may have different shape overtime. In cases where a form has many collaborators, it may be confusing for form admins to know why some submissions are different from others.

Specifically for payments, since payments can be turned off, this is an even more tricky situation to know why some submissions have payment attached while some do not.

FormSG as a platform should be able to show change history to a form, so it is clear who changed what when.

Initially (Phase 1), the change log can be an internal log the FormSg team itself can refer to support admin queries.

As a more advance feature (Phase 2), the change log can be a feature for admins to see in a self-serve manner.

TODO:
- Devise and implement system to track audit log. Suggestions: an audit array in the form document themselves, create a separate audit log collection.

**Comment by tshuli** [comment]
Currently we do log all admin actions in cloudwatch, will that be sufficient for phase 1?

**Comment by sebastianwzq** [comment]
Tracking on linear
