### ISSUE TITLE
[REVIEW] Business Info (GST Reg No, Address) should be extended to form-level

### ISSUE THREAD

**Issue by KenLSM** [opengovsg/FormSG#6085]
The `GST Reg No`, and `Business Address` are read during invoice generation on the payment page (after responder has successfully paid and we've received the receipt url from stripe).

This two fields are currently stored and read from form-level details. However, as we expect large agencies to have different `GST Reg No`, and `Business Address`, we want to add support to store and alter them at the form-level.

Storing at the form-level also supports the edge case where the form is **transferred to a different agency**, but the payment channel information should still remain the same.

The agency-level information will then be used as a prefill when the admin first.

Context:
- #6078

**Comment by amitogp** [comment]
Waiting for design @staceytan1998

**Comment by KenLSM** [comment]
> Implementation should be similar to agency logo

**Comment by staceytan1998** [comment]
[Design is here](https://www.figma.com/file/CMq0CJtawn7NGM7Zdpi8Ti/Form-Design-Master?node-id=16608-164642&t=2w7DF2ttSva3SjHL-4)! 
- Use pre-fill field as GST Reg No and Address are taken from Stripe
- When user enters field and changes information, revert to normal field
- Clicking out of the field saves the changes, like the rest of the settings

**Comment by KenLSM** [comment]
Raising this to `P2` as we are onboarding more agencies over to UAT now. 

Scoping this issue to be solely exposing the gst reg + address to be editable and set on form.
- ❗ Prefill requirements can be dropped (create a new issue it is dropped)

**Context**
To only way to set this up is to be handled by SWE which is not efficient.
