### ISSUE TITLE
Payment fields should be disabled until the payment toggle is enabled

### ISSUE THREAD

**Issue by foochifa** [opengovsg/FormSG#6090]
This should reference other field's BasicField settings. When the drawer is first opened without any payment_fields existing in PaymentStore, enabled should be default toggled on.

E.g. Creating a short text will have default required enabled in the drawer (no BE calls are made yet)

And if the user cancels the field drawer (instead of saving), the field will disappear from the form. Hence, there will be no confusion on whether payment is enabled in the form.

This is blocked by #6018 

i.e.

![Image](https://user-images.githubusercontent.com/59867455/231414312-be6f8477-7446-41f8-a461-d46609e32424.png)

**Comment by amitogp** [comment]
Enable payment toggle doesn't have to be on by default. It should get enabled when the user starts inputting any payment details.

Another option can be keeping payments disabled by default and the payment fields remain disabled until the user enabled payments.

**Comment by foochifa** [comment]
Oh sorry my description wasn't clear enough, it follows your point 1 @amitogp 

So after the user connects the stripe account and goes to `create` then `paymentTab` (means no payment_field exist yet), the tab should default display enabled as toggled on (this is only on the FE, no BE calls are made yet)

As the admin must have connected the stripe account and access the paymentTab to enable payments, it make sense for us to default enable it.

However, the admin cannot save the field until he fields in the 'Product/Service Name' and 'Payment Amount', if he cancels at any point before saving field, payment will not be enabled (same behaviour as other fields)

**Comment by amitogp** [comment]
@foochifa I have updated the title based on the discussion yesterday. Please let me know if you have any doubts.

**Comment by foochifa** [comment]
Disabling of payment fields is done [here](https://github.com/opengovsg/FormSG/pull/6130)
