### ISSUE TITLE
Replace receipt url in payment response info and CSV with invoice URL

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#6094]
![Image](https://user-images.githubusercontent.com/107169604/231655284-cfe9bc1a-2567-45b2-98b2-42139cafe70c.png)

As we only provided simplified tax invoice as proof of payment, we should only invoice URLs rather than Receipt's.

**Comment by KenLSM** [comment]
In the same spirit as https://github.com/opengovsg/FormSG/issues/6053#issuecomment-1512486804

**Comment by KenLSM** [comment]
Raising to P1 as we need this before JTC onboard

**Comment by KenLSM** [comment]
Raised to P0.
