### ISSUE TITLE
Investigate if it's possible to inject env into our cloudwatch to DD logs

### ISSUE THREAD

**Issue by wanlingt** [opengovsg/FormSG#6108]
When we want to look at cloudwatch logs from different environments in DD, we have to change the host. It would be easier to toggle this according to env instead.
<img width="246" alt="image" src="https://user-images.githubusercontent.com/56983748/232648984-ddc6428d-87cb-42bc-a898-62436ccbeae6.png">

Check if it's possible to inject `env` - maybe in the lambda itself. Might have to create separate lambdas (cloudwatch to DD) for each environment

**Comment by sebastianwzq** [comment]
Tracking on linear
