### ISSUE TITLE
Format table and checkboxes Zapier responses

### ISSUE THREAD

**Issue by wanlingt** [opengovsg/FormSG#6110]
This is how Plumber does it and splits the array of elements into individual components.

<img width="851" alt="image" src="https://user-images.githubusercontent.com/103998698/232668742-4e35afaa-d899-43be-aa45-ac1ca4aac117.png">

Currently in FormSG - Zapier integration, the array still outputs as a string and you need to delimit by comma

<img width="851" alt="image" src="https://user-images.githubusercontent.com/103998698/232668886-f0f408c1-c6e4-4d88-8800-52b5cfeec767.png">

Ideal state:
Map selected checkbox to the form field, show a blank option if checkbox is not selected

**Comment by sebastianwzq** [comment]
Tracking on linear
