### ISSUE TITLE
Fix drag lag in form builder

### ISSUE THREAD

**Issue by timotheeg** [opengovsg/FormSG#6121]

**Comment by karrui** [comment]
Note that if we use virtualisation, search and print will not work properly. 

I have some ideas to improve perf of the form builder:

We are currently rendering each field using `FieldRowContainer`, which is way too heavy. The container should realistically be loaded only when the field is active. We should render something less heavy (display only component, maybe?) when the field is not active. I think this could improve the perf and is worth a try.

**Comment by foochifa** [comment]
Yep! Thats what we have explored, found a way to react memo the fieldrows and by extracting out some of the hooks to the parent builderfield we were able to avoid most of the re-renders (Though there are still a few unnecessary ones including the updating of the field index for non-edited fields)

**Comment by foochifa** [comment]
Like this! my intel mac a bit lag when recording

https://user-images.githubusercontent.com/59867455/233533791-795abe16-356a-49df-a748-82b784090e63.mov
