### ISSUE TITLE
Make payout status always visible on payments details in response

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#6143]
Admins should not have to wonder whether they have received the payout or not.

**Comment by justynoh** [comment]
This one is done already, it will be displayed when we receive the payout details. Can this be closed?

**Comment by amitogp** [comment]
I changed the title and description now. Basically the admins should always have the visibility on payout status.

**Comment by LinHuiqing** [comment]
Figma Design: https://www.figma.com/file/CMq0CJtawn7NGM7Zdpi8Ti/Form-Design-Master?node-id=16236-159983&t=7kdKb1U7zUzyzhBo-0

**Comment by justynoh** [comment]
still no design for when the payout details are not available yet! @staceytan1998 can help with this? the payout details don't come in until a few days later, what should we display in the payout section before that?
