### ISSUE TITLE
Setup monitors and alerts for payment errors and anomalies

### ISSUE THREAD

**Issue by timotheeg** [opengovsg/FormSG#6153]

**Comment by justynoh** [comment]
See #6023 

For webhook handler, wondering if we should return 200 OK for PaymentNotFound, so that we do not trigger alarms on this result (since live mode is shared between production and UAT). For all other 4xx and 5xx status codes, we should set alarms.

**Comment by foochifa** [comment]
☝️ This applies to finding previous payment as well (which currently returns a 404 for PaymentNotFound).

Also, for consideration, but we should have a monitor of how often the previous payment gets retrieved (previous payment returns 200)
