### ISSUE TITLE
Change UAT stripe to test mode as we already have live mode on prod

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#6156]

**Comment by wanlingt** [comment]
We need to have one live (non-test-mode) test environment for certain features e.g. Stripe only sends receipt emails on live environments. Should we make either one of the `staging` envs or `uat` a live environment for us to do testing? 

cc @KenLSM @LinHuiqing

**Comment by KenLSM** [comment]
For more context, this is for agencies that want to play around with payments without actually paying. Thus, we do need an environment that is connected to Stripe TEST. We are expecting to onboard several agencies in this few weeks.
