### ISSUE TITLE
Retrieve, check and display prompt when payment is in processing state

### ISSUE THREAD

**Issue by foochifa** [opengovsg/FormSG#6188]
Currently we have the browser STM for un-paid payments
And the email check for successful payments

However, if a payment is processing (i.e. the user entered their payment details and are waiting for their invoice/receipt), we do not have a mechanism to prompt the user back to the payment page.

This should probably be done on the email check level (simple change, just have to retrieve payment document thats also in the processing state). But will need design copy for it.

**Comment by staceytan1998** [comment]
[Design here](https://www.figma.com/file/CMq0CJtawn7NGM7Zdpi8Ti/Form-Design-Master?node-id=16682-164713&t=9kYHgGhBCSzk5E2E-4)!

**Comment by foochifa** [comment]
Eng discussion [here](https://docs.google.com/document/d/1zNiBiHLnIfbl7lNCfUNpHMTvyMy2PdZ9ikSi25VPG_s/)

**Comment by foochifa** [comment]
Blocked by #6192
