### ISSUE TITLE
Payment toggle to be enabled on first access in payment drawer

### ISSUE THREAD

**Issue by foochifa** [opengovsg/FormSG#6227]
Follows the original discussion in issue #6090 

figma for design [here](https://www.figma.com/file/CMq0CJtawn7NGM7Zdpi8Ti/Form-Design-Master?node-id=16157-160467&t=KwRN1bas0XCmwk2a-0)

After the user connects their stripe account, and then goes back to the 'create' tab to make the payment field, we should at default enable and display the field at first access.

**Comment by foochifa** [comment]
awaiting #6213

**Comment by KenLSM** [comment]
Irrelevant now as we have removed payment toggle
