### ISSUE TITLE
Performance: investigate spikes in form retrieval

### ISSUE THREAD

**Issue by timotheeg** [opengovsg/FormSG#6229]
Since SES lag has been resolved our current worst performing route is getting form definitions (> 2s), which is strange since it should be a plain read from mongodb. 

TODO: investigate why p99 for form retrieval has these spikes of bad performance. Propose fix if needed.

![Image](https://user-images.githubusercontent.com/935223/235569612-d2da206b-a6ec-4b20-b98c-66dcfdc4ec7c.png)

**Comment by KenLSM** [comment]
![Screenshot 2024-02-14 at 12 09 46 PM](https://github.com/opengovsg/FormSG/assets/12391617/7d81d749-96e3-4702-af6d-41ee2083b425)

No longer >2 for P95.
