### ISSUE TITLE
Add description to payment field

### ISSUE THREAD

**Issue by wanlingt** [opengovsg/FormSG#6233]
pending design

- modify form.payments_field definition 
- add to admin builder
- add to public form view ([figma](https://www.figma.com/file/CMq0CJtawn7NGM7Zdpi8Ti/Form-Design-Master?type=design&node-id=15512-139853&t=rDt8J3R2eyUXBrmX-0))

**Comment by foochifa** [comment]
Oh just to clarify but this is for the sub-description right? That we aren't going to submit to stripe in payments_intent?
