### ISSUE TITLE
Design Payment feature on form.gov.sg landing page

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#6240]

**Comment by staceytan1998** [comment]
Included banner to announce payments:

- [Landing page](https://www.figma.com/file/CMq0CJtawn7NGM7Zdpi8Ti/Form-Design-Master?type=design&node-id=17254-182432&t=oA3xp3bLLVURC9Rk-4)
- [Login](https://www.figma.com/file/CMq0CJtawn7NGM7Zdpi8Ti/Form-Design-Master?type=design&node-id=17254-184143&t=oA3xp3bLLVURC9Rk-4)
