### ISSUE TITLE
Design admin feedback rating

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#6241]
Start rating from 1 to 5, similar to what we have for respondents.

**Comment by staceytan1998** [comment]
Arranged a session with Justyn and Wanling on Weds to brainstorm when we want to show admin this little survey! 

[Potential designs](https://www.figma.com/file/sLYgTbw8tCQe1qmYsz9QE0/Form-Exploration?type=design&node-id=7855-190890)

[Brainstorm document](https://www.notion.so/opengov/Admin-satisfaction-be2a1a20c0c64ccdae08e1a05a449179?pvs=4)
