### ISSUE TITLE
Copy and design for payment launch

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#6245]
Copy for bulk tender

[This ticket](https://github.com/opengovsg/FormSG/issues/6085) must be released before launch.

**Comment by amitogp** [comment]
@staceytan1998 following is the suggested copy for Stripe payment setting page. Admins should see to this if they have not connected their Stripe account yet:

Link your form to a Stripe account to start collecting payments. If you do not have a Stripe account please create one by following this [onboarding guide](https://drive.google.com/file/d/1ulf46_IKo_8PJTvZ82ZYCA2sEWYg2HE8/view?usp=share_link). Please refer to the following purchase order sample or fee schedule for more information on procurement and transaction fees:
* For government agencies: [Purchase order sample](https://drive.google.com/file/d/1XoJn4NbDpf6WluLOkWNB4KKaQtQzX_Fy/view?usp=share_link)
* For healthcare institutes: [(Non-GeBiz) Fee Schedule](https://drive.google.com/file/d/1S-n1XgDa_u-5o5TWo0dn7Ycc3eEwCmvG/view?usp=share_link)

**Comment by staceytan1998** [comment]
[Design is here](https://www.figma.com/file/CMq0CJtawn7NGM7Zdpi8Ti/Form-Design-Master?type=design&node-id=15512-139797&t=hb0LSnSN264FEMuW-4)!

Decided to go with just linking out to go.gov.sg/formsg-guide-payments! Its weird to talk about purchase order (mentioned in the last step of the guide) before they get to reading the guide!
