### ISSUE TITLE
Add user education and bulk tender details on payment settings

### ISSUE THREAD

**Issue by amitogp** [opengovsg/FormSG#6249]

**Comment by LinHuiqing** [comment]
Is the copy and design for this up already? Or is that part of the task?

**Comment by staceytan1998** [comment]
@LinHuiqing Design for this is [here](https://www.figma.com/file/CMq0CJtawn7NGM7Zdpi8Ti/Form-Design-Master?type=design&node-id=17198-179617&t=oA3xp3bLLVURC9Rk-4)! 

To note:
- Admin has to check the condition for the button to be enabled
- External link leads to a direct download of the Stripe user manual (Pending Kenneth)
