### ISSUE TITLE
Bearer Token API access

### ISSUE THREAD

**Issue by timotheeg** [opengovsg/FormSG#6250]
Allow (some) formsg APIs to be usable with bearer token authentication.

Minimally:
- Update form definition
- Download responses

Consideration:
- Do we use the same namespace as session-based APIs?
- Need to figure out the format to store API token in the user objects in DB + index
- Initially, we can create API for selected admins with manual onboarding, eventually we need UI to generate and regenerate API token

Question:
- Do we have change logs so we know what's going on?

**Comment by KenLSM** [comment]
Closing as FRM-906 has been completed
