### ISSUE TITLE
Paynow should work on UAT

### ISSUE THREAD

**Issue by KenLSM** [opengovsg/FormSG#6251]
We want to support paynow on UAT

Deliverables
- doc on how to control paynow display (is it controlled by us, the platform, or user)
- able to toggle on paynow

**Comment by LinHuiqing** [comment]
Not sure if I missed this in the past - was there any discussion regarding just removing the payment methods definition on our end and simply letting form admins control this through their stripe dashboard?

**Comment by KenLSM** [comment]
Copying response from another convo for posterity

> 1. How does it work?
> * Can we enable it from our side (if so how?)
> * Can admins enable it from their side (if so how?)
> * any further eng work required to enable it?
> 2. Does it work fine with our implementation?

**Comment by LinHuiqing** [comment]
Wrote up some brief [docs on the admin and our flow for this](https://docs.google.com/document/d/1Js4zR8guyT-gREK4yTC094UZlJ96zRELTVgiviFKDEM/edit#heading=h.iu22j47aesom). 

Will make the relevant implementation changes and test on staging!
