### ISSUE TITLE
Detect possible OTP delay and show message on login page

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#629]
thinking this is something @jia1 can help to implement

thoughts on cheapest way to detect? @jia1 @karrui 

**Updated**

- **25s** after OTP requested, show blue infobox with copy below
- every time we show this notification, log timestamp and email address so we have a gauge of OTP delay occurrences
- this otp delay infobox disappears if OTP is sent again and the timer resets
- on login page, change link text 'Have a question?' to 'Need help?'

Copy:
'OTP might be delayed due to government email traffic. Please try again later, or contact us if issue persists.'

**Comment by karrui** [comment]
don't think we can detect if the mail service announces success even though the OTP does not arrive at the mailboxes yet. 

should be a front end only change; can just start a timer on the frontend and display a permanent toast if the user has not logged in after lets say 1 minute, and reset the timer when user requests for a new OTP, remove the timer when user logs in, etc

**Comment by syan-syan** [comment]
> don't think we can detect if the mail service announces success even though the OTP does not arrive at the mailboxes yet.
> 
> should be a front end only change; can just start a timer on the frontend and display a permanent toast if the user has not logged in after lets say 1 minute, and reset the timer when user requests for a new OTP, remove the timer when user logs in, etc

yup the timer is more than sufficient.. lets do 45 seconds to be conservative. I just used a timer and that seemed pretty long for an OTP.

**Comment by pearlyong** [comment]
Would suggest using a Notification instead of a Toast, as toasts are meant to be timed (appear for a few seconds and fade away), dismissable, and in direct and immediate reaction to a user action. Can see zeplin for reference: https://zpl.io/2Er4kM8
