### ISSUE TITLE
Increase attachment size options

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#662]
@tshuli not sure how much incremental effort it would be to allow 1-20mb, then remove 8-20mb for Email mode? we have some users wanting to have a 20mb attachment but they cant right now as our max individual attachment size is 7mb

**Comment by arshadali172** [comment]
Take note that the maximum size of the email that can be sent to SGMail is about 10MB, which is why we set the ceiling for attachments as 7MB

**Comment by tshuli** [comment]
Reopening after discussion at syncup today to:
- Limit intervals to 1, 2, 3, 7, 10, 20
- Shift copy of example file types to tooltip
