### ISSUE TITLE
Difficulty in translating hardcoded text within nested React tags using i18next

### ISSUE THREAD

**Issue by SeanChinJunKai** [opengovsg/FormSG#7333]
https://github.com/opengovsg/FormSG/blob/643dbc49ca2ee91c7f54770d43af4b3dbb6b98ac/frontend/src/features/login/components/SgidLoginButton.tsx#L35-L40

Shown above is the SgidLoginButton.tsx in login components. In order to translate this using i18next would require something like this: <0><0>For</0><1></1><2><0>select agencies</0></2>/0> which is quite messy

You can refer to this issue for further context: https://github.com/i18next/react-i18next/issues/928

**Comment by LoneRifle** [comment]
Thanks @SeanChinJunKai. Actually, looking at the react-i18next issue you cited, wouldn't the resulting code look something like maybe...
```ts
 <Text> 
  <Trans t={t} key="sgidLogin.forSelectAgencies">
     For{' '} 
     <Link isExternal href={SGID_VALID_ORG_PAGE}> 
       select agencies 
     </Link> 
  </Trans>
 </Text> 
```

While the locale string would look something like..
```
For <1>select agencies</1>
```

`<0><0>For</0><1></1><2><0>select agencies</0></2></0>` isn't quite it - we can leave the `<Text>` element out of the translation, and `For{' '}` renders as a single node. Further, text isn't nested within its own element, so the locale string shouldn't be wrapping standalone text within <0></0>.

See https://react.i18next.com/latest/trans-component#how-to-get-the-correct-translation-string for further examples which demonstrate my points.

**Comment by SeanChinJunKai** [comment]
@LoneRifle Sorry for the confusion. I overcomplicated it but the resulting string is  'For <2><0>select agencies</0></2>' because the {' '} counts as an element too. I think we should be able to close this issue
