### ISSUE TITLE
Introduce env var to hide frontend elements and features specific to the Singapore Government

### ISSUE THREAD

**Issue by LoneRifle** [opengovsg/FormSG#7562]
[opengovsg/formsg-on-cdk](opengovsg/formsg-on-cdk) was created to allow the rapid deployment of FormSG onto an AWS account. This would allow someone to set up their own instance of FormSG for evaluation and to explore whether it would be suitable for their use case.

We thus wish to provide the means to easily hide elements and features that are of no relevance to the deploying user. In particular, frontend elements like the Singapore Government masthead as well as Singapore-specific integrations like Singpass/MyInfo should be hidden from the platform interface.

Related to #7454.

**Comment by adriangohjw** [comment]
To what extent are we making this configurable? For example there's placeholder for input fields that uses `jane@data.gov.sg` and mentioning `FormSG` - should those be included in this scope?

**Comment by LoneRifle** [comment]
I think so? We could rethink what we use as placeholders as part of this exercise. In that example, those placeholders could be invariant to some degree

**Comment by SeanChinJunKai** [comment]
Hi @KenLSM, regarding this issue the idea that comes to mind is to use some sort of feature flags to toggle visibility of certain Singapore Government elements. What do you think?
