### ISSUE TITLE
Testing bulk attachment downloads on GSIB

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#790]
2 dec 2020, all file sizes 2.8MB
- Edge: avg 1.83s per file, 1k responses will take 30 min, no overheating
- Chrome: avg 3s per file, 1k responses will take 50 min, no overheating
- IE11: form.gov.sg is not responding due to to a long running script. we do not need to support IE11, can just message this to users on feature announcement or in the pre-download. 
- unable to test on SIS yet

**Comment by liangyuanruo** [comment]
Feature launched
