### ISSUE TITLE
Bulk attachment downloads: progress bar 

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#853]
**why**
bulk attachment downloads takes a much longer time than any other function in the app, approached only by the Csv downloads.

key to maintaining user satisfaction and eliminating frustration is to manage user expectations and allow them to plan around the lengthy download
e.g. downloading movies used to take forever but people did not mind bc it was the best available solution + progress bar showing when they can come back

**details**
based on number of responses download over total number (first iteration)

**Comment by Raphael2908** [comment]
May I contribute?

**Comment by karrui** [comment]
> May I contribute?

Ah, this has already been closed, sorry! dangling issue.

**Comment by karrui** [comment]
closed by #3965
