### ISSUE TITLE
Secret key mailto design updates

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/FormSG#9]
Related to UI fix #124 

### Save your Secret Key

Refer to zeplin https://app.zeplin.io/project/5b29ffde48eaaf6318d01b05/screen/5f2df833d0299b1c22acd717

@mantariksh **don't implement the button dropdown yet, lets just do a simple link on the word 'Email' in the info box and leave the download and copy buttons unchanged**. this is because i'm not confident that having Email in the dropdown options is sufficiently prominent, but we dont have a designer this week. if needed we can update the UI later.

## Email prefill

Subject: Secret Key to 'Form Title' has been shared with you
To: all collaborator emails

Dear collaborator, 

I am sharing my form's secret key with you for safekeeping and backup. This is an important key that is needed to access all form responses.

Form name: 'Form Title'
Form link: form.gov.sg/2098590248
Secret key: **secretkey**.

**All you need to do is keep this email as a record, and please do not share this key with anyone else.** 

Thank you for helping to safekeep my form!

## Other requirements

add event so we know when link/button is clicked, and tracker so we know when emails are opened

**Comment by liangyuanruo** [comment]
> Subject: 'Form Title' secret key shared with you

Suggest to move the form title to the back because it can be rather long

**Comment by jonathangohjy** [comment]
@syan-syan Updated some screens on Zeplin for this flow. [Here](https://app.zeplin.io/project/5b29ffde48eaaf6318d01b05/screen/5f2df833d0299b1c22acd717)

**Comment by mantariksh** [comment]
@syan-syan Unfortunately it's not easy to have the form link in the email, as at the point of downloading the secret key, the form hasn't actually been created in the database as yet. If we really need to include it, we'll need to create the form in the db earlier, then delete it in case the user exits the modal. You ok with including the form title but not form link?

**Comment by mantariksh** [comment]
also @syan-syan I don't think it's possible to request a read receipt for the email since we're not the ones sending it, @liangyuanruo do you know if there's a way for us to do that?

**Comment by syan-syan** [comment]
> @syan-syan Unfortunately it's not easy to have the form link in the email, as at the point of downloading the secret key, the form hasn't actually been created in the database as yet. If we really need to include it, we'll need to create the form in the db earlier, then delete it in case the user exits the modal. You ok with including the form title but not form link?

Yup ok lets just include the form title and not the link for the create secret key modal.

(We could also create the form first and then popup the modal again when the user tries to access from dashboard, which is prob a better UX overall, but since that would require us to remember if they had downloaded the key or not, I think its ok not to make this change until needed)

Would it be messy (code wise) to have another secret key mailto at form activation (where it says 'email two colleagues') in the activate modal that fills in the form link? @mantariksh

**Comment by mantariksh** [comment]
@syan-syan nah not messy, it's p easy. what dyou mean by 'email two colleagues'? As in put that as the link text?

**Comment by syan-syan** [comment]
@mantariksh argh sorry these notifs are going to junk! in the activate modal theres a part of the text that says 'email two colleagues' we can put in a secret key mailto link there too that does fill in the form link.

**Comment by mantariksh** [comment]
@syan-syan hmm it's slightly more complicated because in the activate form modal, we don't actually verify whether whatever the user has typed in the secret key box is correct until after they click "Activate Form". This means for e.g. they might upload the wrong secret key, then email that wrong secret key to colleagues, then later realise it was the wrong secret key. Probs worth thinking about this more before implementation, will raise at syncup

**Comment by syan-syan** [comment]
as discussed w pearly and @mantariksh 

preferred: 'permanent' green toaster on top of activate button with copy “Form activated! Email secret key to colleagues for safekeeping.” and link on the second sentence.

if too troublesome, then regular 10s toaster saying the same thing.

in both cases, replace the two current success toasters that last ~2s each

**Comment by mantariksh** [comment]
@syan-syan keeping this issue open until we decide on the button dropdown

**Comment by syan-syan** [comment]
> also @syan-syan I don't think it's possible to request a read receipt for the email since we're not the ones sending it, @liangyuanruo do you know if there's a way for us to do that?

@liangyuanruo @mantariksh  if we are not able to find out if the email was actually sent, let's put a GA event on the Email link click? 

also @mantariksh we need to put this on activation as well as described above, but can queue that after bounce handling

**Comment by mantariksh** [comment]
lol @syan-syan mailto for activate modal, GA event and bounce handling are all alr done. Except the GA event is only on the create form mailto and not the activate modal mailto, as it's not possible to put a GA event on a toastr link as far as I can tell.

**Comment by syan-syan** [comment]
> lol @syan-syan mailto for activate modal, GA event and bounce handling are all alr done. Except the GA event is only on the create form mailto and not the activate modal mailto, as it's not possible to put a GA event on a toastr link as far as I can tell.

@mantariksh my bad i saw the create but not activate in prod ytd. if it was already out, that may be a bad sign meaning its not obvious enough. we should delete the first toaster btw i.e. there should only be one toaster after activation, which is that one. can we increase duration to 20s?

**Comment by pearlyong** [comment]
@mantariksh can we change the copy slightly to make it a bit more succinct, keep it to one line, remove the Verified! toaster? this is the only toaster that should display https://zpl.io/beR8RGW
