### ISSUE TITLE
Use convict.js and type-checking for configuration management

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#92]
It is easy to make mistakes with configuration in the current codebase e.g. CSP headers.

Migrate `config.ts` to use [Convict](https://www.npmjs.com/package/convict) and its validation features for configuration management.

Additionally, explore whether configuration code can rely on TypeScript enums or [String literal types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-1-8.html#string-literal-types) so that the compiler will be able to type-check whether an incorrect value potentially results from a bug in this file.

**Comment by liangyuanruo** [comment]
Reopened due to #285

**Comment by arshadali172** [comment]
closed by https://github.com/opengovsg/FormSG/pull/287
