### ISSUE TITLE
Write tests for EditFieldActions

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#93]
We have no controller tests for the various actions to edit fields, and such tests might have caught the bug from #74. These tests should hardcode the strings from the EditFieldActions enum.

**Comment by liangyuanruo** [comment]
Superseded by https://github.com/opengovsg/FormSG/issues/815, as `EditFieldActions` is itself an anti-pattern that should be resolved by separate and well-designed API endpoints.
