### ISSUE TITLE
Convert verification service to use neverthrow

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#941]
The verification service was one of the earlier services to be converted to TypeScript, before the team took the decision to use the `neverthrow` library and avoid throwing exceptions.

TODO: convert the implementation to use said package, and re-examine the type assertions made.

Blocked by opengovsg/formsg-javascript-sdk#45

**Comment by mantariksh** [comment]
TODO: make SmsFactory interface consistent by using `Promise.reject` when Sms feature is not enabled

**Comment by mantariksh** [comment]
Closed via #1455
